// Generated by booster-apidev | 2026-04-06 19:37:30

using System.ComponentModel.DataAnnotations;

namespace ApiApp.DTOs.Customers;

public class CustomerCreateUpdateDto
{
    public string? CustomerName { get; set; }
    public string? PrimaryContactFirstName { get; set; }
    public string? PrimaryContactLastName { get; set; }
    public string? PrimaryContactJobTitle { get; set; }
    public string? PrimaryContactEmailAddress { get; set; }
    public string? BusinessPhone { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }

    [MaxLength(2)]
    public string? State { get; set; }

    public string? Zip { get; set; }
    public string? Website { get; set; }
    public string? Notes { get; set; }
}
