// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.DTOs.Customers;

public class CustomerProductSummaryDto
{
    public int ProductId { get; set; }
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public int TotalQuantity { get; set; }
    public int OrderCount { get; set; }
    public DateTime? FirstOrderDate { get; set; }
    public DateTime? LastOrderDate { get; set; }
}
