// Generated by booster-apidev | 2026-04-06 19:37:30

using System.ComponentModel.DataAnnotations;

namespace ApiApp.DTOs.Admin;

public class GenerateOrdersDto
{
    [Required]
    [Range(1, 100)]
    public int Count { get; set; }
}
