// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.DTOs.Admin;

public class SystemSettingDto
{
    public int Id { get; set; }
    public string? SettingName { get; set; }
    public string? SettingValue { get; set; }
    public string? Notes { get; set; }
}
