# Generated by booster-iac | 2026-04-06 20:14:29
# run-local.ps1 - Start the full AccessDbApp stack locally
#
# Starts API App on http://localhost:5201 and Web App on http://localhost:5200
# as background PowerShell jobs, then tails their output.
#
# Usage:
#   .\run-local.ps1
#   .\run-local.ps1 -SkipBuild
#
# To stop: Ctrl+C or close the terminal. Jobs are cleaned up on exit.

param(
    [switch]$SkipBuild
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Resolve-Path "$PSScriptRoot\..\.."
$apiProject = Join-Path $repoRoot "output\src\ApiApp"
$webProject = Join-Path $repoRoot "output\src\WebApp"

$apiUrl = "http://localhost:5201"
$webUrl = "http://localhost:5200"

Write-Host "=== AccessDbApp Local Runner ===" -ForegroundColor Cyan
Write-Host "Repo root  : $repoRoot"
Write-Host "API App    : $apiUrl"
Write-Host "Web App    : $webUrl"
Write-Host ""

# -------------------------------------------------------------------------
# Optional build step
# -------------------------------------------------------------------------
if (-not $SkipBuild) {
    Write-Host "Building solution..." -ForegroundColor Yellow
    dotnet build "$repoRoot\AppModBoosterV2x.sln" --configuration Debug --verbosity minimal
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Build failed. Fix errors and rerun, or use -SkipBuild."
        exit 1
    }
    Write-Host "Build succeeded." -ForegroundColor Green
    Write-Host ""
}

# -------------------------------------------------------------------------
# Start apps as background jobs
# -------------------------------------------------------------------------
Write-Host "Starting API App..." -ForegroundColor Yellow
$apiJob = Start-Job -Name "ApiApp" -ScriptBlock {
    param($project, $url)
    Set-Location $project
    $env:ASPNETCORE_ENVIRONMENT = 'Development'
    dotnet run --project $project --urls $url --no-build 2>&1
} -ArgumentList $apiProject, $apiUrl

Write-Host "  Job ID: $($apiJob.Id) | PID will appear in output"

Write-Host "Starting Web App..." -ForegroundColor Yellow
$webJob = Start-Job -Name "WebApp" -ScriptBlock {
    param($project, $url)
    Set-Location $project
    $env:ASPNETCORE_ENVIRONMENT = 'Development'
    $env:ApiSettings__BaseUrl = 'http://localhost:5201'
    dotnet run --project $project --urls $url --no-build 2>&1
} -ArgumentList $webProject, $webUrl

Write-Host "  Job ID: $($webJob.Id) | PID will appear in output"
Write-Host ""

# Wait a moment for startup, then display URLs
Start-Sleep -Seconds 3

Write-Host "=== Apps Starting ===" -ForegroundColor Green
Write-Host ""
Write-Host "  API App    : $apiUrl"
Write-Host "  Swagger UI : $apiUrl/swagger"
Write-Host "  Health     : $apiUrl/health"
Write-Host ""
Write-Host "  Web App    : $webUrl"
Write-Host ""
Write-Host "Press Ctrl+C to stop both apps." -ForegroundColor DarkGray
Write-Host ""

# -------------------------------------------------------------------------
# Stream job output until user cancels
# -------------------------------------------------------------------------
try {
    while ($true) {
        $apiOutput = Receive-Job -Job $apiJob 2>&1
        if ($apiOutput) {
            $apiOutput | ForEach-Object { Write-Host "[API] $_" -ForegroundColor DarkCyan }
        }

        $webOutput = Receive-Job -Job $webJob 2>&1
        if ($webOutput) {
            $webOutput | ForEach-Object { Write-Host "[WEB] $_" -ForegroundColor DarkGreen }
        }

        # Check for job failures
        if ($apiJob.State -eq 'Failed') {
            Write-Host "[API] Job failed. Check output above." -ForegroundColor Red
            Receive-Job -Job $apiJob 2>&1 | ForEach-Object { Write-Host "[API] $_" -ForegroundColor Red }
            break
        }
        if ($webJob.State -eq 'Failed') {
            Write-Host "[WEB] Job failed. Check output above." -ForegroundColor Red
            Receive-Job -Job $webJob 2>&1 | ForEach-Object { Write-Host "[WEB] $_" -ForegroundColor Red }
            break
        }

        Start-Sleep -Milliseconds 500
    }
} finally {
    Write-Host ""
    Write-Host "Stopping apps..." -ForegroundColor Yellow
    Stop-Job -Job $apiJob, $webJob -ErrorAction SilentlyContinue
    Remove-Job -Job $apiJob, $webJob -Force -ErrorAction SilentlyContinue
    Write-Host "Apps stopped." -ForegroundColor Green
}
