# Generated by booster-iac | 2026-04-06 20:14:29
# setup-identity.ps1 - Configure OIDC federated credentials for GitHub Actions
#
# Creates one Azure AD app registration per environment (dev, staging, prod),
# configures GitHub OIDC federated credentials, and assigns Contributor on the
# subscription (or per-resource-group if preferred).
#
# Prerequisites:
#   - Azure CLI logged in: az login
#   - GitHub CLI logged in: gh auth login
#   - Sufficient permissions: Application Administrator + User Access Administrator
#
# Usage:
#   .\setup-identity.ps1 -GithubOrg "myorg" -GithubRepo "myrepo" -SubscriptionId "00000000-..."
#
# Idempotent: safe to rerun. Existing app registrations and credentials are reused.

param(
    [Parameter(Mandatory = $true)]
    [string]$GithubOrg,

    [Parameter(Mandatory = $true)]
    [string]$GithubRepo,

    [Parameter(Mandatory = $true)]
    [string]$SubscriptionId,

    [Parameter(Mandatory = $false)]
    [string[]]$Environments = @('dev', 'staging', 'prod'),

    [Parameter(Mandatory = $false)]
    [string]$AppNamePrefix = 'accessdbapp'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "=== AccessDbApp OIDC Identity Setup ===" -ForegroundColor Cyan
Write-Host "GitHub Org/Repo : $GithubOrg/$GithubRepo"
Write-Host "Subscription    : $SubscriptionId"
Write-Host "Environments    : $($Environments -join ', ')"
Write-Host ""

# Verify az CLI is logged in
$account = az account show --output json 2>$null | ConvertFrom-Json
if (-not $account) {
    Write-Error "Not logged in. Run: az login"
    exit 1
}

az account set --subscription $SubscriptionId
Write-Host "Active subscription: $($account.name) ($SubscriptionId)" -ForegroundColor Green

foreach ($envName in $Environments) {
    $displayName = "sp-$AppNamePrefix-$envName"
    $resourceGroup = "rg-$AppNamePrefix-$envName"

    Write-Host ""
    Write-Host "--- Environment: $envName ---" -ForegroundColor Yellow

    # -------------------------------------------------------------------------
    # 1. App Registration (idempotent)
    # -------------------------------------------------------------------------
    $existing = @(az ad app list --display-name $displayName --output json | ConvertFrom-Json)
    if ($existing.Count -gt 0) {
        $appId = $existing[0].appId
        $objectId = $existing[0].id
        Write-Host "  App registration exists: $displayName (appId=$appId)"
    } else {
        Write-Host "  Creating app registration: $displayName"
        $app = az ad app create --display-name $displayName --output json | ConvertFrom-Json
        $appId = $app.appId
        $objectId = $app.id
        Write-Host "  Created: appId=$appId"
    }

    # -------------------------------------------------------------------------
    # 2. Service Principal (idempotent)
    # -------------------------------------------------------------------------
    $sp = @(az ad sp list --filter "appId eq '$appId'" --output json | ConvertFrom-Json)
    if ($sp.Count -eq 0) {
        Write-Host "  Creating service principal..."
        az ad sp create --id $appId --output none
        Write-Host "  Service principal created."
    } else {
        Write-Host "  Service principal exists: $($sp[0].id)"
    }

    # -------------------------------------------------------------------------
    # 3. Federated Credential for main branch (environment-scoped)
    # -------------------------------------------------------------------------
    $credName = "github-$GithubOrg-$GithubRepo-$envName"
    $subject = "repo:$($GithubOrg)/$($GithubRepo):environment:$envName"
    $existingCreds = @(az ad app federated-credential list --id $objectId --output json | ConvertFrom-Json)
    $credExists = $existingCreds | Where-Object { $_.name -eq $credName }

    if ($credExists) {
        Write-Host "  Federated credential exists: $credName"
    } else {
        Write-Host "  Creating federated credential: $credName"
        $credJson = @{
            name        = $credName
            issuer      = "https://token.actions.githubusercontent.com"
            subject     = $subject
            audiences   = @("api://AzureADTokenExchange")
            description = "GitHub Actions OIDC for $envName environment"
        } | ConvertTo-Json -Compress
        $tmpFile = [System.IO.Path]::GetTempFileName()
        Set-Content -Path $tmpFile -Value $credJson -Encoding utf8
        az ad app federated-credential create `
            --id $objectId `
            --parameters "@$tmpFile" `
            --output none
        Remove-Item $tmpFile
        Write-Host "  Federated credential created."
    }

    # Also add a credential for workflow_dispatch (no environment scope, branch-based)
    $credNameBranch = "github-$GithubOrg-$GithubRepo-main"
    $subjectBranch = "repo:$($GithubOrg)/$($GithubRepo):ref:refs/heads/main"
    $credExistsBranch = $existingCreds | Where-Object { $_.name -eq $credNameBranch }

    if (-not $credExistsBranch) {
        Write-Host "  Creating branch federated credential: $credNameBranch"
        $credJsonBranch = @{
            name        = $credNameBranch
            issuer      = "https://token.actions.githubusercontent.com"
            subject     = $subjectBranch
            audiences   = @("api://AzureADTokenExchange")
            description = "GitHub Actions OIDC for main branch push/workflow_dispatch"
        } | ConvertTo-Json -Compress
        $tmpFileBranch = [System.IO.Path]::GetTempFileName()
        Set-Content -Path $tmpFileBranch -Value $credJsonBranch -Encoding utf8
        az ad app federated-credential create `
            --id $objectId `
            --parameters "@$tmpFileBranch" `
            --output none
        Remove-Item $tmpFileBranch
        Write-Host "  Branch federated credential created."
    } else {
        Write-Host "  Branch federated credential exists."
    }

    # -------------------------------------------------------------------------
    # 4. RBAC - Contributor on subscription (idempotent)
    #    Assigned at subscription scope so the workflow can create the resource
    #    group and all resources within it on first run.
    # -------------------------------------------------------------------------
    $spObjectId = (az ad sp show --id $appId --output json | ConvertFrom-Json).id
    $scope = "/subscriptions/$SubscriptionId"

    $roleAssignments = @(az role assignment list `
        --assignee $spObjectId `
        --role Contributor `
        --scope $scope `
        --output json | ConvertFrom-Json)

    if ($roleAssignments.Count -gt 0) {
        Write-Host "  Contributor role already assigned on subscription"
    } else {
        Write-Host "  Assigning Contributor role on subscription..."
        az role assignment create `
            --assignee $spObjectId `
            --role Contributor `
            --scope $scope `
            --output none
        Write-Host "  Role assigned."
    }

    # -------------------------------------------------------------------------
    # 5. Set GitHub environment secrets
    # -------------------------------------------------------------------------
    $tenantId = (az account show --output json | ConvertFrom-Json).tenantId

    Write-Host ""
    Write-Host "  Setting GitHub secrets for $envName environment..." -ForegroundColor Cyan

    $ghToken = gh auth token 2>$null
    if (-not $ghToken) {
        Write-Warning "  gh CLI not authenticated. Run: gh auth login"
        Write-Host "  Set secrets manually:"
        Write-Host "    AZURE_CLIENT_ID       = $appId"
        Write-Host "    AZURE_TENANT_ID       = $tenantId"
        Write-Host "    AZURE_SUBSCRIPTION_ID = $SubscriptionId"
    } else {
        gh secret set AZURE_CLIENT_ID       --env $envName --repo "$GithubOrg/$GithubRepo" --body $appId
        gh secret set AZURE_TENANT_ID       --env $envName --repo "$GithubOrg/$GithubRepo" --body $tenantId
        gh secret set AZURE_SUBSCRIPTION_ID --env $envName --repo "$GithubOrg/$GithubRepo" --body $SubscriptionId
        Write-Host "  Secrets set for $envName." -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "=== Setup complete ===" -ForegroundColor Green
Write-Host "Next step: deploy infrastructure with deploy-infra.yml workflow,"
Write-Host "then run setup-sql-identity.ps1 to grant managed identity DB access."

