# Generated by booster-iac | 2026-04-06 20:14:29
# setup-sql-identity.ps1 - Grant API App managed identity access to Azure SQL Database
#
# Creates a contained database user for the API App's system-assigned managed identity
# and grants the minimum required permissions (db_datareader, db_datawriter, EXECUTE).
# Also creates the user for EF Core schema migrations (db_ddladmin).
#
# Prerequisites:
#   - Azure CLI logged in as a user with db_owner or higher on the target database
#   - SqlServer PowerShell module: Install-Module -Name SqlServer -Scope CurrentUser
#   - Managed identity must already exist (deploy API App first via deploy-infra.yml)
#
# Usage:
#   .\setup-sql-identity.ps1 -Environment dev
#
# Idempotent: checks for existing user before creating.

param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('dev', 'staging', 'prod')]
    [string]$Environment,

    [Parameter(Mandatory = $false)]
    [string]$AppNamePrefix = 'accessdbapp'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Resource names derived from environment
$resourceGroup  = "rg-$AppNamePrefix-$Environment"
$sqlServerName  = "sql-$AppNamePrefix-$Environment"
$sqlDatabaseName = "sqldb-$AppNamePrefix-$Environment"
$apiAppName     = "api-$AppNamePrefix-$Environment"
$sqlServerFqdn  = "$sqlServerName.database.windows.net"

Write-Host "=== SQL Managed Identity Setup ===" -ForegroundColor Cyan
Write-Host "Environment  : $Environment"
Write-Host "SQL Server   : $sqlServerFqdn"
Write-Host "Database     : $sqlDatabaseName"
Write-Host "API App      : $apiAppName"
Write-Host ""

# -------------------------------------------------------------------------
# 1. Verify prerequisites
# -------------------------------------------------------------------------
if (-not (Get-Module -ListAvailable -Name SqlServer)) {
    Write-Host "Installing SqlServer PowerShell module..." -ForegroundColor Yellow
    Install-Module -Name SqlServer -Scope CurrentUser -Force -AllowClobber
}
Import-Module SqlServer

# Verify az CLI login
$account = az account show --output json 2>$null | ConvertFrom-Json
if (-not $account) {
    Write-Error "Not logged in to Azure CLI. Run: az login"
    exit 1
}
Write-Host "Logged in as: $($account.user.name)" -ForegroundColor Green

# -------------------------------------------------------------------------
# 2. Get an access token for the SQL Database
# -------------------------------------------------------------------------
Write-Host "Acquiring access token for Azure SQL..."
$tokenResponse = az account get-access-token --resource https://database.windows.net --output json | ConvertFrom-Json
$accessToken = $tokenResponse.accessToken

# -------------------------------------------------------------------------
# 3. Get the API App's managed identity display name
# -------------------------------------------------------------------------
Write-Host "Looking up API App managed identity..."
$apiApp = az webapp show --name $apiAppName --resource-group $resourceGroup --output json | ConvertFrom-Json
$principalId = $apiApp.identity.principalId

if (-not $principalId) {
    Write-Error "API App '$apiAppName' does not have a system-assigned managed identity. Deploy infrastructure first."
    exit 1
}
Write-Host "  Principal ID: $principalId"

# The SQL contained user name must match the managed identity's display name (app name)
$managedIdentityName = $apiAppName

# -------------------------------------------------------------------------
# 4. Run SQL to create the contained database user and grant permissions
# -------------------------------------------------------------------------
$createUserSql = @"
-- Create contained database user for API App managed identity
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = '$managedIdentityName')
BEGIN
    CREATE USER [$managedIdentityName] FROM EXTERNAL PROVIDER;
    PRINT 'Created user: $managedIdentityName';
END
ELSE
BEGIN
    PRINT 'User already exists: $managedIdentityName';
END

-- Grant data access roles
IF IS_ROLEMEMBER('db_datareader', '$managedIdentityName') = 0
    ALTER ROLE db_datareader ADD MEMBER [$managedIdentityName];

IF IS_ROLEMEMBER('db_datawriter', '$managedIdentityName') = 0
    ALTER ROLE db_datawriter ADD MEMBER [$managedIdentityName];

-- Grant schema modification for EF Core migrations (run once after initial deploy)
IF IS_ROLEMEMBER('db_ddladmin', '$managedIdentityName') = 0
    ALTER ROLE db_ddladmin ADD MEMBER [$managedIdentityName];

PRINT 'Permissions granted to: $managedIdentityName';
"@

Write-Host ""
Write-Host "Running SQL grant commands on '$sqlDatabaseName'..." -ForegroundColor Yellow

Invoke-Sqlcmd `
    -ServerInstance $sqlServerFqdn `
    -Database $sqlDatabaseName `
    -AccessToken $accessToken `
    -Query $createUserSql `
    -Verbose

Write-Host ""
Write-Host "=== SQL identity setup complete ===" -ForegroundColor Green
Write-Host "The API App managed identity '$managedIdentityName' now has read/write/ddl access."
Write-Host ""
Write-Host "Connection string format used by ApiApp:"
Write-Host "  Server=tcp:$sqlServerFqdn,1433;Initial Catalog=$sqlDatabaseName;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication=Active Directory Managed Identity;"
