# Generated by booster-iac | 2026-04-07 15:53:19
# setup-oidc-identity.ps1 — Configures OIDC federated credentials for GitHub Actions
# Usage: .\setup-oidc-identity.ps1 -GitHubOrg <org> -GitHubRepo <repo> [-AppName northwind] [-Location eastus2]
# Idempotent — safe to rerun
#
# Creates a Microsoft Entra ID app registration with federated credentials
# for GitHub Actions OIDC authentication. Creates credentials for dev, staging, and prod environments.

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$GitHubOrg,

    [Parameter(Mandatory = $true)]
    [string]$GitHubRepo,

    [Parameter(Mandatory = $false)]
    [string]$AppName = "northwind2",

    [Parameter(Mandatory = $false)]
    [string]$Location = "eastus2"
)

$ErrorActionPreference = "Stop"

$appDisplayName = "gh-$AppName-deployer"
$environments = @("dev", "staging", "prod")

Write-Host "=== Setting up OIDC identity federation ===" -ForegroundColor Cyan
Write-Host "App Registration: $appDisplayName"
Write-Host "GitHub: $GitHubOrg/$GitHubRepo"
Write-Host "Environments: $($environments -join ', ')"

# --- Create or get App Registration ---
Write-Host "`n--- App Registration ---" -ForegroundColor Yellow
$existingApp = az ad app list --display-name $appDisplayName --query "[0]" --output json 2>$null | ConvertFrom-Json
if ($existingApp) {
    $appId = $existingApp.appId
    $objectId = $existingApp.id
    Write-Host "App Registration '$appDisplayName' already exists (appId: $appId)."
} else {
    Write-Host "Creating App Registration '$appDisplayName'..."
    $newApp = az ad app create --display-name $appDisplayName --output json | ConvertFrom-Json
    $appId = $newApp.appId
    $objectId = $newApp.id
    Write-Host "App Registration created (appId: $appId)."
}

# --- Create or get Service Principal ---
Write-Host "`n--- Service Principal ---" -ForegroundColor Yellow
$existingSp = az ad sp show --id $appId 2>$null
if ($existingSp) {
    Write-Host "Service Principal already exists for appId: $appId."
} else {
    Write-Host "Creating Service Principal..."
    az ad sp create --id $appId --output none
    Write-Host "Service Principal created."
}

# --- Create Federated Credentials for each environment ---
Write-Host "`n--- Federated Credentials ---" -ForegroundColor Yellow
foreach ($env in $environments) {
    $credName = "gh-$env"
    $subject = "repo:${GitHubOrg}/${GitHubRepo}:environment:$env"

    Write-Host "Checking federated credential '$credName'..."
    $existingCred = az ad app federated-credential show --id $objectId --federated-credential-id $credName 2>$null
    if ($existingCred) {
        Write-Host "  Federated credential '$credName' already exists."
    } else {
        Write-Host "  Creating federated credential '$credName' (subject: $subject)..."
        $credBody = @{
            name        = $credName
            issuer      = "https://token.actions.githubusercontent.com"
            subject     = $subject
            description = "GitHub Actions OIDC for $env environment"
            audiences   = @("api://AzureADTokenExchange")
        } | ConvertTo-Json -Compress

        $credBody | az ad app federated-credential create --id $objectId --parameters "@-" --output none
        Write-Host "  Federated credential created."
    }
}

# --- Assign Contributor role on subscription ---
Write-Host "`n--- Role Assignment ---" -ForegroundColor Yellow
$subscriptionId = az account show --query id --output tsv
$spObjectId = az ad sp show --id $appId --query id --output tsv

Write-Host "Assigning Contributor role on subscription..."
$existingRole = az role assignment list --assignee $spObjectId --role Contributor --scope "/subscriptions/$subscriptionId" --query "[0]" --output json 2>$null
if ($existingRole -and $existingRole -ne "[]" -and $existingRole -ne "") {
    Write-Host "Contributor role already assigned."
} else {
    az role assignment create `
        --assignee-object-id $spObjectId `
        --assignee-principal-type ServicePrincipal `
        --role Contributor `
        --scope "/subscriptions/$subscriptionId" `
        --output none
    Write-Host "Contributor role assigned."
}

# --- Output Summary ---
$tenantId = az account show --query tenantId --output tsv

Write-Host "`n=== OIDC Identity Federation Setup Complete ===" -ForegroundColor Green
Write-Host ""
Write-Host "Add these secrets to your GitHub repository settings:" -ForegroundColor Yellow
Write-Host "  Repository: $GitHubOrg/$GitHubRepo"
Write-Host "  Settings > Secrets and variables > Actions > Secrets"
Write-Host ""
Write-Host "  AZURE_CLIENT_ID:       $appId"
Write-Host "  AZURE_TENANT_ID:       $tenantId"
Write-Host "  AZURE_SUBSCRIPTION_ID: $subscriptionId"
Write-Host ""
Write-Host "Create these GitHub Environments:" -ForegroundColor Yellow
foreach ($env in $environments) {
    Write-Host "  - $env"
}
Write-Host ""
Write-Host "Each environment uses OIDC subject: repo:${GitHubOrg}/${GitHubRepo}:environment:<env>"
