// Generated by booster-webdev | 2026-04-06
using System.Net.Http.Json;
using System.Text.Json;
using WebApp.Models;

namespace WebApp.Services;

public class ApiClient
{
    private readonly HttpClient _http;
    private static readonly JsonSerializerOptions _json = new(JsonSerializerDefaults.Web);

    public ApiClient(HttpClient http)
    {
        _http = http;
    }

    // ── Customers ────────────────────────────────────────────────────────────

    public Task<PagedResult<CustomerListItem>?> GetCustomersAsync(
        string? search = null, bool activeOnly = false, int page = 1, int pageSize = 20)
    {
        var qs = BuildQs(("search", search), ("activeOnly", activeOnly ? "true" : null),
                         ("page", page.ToString()), ("pageSize", pageSize.ToString()));
        return GetAsync<PagedResult<CustomerListItem>>($"/api/customers{qs}");
    }

    public Task<CustomerDetail?> GetCustomerAsync(int id)
        => GetAsync<CustomerDetail>($"/api/customers/{id}");

    public Task<CustomerDetail?> CreateCustomerAsync(CustomerFormData data)
        => PostAsync<CustomerDetail>("/api/customers", data);

    public Task<CustomerDetail?> UpdateCustomerAsync(int id, CustomerFormData data)
        => PutAsync<CustomerDetail>($"/api/customers/{id}", data);

    public Task<bool> DeleteCustomerAsync(int id)
        => DeleteAsync($"/api/customers/{id}");

    public Task<PagedResult<OrderListItem>?> GetCustomerOrdersAsync(int customerId, int? top = null)
    {
        var qs = top.HasValue ? $"?top={top}" : "";
        return GetAsync<PagedResult<OrderListItem>>($"/api/customers/{customerId}/orders{qs}");
    }

    public Task<List<CustomerProductSummary>?> GetCustomerProductsAsync(int customerId)
        => GetAsync<List<CustomerProductSummary>>($"/api/customers/{customerId}/products");

    // ── Employees ────────────────────────────────────────────────────────────

    public Task<PagedResult<EmployeeListItem>?> GetEmployeesAsync(
        string? search = null, int page = 1, int pageSize = 20)
    {
        var qs = BuildQs(("search", search), ("page", page.ToString()), ("pageSize", pageSize.ToString()));
        return GetAsync<PagedResult<EmployeeListItem>>($"/api/employees{qs}");
    }

    public Task<EmployeeDetail?> GetEmployeeAsync(int id)
        => GetAsync<EmployeeDetail>($"/api/employees/{id}");

    public Task<EmployeeDetail?> CreateEmployeeAsync(EmployeeFormData data)
        => PostAsync<EmployeeDetail>("/api/employees", data);

    public Task<EmployeeDetail?> UpdateEmployeeAsync(int id, EmployeeFormData data)
        => PutAsync<EmployeeDetail>($"/api/employees/{id}", data);

    public Task<bool> DeleteEmployeeAsync(int id)
        => DeleteAsync($"/api/employees/{id}");

    public Task<PagedResult<OrderListItem>?> GetEmployeeOrdersAsync(int employeeId)
        => GetAsync<PagedResult<OrderListItem>>($"/api/employees/{employeeId}/orders");

    // ── Orders ───────────────────────────────────────────────────────────────

    public Task<PagedResult<OrderListItem>?> GetOrdersAsync(
        int? customerId = null, int? employeeId = null, string? status = null,
        string? sortBy = null, int? top = null, int page = 1, int pageSize = 20)
    {
        var qs = BuildQs(
            ("customerId", customerId?.ToString()),
            ("employeeId", employeeId?.ToString()),
            ("status", status),
            ("sortBy", sortBy),
            ("top", top?.ToString()),
            ("page", page.ToString()),
            ("pageSize", pageSize.ToString()));
        return GetAsync<PagedResult<OrderListItem>>($"/api/orders{qs}");
    }

    public Task<OrderDetail?> GetOrderAsync(int id)
        => GetAsync<OrderDetail>($"/api/orders/{id}");

    public Task<OrderDetail?> CreateOrderAsync(OrderFormData data)
        => PostAsync<OrderDetail>("/api/orders", data);

    public Task<OrderDetail?> UpdateOrderAsync(int id, OrderFormData data)
        => PutAsync<OrderDetail>($"/api/orders/{id}", data);

    public Task<bool> DeleteOrderAsync(int id)
        => DeleteAsync($"/api/orders/{id}");

    public Task<OrderStatusResult?> PatchOrderStatusAsync(int id, string status)
        => PatchAsync<OrderStatusResult>($"/api/orders/{id}/status", new { status });

    // ── Order Details ────────────────────────────────────────────────────────

    public Task<OrderLineItem?> AddOrderLineAsync(int orderId, OrderLineFormData data)
        => PostAsync<OrderLineItem>($"/api/orders/{orderId}/details", data);

    public Task<OrderLineItem?> UpdateOrderLineAsync(int orderId, int lineId, OrderLineFormData data)
        => PutAsync<OrderLineItem>($"/api/orders/{orderId}/details/{lineId}", data);

    public Task<bool> DeleteOrderLineAsync(int orderId, int lineId)
        => DeleteAsync($"/api/orders/{orderId}/details/{lineId}");

    // ── Products ─────────────────────────────────────────────────────────────

    public Task<PagedResult<ProductListItem>?> GetProductsAsync(
        string? search = null, bool includeSalesStats = true, int page = 1, int pageSize = 20)
    {
        var qs = BuildQs(("search", search),
                         ("includeSalesStats", includeSalesStats ? "true" : "false"),
                         ("page", page.ToString()), ("pageSize", pageSize.ToString()));
        return GetAsync<PagedResult<ProductListItem>>($"/api/products{qs}");
    }

    public Task<ProductDetail?> GetProductAsync(int id)
        => GetAsync<ProductDetail>($"/api/products/{id}");

    public Task<ProductDetail?> CreateProductAsync(ProductFormData data)
        => PostAsync<ProductDetail>("/api/products", data);

    public Task<ProductDetail?> UpdateProductAsync(int id, ProductFormData data)
        => PutAsync<ProductDetail>($"/api/products/{id}", data);

    public Task<bool> DeleteProductAsync(int id)
        => DeleteAsync($"/api/products/{id}");

    public Task<List<ProductOrderSummary>?> GetProductOrdersAsync(int productId)
        => GetAsync<List<ProductOrderSummary>>($"/api/products/{productId}/orders");

    // ── Lookup ───────────────────────────────────────────────────────────────

    public Task<List<LookupCustomer>?> GetLookupCustomersAsync()
        => GetAsync<List<LookupCustomer>>("/api/lookup/customers");

    public Task<List<LookupEmployee>?> GetLookupEmployeesAsync()
        => GetAsync<List<LookupEmployee>>("/api/lookup/employees");

    public Task<List<LookupProduct>?> GetLookupProductsAsync()
        => GetAsync<List<LookupProduct>>("/api/lookup/products");

    public Task<List<LookupOrderStatus>?> GetLookupOrderStatusesAsync()
        => GetAsync<List<LookupOrderStatus>>("/api/lookup/order-statuses");

    // ── Reports ──────────────────────────────────────────────────────────────

    public Task<SalesYtd?> GetSalesYtdAsync()
        => GetAsync<SalesYtd>("/api/reports/sales-ytd");

    public Task<List<SalesByEmployee>?> GetSalesByEmployeeAsync(int? year = null, string groupBy = "month")
    {
        var qs = BuildQs(("year", year?.ToString()), ("groupBy", groupBy));
        return GetAsync<List<SalesByEmployee>>($"/api/reports/sales-by-employee{qs}");
    }

    public Task<List<SalesByProduct>?> GetSalesByProductAsync(int? year = null, string groupBy = "month")
    {
        var qs = BuildQs(("year", year?.ToString()), ("groupBy", groupBy));
        return GetAsync<List<SalesByProduct>>($"/api/reports/sales-by-product{qs}");
    }

    public Task<InvoiceReport?> GetInvoiceAsync(int orderId)
        => GetAsync<InvoiceReport>($"/api/reports/invoice/{orderId}");

    public Task<List<EmployeeEmailEntry>?> GetEmployeeEmailListAsync()
        => GetAsync<List<EmployeeEmailEntry>>("/api/reports/employee-email-list");

    public Task<List<EmployeePhoneEntry>?> GetEmployeePhoneListAsync()
        => GetAsync<List<EmployeePhoneEntry>>("/api/reports/employee-phone-list");

    // ── Admin ────────────────────────────────────────────────────────────────

    public Task<List<AdminSetting>?> GetSettingsAsync()
        => GetAsync<List<AdminSetting>>("/api/admin/settings");

    public Task<AdminSetting?> UpdateSettingAsync(int id, string settingValue)
        => PutAsync<AdminSetting>($"/api/admin/settings/{id}", new { settingValue });

    public Task<AdminGenerateResult?> GenerateOrdersAsync(int count)
        => PostAsync<AdminGenerateResult>("/api/admin/generate-orders", new { count });

    public Task<AdminDeleteResult?> DeleteTestDataAsync()
        => DeleteWithBodyAsync<AdminDeleteResult>("/api/admin/test-data");

    // ── HTTP helpers ─────────────────────────────────────────────────────────

    private async Task<T?> GetAsync<T>(string url)
    {
        try
        {
            var response = await _http.GetAsync(url);
            if (!response.IsSuccessStatusCode) return default;
            return await response.Content.ReadFromJsonAsync<T>(_json);
        }
        catch { return default; }
    }

    private async Task<T?> PostAsync<T>(string url, object body)
    {
        try
        {
            var response = await _http.PostAsJsonAsync(url, body);
            if (!response.IsSuccessStatusCode) return default;
            return await response.Content.ReadFromJsonAsync<T>(_json);
        }
        catch { return default; }
    }

    private async Task<T?> PutAsync<T>(string url, object body)
    {
        try
        {
            var response = await _http.PutAsJsonAsync(url, body);
            if (!response.IsSuccessStatusCode) return default;
            return await response.Content.ReadFromJsonAsync<T>(_json);
        }
        catch { return default; }
    }

    private async Task<T?> PatchAsync<T>(string url, object body)
    {
        try
        {
            var content = JsonContent.Create(body);
            var response = await _http.PatchAsync(url, content);
            if (!response.IsSuccessStatusCode) return default;
            return await response.Content.ReadFromJsonAsync<T>(_json);
        }
        catch { return default; }
    }

    private async Task<bool> DeleteAsync(string url)
    {
        try
        {
            var response = await _http.DeleteAsync(url);
            return response.IsSuccessStatusCode;
        }
        catch { return false; }
    }

    private async Task<T?> DeleteWithBodyAsync<T>(string url)
    {
        try
        {
            var response = await _http.DeleteAsync(url);
            if (!response.IsSuccessStatusCode) return default;
            return await response.Content.ReadFromJsonAsync<T>(_json);
        }
        catch { return default; }
    }

    private static string BuildQs(params (string Key, string? Value)[] pairs)
    {
        var parts = pairs.Where(p => !string.IsNullOrEmpty(p.Value))
                         .Select(p => $"{p.Key}={Uri.EscapeDataString(p.Value!)}");
        var joined = string.Join("&", parts);
        return string.IsNullOrEmpty(joined) ? "" : "?" + joined;
    }
}
