// > Generated by booster-webdev | 2026-04-07 12:29:26
using System.Net;
using System.Net.Http.Json;
using WebApp.Models;

namespace WebApp.Services;

public class NorthwindApiService
{
    private readonly HttpClient _http;

    public NorthwindApiService(HttpClient http)
    {
        _http = http;
    }

    // ---- Customers ----

    public Task<List<CustomerDto>?> GetCustomersAsync(string? search = null)
    {
        var url = string.IsNullOrWhiteSpace(search) ? "/api/customers" : $"/api/customers?search={Uri.EscapeDataString(search)}";
        return _http.GetFromJsonAsync<List<CustomerDto>>(url);
    }

    public Task<CustomerDto?> GetCustomerAsync(int id) =>
        _http.GetFromJsonAsync<CustomerDto>($"/api/customers/{id}");

    public async Task<CustomerDto?> CreateCustomerAsync(CustomerRequest req)
    {
        var resp = await _http.PostAsJsonAsync("/api/customers", req);
        resp.EnsureSuccessStatusCode();
        return await resp.Content.ReadFromJsonAsync<CustomerDto>();
    }

    public async Task<CustomerDto?> UpdateCustomerAsync(int id, CustomerRequest req)
    {
        var resp = await _http.PutAsJsonAsync($"/api/customers/{id}", req);
        resp.EnsureSuccessStatusCode();
        return await resp.Content.ReadFromJsonAsync<CustomerDto>();
    }

    public async Task<bool> DeleteCustomerAsync(int id)
    {
        var resp = await _http.DeleteAsync($"/api/customers/{id}");
        return resp.IsSuccessStatusCode;
    }

    public Task<List<CustomerLookupDto>?> GetCustomerLookupAsync() =>
        _http.GetFromJsonAsync<List<CustomerLookupDto>>("/api/customers/lookup");

    public Task<List<OrderSummaryDto>?> GetCustomerOrdersAsync(int id) =>
        _http.GetFromJsonAsync<List<OrderSummaryDto>>($"/api/customers/{id}/orders");

    public Task<List<CustomerProductDto>?> GetCustomerProductsAsync(int id) =>
        _http.GetFromJsonAsync<List<CustomerProductDto>>($"/api/customers/{id}/products");

    // ---- Employees ----

    public Task<List<EmployeeDto>?> GetEmployeesAsync() =>
        _http.GetFromJsonAsync<List<EmployeeDto>>("/api/employees");

    public Task<EmployeeDto?> GetEmployeeAsync(int id) =>
        _http.GetFromJsonAsync<EmployeeDto>($"/api/employees/{id}");

    public async Task<EmployeeDto?> CreateEmployeeAsync(EmployeeRequest req)
    {
        var resp = await _http.PostAsJsonAsync("/api/employees", req);
        resp.EnsureSuccessStatusCode();
        return await resp.Content.ReadFromJsonAsync<EmployeeDto>();
    }

    public async Task<EmployeeDto?> UpdateEmployeeAsync(int id, EmployeeRequest req)
    {
        var resp = await _http.PutAsJsonAsync($"/api/employees/{id}", req);
        resp.EnsureSuccessStatusCode();
        return await resp.Content.ReadFromJsonAsync<EmployeeDto>();
    }

    public async Task<bool> DeleteEmployeeAsync(int id)
    {
        var resp = await _http.DeleteAsync($"/api/employees/{id}");
        return resp.IsSuccessStatusCode;
    }

    public Task<List<EmployeeLookupDto>?> GetEmployeeLookupAsync() =>
        _http.GetFromJsonAsync<List<EmployeeLookupDto>>("/api/employees/lookup");

    public Task<List<OrderSummaryDto>?> GetEmployeeOrdersAsync(int id) =>
        _http.GetFromJsonAsync<List<OrderSummaryDto>>($"/api/employees/{id}/orders");

    // ---- Products ----

    public Task<List<ProductDto>?> GetProductsAsync(string? search = null)
    {
        var url = string.IsNullOrWhiteSpace(search) ? "/api/products" : $"/api/products?search={Uri.EscapeDataString(search)}";
        return _http.GetFromJsonAsync<List<ProductDto>>(url);
    }

    public Task<ProductDto?> GetProductAsync(int id) =>
        _http.GetFromJsonAsync<ProductDto>($"/api/products/{id}");

    public async Task<ProductDto?> CreateProductAsync(ProductRequest req)
    {
        var resp = await _http.PostAsJsonAsync("/api/products", req);
        resp.EnsureSuccessStatusCode();
        return await resp.Content.ReadFromJsonAsync<ProductDto>();
    }

    public async Task<ProductDto?> UpdateProductAsync(int id, ProductRequest req)
    {
        var resp = await _http.PutAsJsonAsync($"/api/products/{id}", req);
        resp.EnsureSuccessStatusCode();
        return await resp.Content.ReadFromJsonAsync<ProductDto>();
    }

    public async Task<bool> DeleteProductAsync(int id)
    {
        var resp = await _http.DeleteAsync($"/api/products/{id}");
        return resp.IsSuccessStatusCode;
    }

    public Task<List<ProductLookupDto>?> GetProductLookupAsync() =>
        _http.GetFromJsonAsync<List<ProductLookupDto>>("/api/products/lookup");

    public Task<List<ProductOrderDto>?> GetProductOrdersAsync(int id) =>
        _http.GetFromJsonAsync<List<ProductOrderDto>>($"/api/products/{id}/orders");

    // ---- Orders ----

    public Task<List<OrderSummaryDto>?> GetOrdersAsync(int? customerId = null, int? employeeId = null, int? statusId = null, string? orderDate = null, int? top = null)
    {
        var qs = new List<string>();
        if (customerId.HasValue) qs.Add($"customerId={customerId}");
        if (employeeId.HasValue) qs.Add($"employeeId={employeeId}");
        if (statusId.HasValue) qs.Add($"statusId={statusId}");
        if (!string.IsNullOrWhiteSpace(orderDate)) qs.Add($"orderDate={Uri.EscapeDataString(orderDate)}");
        if (top.HasValue) qs.Add($"top={top}");
        var url = qs.Count > 0 ? $"/api/orders?{string.Join("&", qs)}" : "/api/orders";
        return _http.GetFromJsonAsync<List<OrderSummaryDto>>(url);
    }

    public Task<OrderFullDto?> GetOrderAsync(int id) =>
        _http.GetFromJsonAsync<OrderFullDto>($"/api/orders/{id}");

    public async Task<OrderSummaryDto?> CreateOrderAsync(OrderRequest req)
    {
        var resp = await _http.PostAsJsonAsync("/api/orders", req);
        resp.EnsureSuccessStatusCode();
        return await resp.Content.ReadFromJsonAsync<OrderSummaryDto>();
    }

    public async Task<OrderSummaryDto?> UpdateOrderAsync(int id, OrderRequest req)
    {
        var resp = await _http.PutAsJsonAsync($"/api/orders/{id}", req);
        resp.EnsureSuccessStatusCode();
        return await resp.Content.ReadFromJsonAsync<OrderSummaryDto>();
    }

    public async Task<bool> DeleteOrderAsync(int id)
    {
        var resp = await _http.DeleteAsync($"/api/orders/{id}");
        return resp.IsSuccessStatusCode;
    }

    // ---- Order Details ----

    public async Task<OrderLineDto?> AddOrderDetailAsync(int orderId, OrderLineRequest req)
    {
        var resp = await _http.PostAsJsonAsync($"/api/orders/{orderId}/details", req);
        resp.EnsureSuccessStatusCode();
        return await resp.Content.ReadFromJsonAsync<OrderLineDto>();
    }

    public async Task<OrderLineDto?> UpdateOrderDetailAsync(int orderId, int detailId, OrderLineRequest req)
    {
        var resp = await _http.PutAsJsonAsync($"/api/orders/{orderId}/details/{detailId}", req);
        resp.EnsureSuccessStatusCode();
        return await resp.Content.ReadFromJsonAsync<OrderLineDto>();
    }

    public async Task<bool> DeleteOrderDetailAsync(int orderId, int detailId)
    {
        var resp = await _http.DeleteAsync($"/api/orders/{orderId}/details/{detailId}");
        return resp.IsSuccessStatusCode;
    }

    // ---- Order Statuses ----

    public Task<List<OrderStatusDto>?> GetOrderStatusesAsync() =>
        _http.GetFromJsonAsync<List<OrderStatusDto>>("/api/orderstatuses");

    // ---- Reports ----

    public Task<SalesYtdDto?> GetSalesYtdAsync() =>
        _http.GetFromJsonAsync<SalesYtdDto>("/api/reports/sales-ytd");

    public Task<List<SalesByEmployeeDto>?> GetSalesByEmployeeAsync() =>
        _http.GetFromJsonAsync<List<SalesByEmployeeDto>>("/api/reports/sales-by-employee");

    public Task<List<SalesByProductDto>?> GetSalesByProductAsync(string? from = null, string? to = null)
    {
        var qs = new List<string>();
        if (!string.IsNullOrWhiteSpace(from)) qs.Add($"from={Uri.EscapeDataString(from)}");
        if (!string.IsNullOrWhiteSpace(to)) qs.Add($"to={Uri.EscapeDataString(to)}");
        var url = qs.Count > 0 ? $"/api/reports/sales-by-product?{string.Join("&", qs)}" : "/api/reports/sales-by-product";
        return _http.GetFromJsonAsync<List<SalesByProductDto>>(url);
    }

    public Task<List<SalesByProductQuarterlyDto>?> GetSalesByProductQuarterlyAsync(string? from = null, string? to = null)
    {
        var qs = new List<string>();
        if (!string.IsNullOrWhiteSpace(from)) qs.Add($"from={Uri.EscapeDataString(from)}");
        if (!string.IsNullOrWhiteSpace(to)) qs.Add($"to={Uri.EscapeDataString(to)}");
        var url = qs.Count > 0 ? $"/api/reports/sales-by-product-quarterly?{string.Join("&", qs)}" : "/api/reports/sales-by-product-quarterly";
        return _http.GetFromJsonAsync<List<SalesByProductQuarterlyDto>>(url);
    }

    public Task<List<SalesByEmployeeMonthlyDto>?> GetSalesByEmployeeMonthlyAsync(string? from = null, string? to = null)
    {
        var qs = new List<string>();
        if (!string.IsNullOrWhiteSpace(from)) qs.Add($"from={Uri.EscapeDataString(from)}");
        if (!string.IsNullOrWhiteSpace(to)) qs.Add($"to={Uri.EscapeDataString(to)}");
        var url = qs.Count > 0 ? $"/api/reports/sales-by-employee-monthly?{string.Join("&", qs)}" : "/api/reports/sales-by-employee-monthly";
        return _http.GetFromJsonAsync<List<SalesByEmployeeMonthlyDto>>(url);
    }

    public Task<List<EmployeeEmailDto>?> GetEmployeeEmailListAsync() =>
        _http.GetFromJsonAsync<List<EmployeeEmailDto>>("/api/reports/employee-email-list");

    public Task<List<EmployeePhoneDto>?> GetEmployeePhoneListAsync() =>
        _http.GetFromJsonAsync<List<EmployeePhoneDto>>("/api/reports/employee-phone-list");

    public Task<InvoiceDto?> GetInvoiceAsync(int orderId) =>
        _http.GetFromJsonAsync<InvoiceDto>($"/api/reports/invoice/{orderId}");

    // ---- Admin ----

    public Task<List<SystemSettingDto>?> GetSettingsAsync() =>
        _http.GetFromJsonAsync<List<SystemSettingDto>>("/api/admin/settings");

    public async Task<SystemSettingDto?> UpdateSettingAsync(int id, SystemSettingUpdateRequest req)
    {
        var resp = await _http.PutAsJsonAsync($"/api/admin/settings/{id}", req);
        resp.EnsureSuccessStatusCode();
        return await resp.Content.ReadFromJsonAsync<SystemSettingDto>();
    }

    public async Task<GenerateOrdersResponse?> GenerateOrdersAsync(int count)
    {
        var resp = await _http.PostAsJsonAsync("/api/admin/generate-orders", new GenerateOrdersRequest { Count = count });
        resp.EnsureSuccessStatusCode();
        return await resp.Content.ReadFromJsonAsync<GenerateOrdersResponse>();
    }

    public async Task<bool> DeleteTestDataAsync()
    {
        var resp = await _http.DeleteAsync("/api/admin/test-data");
        return resp.IsSuccessStatusCode;
    }
}
