> Generated by booster-iac | 2026-04-06 20:14:29

// parameters/dev.bicepparam - Development environment parameter values

using '../main.bicep'

param env = 'dev'
param location = 'eastus'
param planSku = 'B1'

// Replace with the Object ID of your Azure AD group for SQL administration
// az ad group show --group "YourGroupName" --query id -o tsv
param sqlAdminGroupObjectId = 'TODO-replace-with-dev-sql-admin-group-object-id'
param sqlAdminGroupName = 'TODO-replace-with-dev-sql-admin-group-name'
