// Generated by booster-iac | 2026-04-06 20:14:29
// parameters/staging.bicepparam - Staging environment parameter values

using '../main.bicep'

param env = 'staging'
param location = 'uksouth'
param planSku = 'P1v3'

// Replace with the Object ID of your Azure AD group for SQL administration
// az ad group show --group "YourGroupName" --query id -o tsv
param sqlAdminGroupObjectId = 'ba5a7772-1d04-4209-a09e-5575eb5b9a47'
param sqlAdminGroupName = 'northwind-sql-admins'
