// > Generated by booster-webdev | 2026-04-07 12:29:26
using NUnit.Framework;

namespace E2ETests;

/// <summary>
/// Full CRUD flow tests for primary resources: Customers, Products, Employees, Orders.
/// Each test creates, reads (detail), updates, and deletes a record.
/// </summary>
[TestFixture]
public class CrudFlowTests : NorthwindTestBase
{
    // =============================================
    // CUSTOMER CRUD FLOW
    // =============================================

    [Test]
    public async Task Customer_CreateReadUpdateDelete()
    {
        var uniqueName = $"Test Customer {Guid.NewGuid():N}".Substring(0, 30);

        // CREATE
        await Page.GotoAsync("/customers/create");
        await Page.FillAsync("input[name='CustomerName']", uniqueName);
        await Page.FillAsync("input[name='PrimaryContactFirstName']", "Test");
        await Page.FillAsync("input[name='PrimaryContactLastName']", "Contact");
        await Page.FillAsync("input[name='BusinessPhone']", "555-0100");
        await Page.FillAsync("input[name='City']", "Testville");
        await Page.FillAsync("input[name='State']", "TX");
        await Page.ClickAsync("button[type='submit']");

        // Should redirect to detail page
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/customers/\\d+"));
        await Expect(Page.Locator("h1")).ToContainTextAsync(uniqueName);

        // READ - verify detail page has customer name
        var detailUrl = Page.Url;
        await Expect(Page.Locator("input[name='CustomerName']")).ToHaveValueAsync(uniqueName);

        // UPDATE
        var updatedName = uniqueName.Replace("Test Customer", "Updated Customer");
        await Page.FillAsync("input[name='CustomerName']", updatedName);
        await Page.FillAsync("input[name='City']", "UpdatedCity");
        await Page.ClickAsync("button[type='submit']:has-text('Save')");
        await Page.GotoAsync(detailUrl);
        await Expect(Page.Locator("input[name='CustomerName']")).ToHaveValueAsync(updatedName);

        // DELETE
        Page.Dialog += async (_, dialog) => await dialog.AcceptAsync();
        await Page.ClickAsync("button[type='submit']:has-text('Delete')");
        // After delete, redirected to customer list
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/customers$"));
    }

    // =============================================
    // PRODUCT CRUD FLOW
    // =============================================

    [Test]
    public async Task Product_CreateReadUpdateDelete()
    {
        var code = $"TST{Guid.NewGuid():N}".Substring(0, 8).ToUpper();
        var name = $"Test Product {code}";

        // CREATE
        await Page.GotoAsync("/products/create");
        await Page.FillAsync("input[name='ProductCode']", code);
        await Page.FillAsync("input[name='ProductName']", name);
        await Page.FillAsync("input[name='UnitPrice']", "19.99");
        await Page.ClickAsync("button[type='submit']");

        // Should redirect to detail page
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/products/\\d+"));
        await Expect(Page.Locator("h1")).ToContainTextAsync(name);

        var detailUrl = Page.Url;

        // READ - verify fields
        await Expect(Page.Locator("input[name='ProductName']")).ToHaveValueAsync(name);
        await Expect(Page.Locator("input[name='ProductCode']")).ToHaveValueAsync(code);

        // UPDATE
        var updatedName = name + " Updated";
        await Page.FillAsync("input[name='ProductName']", updatedName);
        await Page.FillAsync("input[name='UnitPrice']", "24.99");
        await Page.ClickAsync("button[type='submit']:has-text('Save')");
        await Page.GotoAsync(detailUrl);
        await Expect(Page.Locator("input[name='ProductName']")).ToHaveValueAsync(updatedName);

        // DELETE
        Page.Dialog += async (_, dialog) => await dialog.AcceptAsync();
        await Page.ClickAsync("button[type='submit']:has-text('Delete')");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/products$"));
    }

    // =============================================
    // EMPLOYEE CRUD FLOW
    // =============================================

    [Test]
    public async Task Employee_CreateReadUpdateDelete()
    {
        var lastName = $"TestEmp{Guid.NewGuid():N}".Substring(0, 12);

        // CREATE
        await Page.GotoAsync("/employees/create");
        await Page.FillAsync("input[name='FirstName']", "Test");
        await Page.FillAsync("input[name='LastName']", lastName);
        await Page.FillAsync("input[name='JobTitle']", "QA Tester");
        await Page.FillAsync("input[name='EmailAddress']", $"test.{lastName}@example.com");
        await Page.FillAsync("input[name='PrimaryPhone']", "555-0199");
        await Page.ClickAsync("button[type='submit']");

        // Should redirect to detail page
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/employees/\\d+"));

        var detailUrl = Page.Url;

        // READ
        await Expect(Page.Locator("input[name='LastName']")).ToHaveValueAsync(lastName);

        // UPDATE
        await Page.FillAsync("input[name='JobTitle']", "Senior QA Tester");
        await Page.ClickAsync("button[type='submit']:has-text('Save')");
        await Page.GotoAsync(detailUrl);
        await Expect(Page.Locator("input[name='JobTitle']")).ToHaveValueAsync("Senior QA Tester");

        // DELETE
        Page.Dialog += async (_, dialog) => await dialog.AcceptAsync();
        await Page.ClickAsync("button[type='submit']:has-text('Delete')");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/employees$"));
    }

    // =============================================
    // ORDER CRUD FLOW
    // =============================================

    [Test]
    public async Task Order_CreateReadUpdateDelete()
    {
        // CREATE - navigate to create form
        await Page.GotoAsync("/orders/create");
        await Expect(Page.Locator("h1")).ToContainTextAsync("New Order");

        // Select first available customer (if any)
        var customerOptions = Page.Locator("select[name='CustomerId'] option:not([value=''])");
        if (await customerOptions.CountAsync() > 0)
        {
            var firstValue = await customerOptions.First.GetAttributeAsync("value");
            await Page.SelectOptionAsync("select[name='CustomerId']", firstValue ?? "");
        }

        // Select first available employee (if any)
        var employeeOptions = Page.Locator("select[name='EmployeeId'] option:not([value=''])");
        if (await employeeOptions.CountAsync() > 0)
        {
            var firstValue = await employeeOptions.First.GetAttributeAsync("value");
            await Page.SelectOptionAsync("select[name='EmployeeId']", firstValue ?? "");
        }

        // Set order date
        await Page.FillAsync("input[name='OrderDate']", DateTime.Today.ToString("yyyy-MM-dd"));
        await Page.FillAsync("textarea[name='Notes']", "E2E test order - can be deleted");
        await Page.ClickAsync("button[type='submit']");

        // Should redirect to order detail page
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/orders/\\d+"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Order #");

        var detailUrl = Page.Url;

        // UPDATE - change notes
        await Page.FillAsync("textarea[name='Notes']", "E2E test order - updated");
        await Page.ClickAsync("button[type='submit']:has-text('Save Order')");

        // Reload and verify
        await Page.GotoAsync(detailUrl);
        await Expect(Page.Locator("textarea[name='Notes']")).ToHaveValueAsync("E2E test order - updated");

        // DELETE
        Page.Dialog += async (_, dialog) => await dialog.AcceptAsync();
        await Page.ClickAsync("button[type='submit']:has-text('Delete')");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/orders$"));
    }

    // =============================================
    // ORDERS LIST FILTER
    // =============================================

    [Test]
    public async Task Orders_FilterByStatus()
    {
        await Page.GotoAsync("/orders");

        // Find the status dropdown
        var statusSelect = Page.Locator("select[name='statusId']");
        await Expect(statusSelect).ToBeVisibleAsync();

        // Select first non-empty status option
        var options = statusSelect.Locator("option:not([value=''])");
        if (await options.CountAsync() > 0)
        {
            var firstValue = await options.First.GetAttributeAsync("value");
            await Page.SelectOptionAsync("select[name='statusId']", firstValue ?? "");
            await Page.ClickAsync("button[type='submit']:has-text('Filter')");
            // Page should reload with filter applied
            await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("statusId="));
        }
    }

    // =============================================
    // CUSTOMERS LIST SEARCH
    // =============================================

    [Test]
    public async Task Customers_SearchFilters()
    {
        await Page.GotoAsync("/customers");
        await Page.FillAsync("input[name='search']", "contoso");
        await Page.ClickAsync("button[type='submit']");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("search=contoso"));
        // Clear search
        await Page.ClickAsync("a:has-text('Clear')");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/customers$"));
    }
}
