// > Generated by booster-webdev | 2026-04-07 12:29:26
using NUnit.Framework;

namespace E2ETests;

/// <summary>
/// Verifies the navbar links navigate to the correct pages.
/// </summary>
[TestFixture]
public class NavigationTests : NorthwindTestBase
{
    [Test]
    public async Task Navbar_LinksNavigateCorrectly()
    {
        await Page.GotoAsync("/");

        // Orders
        await Page.ClickAsync("nav a:has-text('Orders')");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/orders"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Orders");

        // Customers
        await Page.ClickAsync("nav a:has-text('Customers')");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/customers"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Customers");

        // Products
        await Page.ClickAsync("nav a:has-text('Products')");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/products"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Products");

        // Employees
        await Page.ClickAsync("nav a:has-text('Employees')");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/employees"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Employees");

        // Reports
        await Page.ClickAsync("nav a:has-text('Reports')");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/reports"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Reports");

        // Admin
        await Page.ClickAsync("nav a:has-text('Admin')");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/admin"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Admin");
    }

    [Test]
    public async Task BrandLink_NavigatesToDashboard()
    {
        await Page.GotoAsync("/customers");
        await Page.ClickAsync(".navbar-brand");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("^http://localhost:5200/?$"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Dashboard");
    }
}
