// > Generated by booster-webdev | 2026-04-07 12:29:26
using Microsoft.Playwright;
using Microsoft.Playwright.NUnit;
using NUnit.Framework;

namespace E2ETests;

/// <summary>
/// Base class for all Northwind E2E tests. Uses Chromium (default) only.
/// Set BROWSER=chromium to ensure Chromium browser; it is the default in Playwright NUnit.
/// </summary>
public abstract class NorthwindTestBase : PageTest
{
    protected const string BaseUrl = "http://localhost:5200";

    public override BrowserNewContextOptions ContextOptions() => new()
    {
        BaseURL = BaseUrl,
        IgnoreHTTPSErrors = true
    };
}
