// > Generated by booster-webdev | 2026-04-07 12:29:26
using NUnit.Framework;

namespace E2ETests;

/// <summary>
/// Verifies every page from ui-pages.md loads without errors.
/// </summary>
[TestFixture]
public class PageLoadTests : NorthwindTestBase
{
    [Test]
    public async Task Dashboard_Loads()
    {
        await Page.GotoAsync("/");
        await Expect(Page).ToHaveTitleAsync(new System.Text.RegularExpressions.Regex("Dashboard"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Dashboard");
    }

    [Test]
    public async Task OrdersList_Loads()
    {
        await Page.GotoAsync("/orders");
        await Expect(Page).ToHaveTitleAsync(new System.Text.RegularExpressions.Regex("Orders"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Orders");
    }

    [Test]
    public async Task CreateOrder_Loads()
    {
        await Page.GotoAsync("/orders/create");
        await Expect(Page.Locator("h1")).ToContainTextAsync("New Order");
    }

    [Test]
    public async Task CustomersList_Loads()
    {
        await Page.GotoAsync("/customers");
        await Expect(Page).ToHaveTitleAsync(new System.Text.RegularExpressions.Regex("Customers"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Customers");
    }

    [Test]
    public async Task CreateCustomer_Loads()
    {
        await Page.GotoAsync("/customers/create");
        await Expect(Page.Locator("h1")).ToContainTextAsync("New Customer");
    }

    [Test]
    public async Task ProductsList_Loads()
    {
        await Page.GotoAsync("/products");
        await Expect(Page).ToHaveTitleAsync(new System.Text.RegularExpressions.Regex("Products"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Products");
    }

    [Test]
    public async Task CreateProduct_Loads()
    {
        await Page.GotoAsync("/products/create");
        await Expect(Page.Locator("h1")).ToContainTextAsync("New Product");
    }

    [Test]
    public async Task EmployeesList_Loads()
    {
        await Page.GotoAsync("/employees");
        await Expect(Page).ToHaveTitleAsync(new System.Text.RegularExpressions.Regex("Employees"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Employees");
    }

    [Test]
    public async Task CreateEmployee_Loads()
    {
        await Page.GotoAsync("/employees/create");
        await Expect(Page.Locator("h1")).ToContainTextAsync("New Employee");
    }

    [Test]
    public async Task ReportsHub_Loads()
    {
        await Page.GotoAsync("/reports");
        await Expect(Page).ToHaveTitleAsync(new System.Text.RegularExpressions.Regex("Reports"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Reports");
    }

    [Test]
    public async Task SalesByProduct_Loads()
    {
        await Page.GotoAsync("/reports/sales-by-product");
        await Expect(Page.Locator("h1")).ToContainTextAsync("Sales by Product");
    }

    [Test]
    public async Task SalesByProductQuarterly_Loads()
    {
        await Page.GotoAsync("/reports/sales-by-product-quarterly");
        await Expect(Page.Locator("h1")).ToContainTextAsync("Sales by Product");
    }

    [Test]
    public async Task SalesByEmployee_Loads()
    {
        await Page.GotoAsync("/reports/sales-by-employee");
        await Expect(Page.Locator("h1")).ToContainTextAsync("Sales by Employee");
    }

    [Test]
    public async Task EmployeeEmailList_Loads()
    {
        await Page.GotoAsync("/reports/employee-email-list");
        await Expect(Page.Locator("h1")).ToContainTextAsync("Email Directory");
    }

    [Test]
    public async Task EmployeePhoneList_Loads()
    {
        await Page.GotoAsync("/reports/employee-phone-list");
        await Expect(Page.Locator("h1")).ToContainTextAsync("Phone Directory");
    }

    [Test]
    public async Task AdminPanel_Loads()
    {
        await Page.GotoAsync("/admin");
        await Expect(Page).ToHaveTitleAsync(new System.Text.RegularExpressions.Regex("Admin"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Admin");
    }

    [Test]
    public async Task AdminSettings_Loads()
    {
        await Page.GotoAsync("/admin/settings");
        await Expect(Page.Locator("h1")).ToContainTextAsync("System Settings");
    }
}
