// > Generated by booster-webdev | 2026-04-07 12:29:26
// Playwright E2E Tests - Northwind Traders WebApp
// Uses Chromium only, happy-path coverage

using Microsoft.Playwright.NUnit;
using NUnit.Framework;

[assembly: Parallelizable(ParallelScope.Self)]
