// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.DTOs.Lookup;

public class CustomerLookupDto
{
    public int Id { get; set; }
    public string? CustomerName { get; set; }
}

public class EmployeeLookupDto
{
    public int Id { get; set; }
    public string? FullNameFNLN { get; set; }
}

public class ProductLookupDto
{
    public int Id { get; set; }
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public decimal? UnitPrice { get; set; }
}

public class OrderStatusLookupDto
{
    public string Value { get; set; } = string.Empty;
    public string Display { get; set; } = string.Empty;
    public int SortOrder { get; set; }
}
