// Generated by booster-webdev | 2026-04-06
using Microsoft.Playwright;
using Microsoft.Playwright.NUnit;
using NUnit.Framework;

namespace E2ETests;

[Parallelizable(ParallelScope.Self)]
[TestFixture]
public class CrudFlowTests : PageTest
{
    private const string BaseUrl = "http://localhost:5200";

    public override BrowserNewContextOptions ContextOptions() =>
        new() { IgnoreHTTPSErrors = true };

    // ── Customer CRUD ─────────────────────────────────────────────────────────

    [Test]
    public async Task Customer_NewForm_Loads()
    {
        await Page.GotoAsync($"{BaseUrl}/Customers/New");
        await Expect(Page.Locator("h1")).ToContainTextAsync("New Customer");
        await Expect(Page.Locator("form")).ToBeVisibleAsync();
    }

    [Test]
    public async Task Customer_Create_And_View()
    {
        await Page.GotoAsync($"{BaseUrl}/Customers/New");
        await Page.FillAsync("input[name='CustomerName']", "E2E Test Customer");
        await Page.FillAsync("input[name='PrimaryContactFirstName']", "Test");
        await Page.FillAsync("input[name='PrimaryContactLastName']", "User");
        await Page.ClickAsync("button[type='submit']");
        // Should redirect to detail page on success
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/Customers"));
    }

    // ── Product CRUD ──────────────────────────────────────────────────────────

    [Test]
    public async Task Product_NewForm_Loads()
    {
        await Page.GotoAsync($"{BaseUrl}/Products/New");
        await Expect(Page.Locator("h1")).ToContainTextAsync("New Product");
        await Expect(Page.Locator("form")).ToBeVisibleAsync();
    }

    [Test]
    public async Task Product_Create_And_View()
    {
        await Page.GotoAsync($"{BaseUrl}/Products/New");
        await Page.FillAsync("input[name='ProductCode']", "E2E-TEST");
        await Page.FillAsync("input[name='ProductName']", "E2E Test Product");
        await Page.FillAsync("input[name='UnitPrice']", "9.99");
        await Page.ClickAsync("button[type='submit']");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/Products"));
    }

    // ── Order CRUD ────────────────────────────────────────────────────────────

    [Test]
    public async Task Order_NewForm_Loads()
    {
        await Page.GotoAsync($"{BaseUrl}/Orders/New");
        await Expect(Page.Locator("h1")).ToContainTextAsync("New Order");
        await Expect(Page.Locator("form")).ToBeVisibleAsync();
    }

    [Test]
    public async Task Orders_List_Shows_Table()
    {
        await Page.GotoAsync($"{BaseUrl}/Orders");
        // The orders table or an empty state should be visible
        var table = Page.Locator("table");
        var emptyAlert = Page.Locator(".alert-info");
        await Expect(table.Or(emptyAlert)).ToBeVisibleAsync();
    }

    // ── Reports ───────────────────────────────────────────────────────────────

    [Test]
    public async Task Reports_SalesByEmployee_Loads()
    {
        await Page.GotoAsync($"{BaseUrl}/Reports/SalesByEmployee");
        await Expect(Page.Locator("h1")).ToContainTextAsync("Sales by Employee");
    }

    [Test]
    public async Task Reports_SalesByProduct_Loads()
    {
        await Page.GotoAsync($"{BaseUrl}/Reports/SalesByProduct");
        await Expect(Page.Locator("h1")).ToContainTextAsync("Sales by Product");
    }

    [Test]
    public async Task Reports_EmployeeEmailList_Loads()
    {
        await Page.GotoAsync($"{BaseUrl}/Reports/EmployeeEmailList");
        await Expect(Page.Locator("h1")).ToContainTextAsync("Email Directory");
    }

    [Test]
    public async Task Reports_EmployeePhoneList_Loads()
    {
        await Page.GotoAsync($"{BaseUrl}/Reports/EmployeePhoneList");
        await Expect(Page.Locator("h1")).ToContainTextAsync("Phone Directory");
    }
}
