// Generated by booster-webdev | 2026-04-06
using Microsoft.Playwright;
using Microsoft.Playwright.NUnit;
using NUnit.Framework;

namespace E2ETests;

[Parallelizable(ParallelScope.Self)]
[TestFixture]
public class NavigationTests : PageTest
{
    private const string BaseUrl = "http://localhost:5200";

    public override BrowserNewContextOptions ContextOptions() =>
        new() { IgnoreHTTPSErrors = true };

    [Test]
    public async Task Navbar_OrdersLink_Works()
    {
        await Page.GotoAsync(BaseUrl);
        await Page.ClickAsync("a[href*='/Orders']");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/Orders"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Orders");
    }

    [Test]
    public async Task Navbar_CustomersLink_Works()
    {
        await Page.GotoAsync(BaseUrl);
        await Page.ClickAsync("a[href*='/Customers']");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/Customers"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Customers");
    }

    [Test]
    public async Task Navbar_EmployeesLink_Works()
    {
        await Page.GotoAsync(BaseUrl);
        await Page.ClickAsync("a[href*='/Employees']");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/Employees"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Employees");
    }

    [Test]
    public async Task Navbar_ProductsLink_Works()
    {
        await Page.GotoAsync(BaseUrl);
        await Page.ClickAsync("a[href*='/Products']");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/Products"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Products");
    }

    [Test]
    public async Task Navbar_ReportsLink_Works()
    {
        await Page.GotoAsync(BaseUrl);
        await Page.ClickAsync("a[href*='/Reports']");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/Reports"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Reports");
    }

    [Test]
    public async Task Navbar_AdminLink_Works()
    {
        await Page.GotoAsync(BaseUrl);
        await Page.ClickAsync("a[href*='/Admin']");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/Admin"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Admin");
    }

    [Test]
    public async Task Navbar_BrandLink_ReturnsHome()
    {
        await Page.GotoAsync($"{BaseUrl}/Orders");
        await Page.ClickAsync(".navbar-brand");
        await Expect(Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("^http://localhost:5200/?$"));
    }
}
