// Generated by booster-webdev | 2026-04-06
using Microsoft.Playwright;
using Microsoft.Playwright.NUnit;
using NUnit.Framework;

namespace E2ETests;

[Parallelizable(ParallelScope.Self)]
[TestFixture]
public class PageLoadTests : PageTest
{
    private const string BaseUrl = "http://localhost:5200";

    public override BrowserNewContextOptions ContextOptions() =>
        new() { IgnoreHTTPSErrors = true };

    [Test]
    public async Task HomePage_Loads()
    {
        await Page.GotoAsync(BaseUrl);
        await Expect(Page).ToHaveTitleAsync(new System.Text.RegularExpressions.Regex("Dashboard|Northwind"));
    }

    [Test]
    public async Task OrdersIndex_Loads()
    {
        await Page.GotoAsync($"{BaseUrl}/Orders");
        await Expect(Page).ToHaveTitleAsync(new System.Text.RegularExpressions.Regex("Orders|Northwind"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Orders");
    }

    [Test]
    public async Task CustomersIndex_Loads()
    {
        await Page.GotoAsync($"{BaseUrl}/Customers");
        await Expect(Page).ToHaveTitleAsync(new System.Text.RegularExpressions.Regex("Customers|Northwind"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Customers");
    }

    [Test]
    public async Task EmployeesIndex_Loads()
    {
        await Page.GotoAsync($"{BaseUrl}/Employees");
        await Expect(Page).ToHaveTitleAsync(new System.Text.RegularExpressions.Regex("Employees|Northwind"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Employees");
    }

    [Test]
    public async Task ProductsIndex_Loads()
    {
        await Page.GotoAsync($"{BaseUrl}/Products");
        await Expect(Page).ToHaveTitleAsync(new System.Text.RegularExpressions.Regex("Products|Northwind"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Products");
    }

    [Test]
    public async Task ReportsIndex_Loads()
    {
        await Page.GotoAsync($"{BaseUrl}/Reports");
        await Expect(Page).ToHaveTitleAsync(new System.Text.RegularExpressions.Regex("Reports|Northwind"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Reports");
    }

    [Test]
    public async Task AdminIndex_Loads()
    {
        await Page.GotoAsync($"{BaseUrl}/Admin");
        await Expect(Page).ToHaveTitleAsync(new System.Text.RegularExpressions.Regex("Admin|Northwind"));
        await Expect(Page.Locator("h1")).ToContainTextAsync("Admin");
    }
}
