// Generated by booster-apidev | 2026-04-06 19:37:30

using ApiApp.Data;
using Microsoft.EntityFrameworkCore;

using ApiApp.Data;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

// ---------- Services ----------

builder.Services.AddControllers()
    .AddJsonOptions(opts =>
    {
        opts.JsonSerializerOptions.DefaultIgnoreCondition =
            System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull;
    });

// Swagger/OpenAPI - enabled in all non-prod environments
var swaggerEnabled = builder.Configuration.GetValue<bool>("Swagger:Enabled", true);
if (swaggerEnabled)
{
    builder.Services.AddEndpointsApiExplorer();
    builder.Services.AddSwaggerGen(c =>
    {
        c.SwaggerDoc("v1", new Microsoft.OpenApi.Models.OpenApiInfo
        {
            Title = "Northwind Traders API",
            Version = "v1",
            Description = "REST API for Northwind Traders - modernized from Access .accdb"
        });
    });
}

// Database - SQLite for Development, SQL Server for all cloud environments
var env = builder.Environment;
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? throw new InvalidOperationException("Connection string 'DefaultConnection' is not configured.");

if (env.IsDevelopment())
{
    builder.Services.AddDbContext<AppDbContext>((sp, options) =>
    {
        options.UseSqlite(connectionString);
        options.EnableSensitiveDataLogging();
    });
}
else
{
    builder.Services.AddDbContext<AppDbContext>((sp, options) =>
    {
        options.UseSqlServer(connectionString, sqlOpts =>
        {
            sqlOpts.EnableRetryOnFailure(
                maxRetryCount: 3,
                maxRetryDelay: TimeSpan.FromSeconds(5),
                errorNumbersToAdd: null);
        });
    });
}

builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<ICurrentUserService, HttpContextCurrentUserService>();

// Health checks
builder.Services.AddHealthChecks();

// ---------- Pipeline ----------

var app = builder.Build();

if (swaggerEnabled)
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "Northwind Traders API v1");
        c.RoutePrefix = "swagger";
    });
}

app.UseHttpsRedirection();
app.MapControllers();
app.MapHealthChecks("/health");

// ---------- DB Init & Seed ----------

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    var hostEnv = scope.ServiceProvider.GetRequiredService<IWebHostEnvironment>();
    var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();

    try
    {
        if (hostEnv.IsDevelopment())
        {
            logger.LogInformation("Development environment: running EnsureCreated and seeding.");
            await DbInitializer.SeedAsync(db, hostEnv, logger);
        }
        else
        {
            logger.LogInformation("Non-development environment: running EF migrations.");
            await db.Database.MigrateAsync();
        }
    }
    catch (Exception ex)
    {
        logger.LogCritical(ex, "Database initialization failed.");
        throw;
    }
}

app.Run();

// Make Program accessible to test projects
public partial class Program { }
