// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Data;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

// Controllers
builder.Services.AddControllers();

// EF Core - select database provider from configuration
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? throw new InvalidOperationException("Connection string 'DefaultConnection' not found.");
var dbProvider = builder.Configuration["DatabaseProvider"] ?? "SqlServer";

if (dbProvider.Equals("Sqlite", StringComparison.OrdinalIgnoreCase))
{
    builder.Services.AddDbContext<AppDbContext>(options => options.UseSqlite(connectionString));
}
else
{
    builder.Services.AddDbContext<AppDbContext>(options => options.UseSqlServer(connectionString));
}

// Swagger - enabled in all environments except prod
var isProd = builder.Environment.IsEnvironment("prod");
if (!isProd)
{
    builder.Services.AddEndpointsApiExplorer();
    builder.Services.AddSwaggerGen(c =>
    {
        c.SwaggerDoc("v1", new() { Title = "Northwind Traders API", Version = "v1" });
    });
}

// Health checks
builder.Services.AddHealthChecks();

var app = builder.Build();

// Initialize database and seed data on startup (with retry for cloud cold-start)
var maxRetries = 5;
for (int attempt = 1; attempt <= maxRetries; attempt++)
{
    try
    {
        using var scope = app.Services.CreateScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        if (dbProvider.Equals("Sqlite", StringComparison.OrdinalIgnoreCase))
        {
            dbContext.Database.EnsureCreated();
        }
        else
        {
            dbContext.Database.Migrate();
        }

        if (app.Environment.IsEnvironment("local") || app.Environment.IsEnvironment("dev"))
        {
            await DataSeeder.SeedAsync(dbContext);
        }
        break;
    }
    catch (Exception ex) when (attempt < maxRetries)
    {
        app.Logger.LogWarning(ex, "Database initialization attempt {Attempt}/{MaxRetries} failed. Retrying in {Delay}s...", attempt, maxRetries, attempt * 5);
        await Task.Delay(TimeSpan.FromSeconds(attempt * 5));
    }
}

// Swagger middleware (non-prod only)
if (!isProd)
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "Northwind Traders API v1");
        c.RoutePrefix = "swagger";
    });
}

// HTTPS redirect - skip when disabled via config (Azure terminates SSL at load balancer)
if (!string.Equals(builder.Configuration["DisableHttpsRedirect"], "true", StringComparison.OrdinalIgnoreCase))
{
    app.UseHttpsRedirection();
}
app.MapControllers();
app.MapHealthChecks("/health");

app.Run();

// Required for WebApplicationFactory<Program> in test project
public partial class Program { }
