# Generated by booster-webdev | 2026-04-06
# Run this script to install Playwright browsers
param([string]$Command = "install", [string]$Browser = "chromium")

$binPath = Join-Path $PSScriptRoot "bin\Debug\net10.0\playwright.ps1"
if (-not (Test-Path $binPath)) {
    Write-Host "Building project first..."
    dotnet build $PSScriptRoot --configuration Debug | Out-Null
}
& pwsh $binPath $Command $Browser
