// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.Models;

public abstract class AuditableEntity
{
    public string? AddedBy { get; set; }
    public DateTime? AddedOn { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }
}
