// > Generated by booster-apidev | 2026-04-07 11:36:00
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiApp.Models;

public class Customer
{
    public int CustomerId { get; set; }

    [MaxLength(50)]
    public string? CustomerName { get; set; }

    [MaxLength(30)]
    public string? PrimaryContactLastName { get; set; }

    [MaxLength(20)]
    public string? PrimaryContactFirstName { get; set; }

    [MaxLength(50)]
    public string? PrimaryContactJobTitle { get; set; }

    [MaxLength(255)]
    public string? PrimaryContactEmailAddress { get; set; }

    [MaxLength(20)]
    public string? BusinessPhone { get; set; }

    [MaxLength(255)]
    public string? Address { get; set; }

    [MaxLength(255)]
    public string? City { get; set; }

    [MaxLength(2)]
    public string? State { get; set; }

    [MaxLength(10)]
    public string? Zip { get; set; }

    public string? Website { get; set; }
    public string? Notes { get; set; }

    [MaxLength(255)]
    public string? AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    [MaxLength(255)]
    public string? ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    [NotMapped]
    public string? PrimaryContactFullName =>
        string.IsNullOrWhiteSpace(PrimaryContactFirstName) && string.IsNullOrWhiteSpace(PrimaryContactLastName)
            ? null
            : $"{PrimaryContactFirstName} {PrimaryContactLastName}".Trim();

    public List<Order> Orders { get; set; } = [];
}
