// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.Models;

public class Customer : AuditableEntity
{
    public int Id { get; set; }
    public string? CustomerName { get; set; }
    public string? PrimaryContactLastName { get; set; }
    public string? PrimaryContactFirstName { get; set; }
    public string? PrimaryContactJobTitle { get; set; }
    public string? PrimaryContactEmailAddress { get; set; }
    public string? BusinessPhone { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? Zip { get; set; }
    public string? Website { get; set; }
    public string? Notes { get; set; }

    // Computed - not persisted
    public string PrimaryContactFullName =>
        $"{PrimaryContactFirstName} {PrimaryContactLastName}".Trim();

    // Navigation
    public ICollection<Order> Orders { get; set; } = new List<Order>();
}
