// > Generated by booster-apidev | 2026-04-07 11:36:00
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiApp.Models;

public class Employee
{
    public int EmployeeId { get; set; }

    [MaxLength(20)]
    public string? FirstName { get; set; }

    [MaxLength(30)]
    public string? LastName { get; set; }

    [MaxLength(255)]
    public string? EmailAddress { get; set; }

    [MaxLength(50)]
    public string? JobTitle { get; set; }

    [MaxLength(20)]
    public string? PrimaryPhone { get; set; }

    [MaxLength(20)]
    public string? SecondaryPhone { get; set; }

    [MaxLength(20)]
    public string? Title { get; set; }

    public string? Notes { get; set; }

    [MaxLength(50)]
    public string? WindowsUserName { get; set; }

    [MaxLength(255)]
    public string? AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    [MaxLength(255)]
    public string? ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    [NotMapped]
    public string? FullNameFNLN =>
        string.IsNullOrWhiteSpace(FirstName) && string.IsNullOrWhiteSpace(LastName)
            ? null
            : $"{FirstName} {LastName}".Trim();

    [NotMapped]
    public string? FullNameLNFN =>
        string.IsNullOrWhiteSpace(LastName) && string.IsNullOrWhiteSpace(FirstName)
            ? null
            : $"{LastName}, {FirstName}".Trim();

    public List<Order> Orders { get; set; } = [];
}
