// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.Models;

public class Employee : AuditableEntity
{
    public int Id { get; set; }
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? EmailAddress { get; set; }
    public string? JobTitle { get; set; }
    public string? PrimaryPhone { get; set; }
    public string? SecondaryPhone { get; set; }
    public string? Title { get; set; }
    public string? Notes { get; set; }
    public string? WindowsUserName { get; set; }

    // Computed - not persisted
    public string FullNameFNLN =>
        $"{FirstName} {LastName}".Trim();

    public string FullNameLNFN =>
        (!string.IsNullOrWhiteSpace(LastName) && !string.IsNullOrWhiteSpace(FirstName))
            ? $"{LastName}, {FirstName}"
            : (LastName ?? FirstName ?? string.Empty);

    // Navigation
    public ICollection<Order> Orders { get; set; } = new List<Order>();
}
