// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.Models;

/// <summary>
/// Order lifecycle status. Stored as int in the database.
/// Sort order reflects legacy display ordering.
/// </summary>
public enum OrderStatus
{
    New = 10,
    Invoiced = 20,
    Shipped = 30,
    Paid = 35,
    Closed = 40
}
