// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.Models;

public class OrderDetail : AuditableEntity
{
    public int Id { get; set; }
    public int OrderId { get; set; }
    public int ProductId { get; set; }
    public short Quantity { get; set; }
    public decimal UnitPrice { get; set; }

    // Navigation
    public Order? Order { get; set; }
    public Product? Product { get; set; }

    // Computed - not persisted
    public decimal ExtendedPrice => Quantity * UnitPrice;
}
