// > Generated by booster-apidev | 2026-04-07 11:36:00
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiApp.Models;

public class Order
{
    public int OrderId { get; set; }

    public int? EmployeeId { get; set; }

    public int? CustomerId { get; set; }

    public int? StatusId { get; set; }

    public DateTime? OrderDate { get; set; }

    public DateTime? ShippedDate { get; set; }

    public DateTime? PaidDate { get; set; }

    public string? Notes { get; set; }

    [MaxLength(255)]
    public string? AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    [MaxLength(255)]
    public string? ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    [NotMapped]
    public decimal OrderTotal => OrderDetails.Sum(od => (od.Quantity ?? 0) * (od.UnitPrice ?? 0));

    public Customer? Customer { get; set; }
    public Employee? Employee { get; set; }
    public OrderStatus? Status { get; set; }
    public List<OrderDetail> OrderDetails { get; set; } = [];
}
