// > Generated by booster-apidev | 2026-04-07 11:36:00
using System.ComponentModel.DataAnnotations;

namespace ApiApp.Models;

public class OrderStatus
{
    public int StatusId { get; set; }

    [MaxLength(5)]
    public string? StatusCode { get; set; }

    [MaxLength(50)]
    public string? StatusName { get; set; }

    public byte? SortOrder { get; set; }

    public List<Order> Orders { get; set; } = [];
}
