// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.Models;

public class Order : AuditableEntity
{
    public int Id { get; set; }
    public int? CustomerId { get; set; }
    public int? EmployeeId { get; set; }
    public DateTime? OrderDate { get; set; }
    public DateTime? ShippedDate { get; set; }
    public DateTime? PaidDate { get; set; }
    public OrderStatus Status { get; set; } = OrderStatus.New;
    public string? Notes { get; set; }

    // Navigation
    public Customer? Customer { get; set; }
    public Employee? Employee { get; set; }
    public ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    // Computed - not persisted (requires OrderDetails to be loaded)
    public decimal OrderTotal => OrderDetails.Sum(d => d.Quantity * d.UnitPrice);
}
