// > Generated by booster-apidev | 2026-04-07 11:36:00
using System.ComponentModel.DataAnnotations;

namespace ApiApp.Models;

public class Product
{
    public int ProductId { get; set; }

    [MaxLength(20)]
    public string? ProductCode { get; set; }

    [MaxLength(50)]
    public string? ProductName { get; set; }

    public string? ProductDescription { get; set; }

    [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal(18,2)")]
    public decimal? UnitPrice { get; set; }

    [MaxLength(255)]
    public string? AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    [MaxLength(255)]
    public string? ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public List<OrderDetail> OrderDetails { get; set; } = [];
}
