// > Generated by booster-apidev | 2026-04-07 11:36:00
using System.ComponentModel.DataAnnotations;

namespace ApiApp.Models;

public class SystemSetting
{
    public int SettingId { get; set; }

    [MaxLength(50)]
    public string? SettingName { get; set; }

    [MaxLength(255)]
    public string? SettingValue { get; set; }

    [MaxLength(255)]
    public string? Notes { get; set; }
}
