// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.Models;

public class SystemSetting
{
    public int Id { get; set; }
    public string SettingName { get; set; } = string.Empty;
    public string SettingValue { get; set; } = string.Empty;
    public string? Notes { get; set; }
}
