// > Generated by booster-apidev | 2026-04-07 11:36:00

namespace ApiApp.DTOs;

public class GenerateOrdersRequest
{
    public int Count { get; set; } = 5;
}

public class GenerateOrdersResponse
{
    public int OrdersCreated { get; set; }
}
