// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Models;
using System.ComponentModel.DataAnnotations;

namespace ApiApp.DTOs;

public class CustomerDto
{
    public int CustomerId { get; set; }
    public string? CustomerName { get; set; }
    public string? PrimaryContactFirstName { get; set; }
    public string? PrimaryContactLastName { get; set; }
    public string? PrimaryContactJobTitle { get; set; }
    public string? PrimaryContactEmailAddress { get; set; }
    public string? PrimaryContactFullName { get; set; }
    public string? BusinessPhone { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? Zip { get; set; }
    public string? Website { get; set; }
    public string? Notes { get; set; }
    public string? AddedBy { get; set; }
    public DateTime? AddedOn { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }

    public static CustomerDto FromEntity(Customer c) => new()
    {
        CustomerId = c.CustomerId,
        CustomerName = c.CustomerName,
        PrimaryContactFirstName = c.PrimaryContactFirstName,
        PrimaryContactLastName = c.PrimaryContactLastName,
        PrimaryContactJobTitle = c.PrimaryContactJobTitle,
        PrimaryContactEmailAddress = c.PrimaryContactEmailAddress,
        PrimaryContactFullName = c.PrimaryContactFullName,
        BusinessPhone = c.BusinessPhone,
        Address = c.Address,
        City = c.City,
        State = c.State,
        Zip = c.Zip,
        Website = c.Website,
        Notes = c.Notes,
        AddedBy = c.AddedBy,
        AddedOn = c.AddedOn,
        ModifiedBy = c.ModifiedBy,
        ModifiedOn = c.ModifiedOn
    };
}

public class CustomerRequest
{
    [MaxLength(50)]
    public string? CustomerName { get; set; }
    [MaxLength(20)]
    public string? PrimaryContactFirstName { get; set; }
    [MaxLength(30)]
    public string? PrimaryContactLastName { get; set; }
    [MaxLength(50)]
    public string? PrimaryContactJobTitle { get; set; }
    [MaxLength(255)]
    public string? PrimaryContactEmailAddress { get; set; }
    [MaxLength(20)]
    public string? BusinessPhone { get; set; }
    [MaxLength(255)]
    public string? Address { get; set; }
    [MaxLength(255)]
    public string? City { get; set; }
    [MaxLength(2)]
    public string? State { get; set; }
    [MaxLength(10)]
    public string? Zip { get; set; }
    public string? Website { get; set; }
    public string? Notes { get; set; }

    public Customer ToEntity() => ApplyTo(new Customer());

    public Customer ApplyTo(Customer c)
    {
        c.CustomerName = CustomerName;
        c.PrimaryContactFirstName = PrimaryContactFirstName;
        c.PrimaryContactLastName = PrimaryContactLastName;
        c.PrimaryContactJobTitle = PrimaryContactJobTitle;
        c.PrimaryContactEmailAddress = PrimaryContactEmailAddress;
        c.BusinessPhone = BusinessPhone;
        c.Address = Address;
        c.City = City;
        c.State = State;
        c.Zip = Zip;
        c.Website = Website;
        c.Notes = Notes;
        return c;
    }
}

public class CustomerProductDto
{
    public int ProductId { get; set; }
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public int TotalQuantity { get; set; }
    public int OrderCount { get; set; }
    public DateTime? FirstOrderDate { get; set; }
    public DateTime? LastOrderDate { get; set; }
}

public class CustomerLookupDto
{
    public int CustomerId { get; set; }
    public string? CustomerName { get; set; }
}
