// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Models;
using System.ComponentModel.DataAnnotations;

namespace ApiApp.DTOs;

public class EmployeeDto
{
    public int EmployeeId { get; set; }
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? FullNameFNLN { get; set; }
    public string? FullNameLNFN { get; set; }
    public string? EmailAddress { get; set; }
    public string? JobTitle { get; set; }
    public string? PrimaryPhone { get; set; }
    public string? SecondaryPhone { get; set; }
    public string? Title { get; set; }
    public string? Notes { get; set; }
    public string? WindowsUserName { get; set; }
    public string? AddedBy { get; set; }
    public DateTime? AddedOn { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }

    public static EmployeeDto FromEntity(Employee e) => new()
    {
        EmployeeId = e.EmployeeId,
        FirstName = e.FirstName,
        LastName = e.LastName,
        FullNameFNLN = e.FullNameFNLN,
        FullNameLNFN = e.FullNameLNFN,
        EmailAddress = e.EmailAddress,
        JobTitle = e.JobTitle,
        PrimaryPhone = e.PrimaryPhone,
        SecondaryPhone = e.SecondaryPhone,
        Title = e.Title,
        Notes = e.Notes,
        WindowsUserName = e.WindowsUserName,
        AddedBy = e.AddedBy,
        AddedOn = e.AddedOn,
        ModifiedBy = e.ModifiedBy,
        ModifiedOn = e.ModifiedOn
    };
}

public class EmployeeRequest
{
    [MaxLength(20)]
    public string? FirstName { get; set; }
    [MaxLength(30)]
    public string? LastName { get; set; }
    [MaxLength(255)]
    public string? EmailAddress { get; set; }
    [MaxLength(50)]
    public string? JobTitle { get; set; }
    [MaxLength(20)]
    public string? PrimaryPhone { get; set; }
    [MaxLength(20)]
    public string? SecondaryPhone { get; set; }
    [MaxLength(20)]
    public string? Title { get; set; }
    public string? Notes { get; set; }
    [MaxLength(50)]
    public string? WindowsUserName { get; set; }

    public Employee ToEntity() => ApplyTo(new Employee());

    public Employee ApplyTo(Employee e)
    {
        e.FirstName = FirstName;
        e.LastName = LastName;
        e.EmailAddress = EmailAddress;
        e.JobTitle = JobTitle;
        e.PrimaryPhone = PrimaryPhone;
        e.SecondaryPhone = SecondaryPhone;
        e.Title = Title;
        e.Notes = Notes;
        e.WindowsUserName = WindowsUserName;
        return e;
    }
}

public class EmployeeLookupDto
{
    public int EmployeeId { get; set; }
    public string? FullNameFNLN { get; set; }
}
