// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Models;

namespace ApiApp.DTOs;

public class OrderLineDto
{
    public int OrderDetailId { get; set; }
    public int? ProductId { get; set; }
    public string? ProductName { get; set; }
    public string? ProductCode { get; set; }
    public short? Quantity { get; set; }
    public decimal? UnitPrice { get; set; }
    public decimal ExtendedPrice { get; set; }

    public static OrderLineDto FromEntity(OrderDetail od) => new()
    {
        OrderDetailId = od.OrderDetailId,
        ProductId = od.ProductId,
        ProductName = od.Product?.ProductName,
        ProductCode = od.Product?.ProductCode,
        Quantity = od.Quantity,
        UnitPrice = od.UnitPrice,
        ExtendedPrice = (od.Quantity ?? 0) * (od.UnitPrice ?? 0)
    };
}

public class OrderLineRequest
{
    public int? ProductId { get; set; }
    public short? Quantity { get; set; }
    public decimal? UnitPrice { get; set; }
}
