// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Models;

namespace ApiApp.DTOs;

public class OrderSummaryDto
{
    public int OrderId { get; set; }
    public int? CustomerId { get; set; }
    public string? CustomerName { get; set; }
    public int? EmployeeId { get; set; }
    public string? EmployeeFullName { get; set; }
    public int? StatusId { get; set; }
    public string? StatusName { get; set; }
    public DateTime? OrderDate { get; set; }
    public DateTime? ShippedDate { get; set; }
    public DateTime? PaidDate { get; set; }
    public string? Notes { get; set; }
    public decimal OrderTotal { get; set; }
    public string? AddedBy { get; set; }
    public DateTime? AddedOn { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }

    public static OrderSummaryDto FromEntity(Order o) => new()
    {
        OrderId = o.OrderId,
        CustomerId = o.CustomerId,
        CustomerName = o.Customer?.CustomerName,
        EmployeeId = o.EmployeeId,
        EmployeeFullName = o.Employee != null
            ? $"{o.Employee.FirstName} {o.Employee.LastName}".Trim()
            : null,
        StatusId = o.StatusId,
        StatusName = o.Status?.StatusName,
        OrderDate = o.OrderDate,
        ShippedDate = o.ShippedDate,
        PaidDate = o.PaidDate,
        Notes = o.Notes,
        OrderTotal = o.OrderDetails.Sum(od => (od.Quantity ?? 0) * (od.UnitPrice ?? 0)),
        AddedBy = o.AddedBy,
        AddedOn = o.AddedOn,
        ModifiedBy = o.ModifiedBy,
        ModifiedOn = o.ModifiedOn
    };
}

public class OrderFullDto : OrderSummaryDto
{
    public List<OrderLineDto> OrderDetails { get; set; } = [];

    public new static OrderFullDto FromEntity(Order o)
    {
        var summary = OrderSummaryDto.FromEntity(o);
        return new OrderFullDto
        {
            OrderId = summary.OrderId,
            CustomerId = summary.CustomerId,
            CustomerName = summary.CustomerName,
            EmployeeId = summary.EmployeeId,
            EmployeeFullName = summary.EmployeeFullName,
            StatusId = summary.StatusId,
            StatusName = summary.StatusName,
            OrderDate = summary.OrderDate,
            ShippedDate = summary.ShippedDate,
            PaidDate = summary.PaidDate,
            Notes = summary.Notes,
            OrderTotal = summary.OrderTotal,
            AddedBy = summary.AddedBy,
            AddedOn = summary.AddedOn,
            ModifiedBy = summary.ModifiedBy,
            ModifiedOn = summary.ModifiedOn,
            OrderDetails = o.OrderDetails.Select(OrderLineDto.FromEntity).ToList()
        };
    }
}

public class OrderRequest
{
    public int? CustomerId { get; set; }
    public int? EmployeeId { get; set; }
    public int? StatusId { get; set; }
    public DateTime? OrderDate { get; set; }
    public DateTime? ShippedDate { get; set; }
    public DateTime? PaidDate { get; set; }
    public string? Notes { get; set; }

    public Order ToEntity() => ApplyTo(new Order());

    public Order ApplyTo(Order o)
    {
        o.CustomerId = CustomerId;
        o.EmployeeId = EmployeeId;
        o.StatusId = StatusId;
        o.OrderDate = OrderDate;
        o.ShippedDate = ShippedDate;
        o.PaidDate = PaidDate;
        o.Notes = Notes;
        return o;
    }
}
