// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Models;

namespace ApiApp.DTOs;

public class OrderStatusDto
{
    public int StatusId { get; set; }
    public string? StatusCode { get; set; }
    public string? StatusName { get; set; }
    public byte? SortOrder { get; set; }

    public static OrderStatusDto FromEntity(OrderStatus s) => new()
    {
        StatusId = s.StatusId,
        StatusCode = s.StatusCode,
        StatusName = s.StatusName,
        SortOrder = s.SortOrder
    };
}
