// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiApp.DTOs;

public class ProductDto
{
    public int ProductId { get; set; }
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public string? ProductDescription { get; set; }
    public decimal? UnitPrice { get; set; }
    public int TotalOrderCount { get; set; }
    public int SoldThisWeek { get; set; }
    public string? AddedBy { get; set; }
    public DateTime? AddedOn { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }

    public static ProductDto FromEntity(Product p, int totalOrderCount = 0, int soldThisWeek = 0) => new()
    {
        ProductId = p.ProductId,
        ProductCode = p.ProductCode,
        ProductName = p.ProductName,
        ProductDescription = p.ProductDescription,
        UnitPrice = p.UnitPrice,
        TotalOrderCount = totalOrderCount,
        SoldThisWeek = soldThisWeek,
        AddedBy = p.AddedBy,
        AddedOn = p.AddedOn,
        ModifiedBy = p.ModifiedBy,
        ModifiedOn = p.ModifiedOn
    };
}

public class ProductRequest
{
    [MaxLength(20)]
    public string? ProductCode { get; set; }
    [MaxLength(50)]
    public string? ProductName { get; set; }
    public string? ProductDescription { get; set; }
    [Column(TypeName = "decimal(18,2)")]
    public decimal? UnitPrice { get; set; }

    public Product ToEntity() => ApplyTo(new Product());

    public Product ApplyTo(Product p)
    {
        p.ProductCode = ProductCode;
        p.ProductName = ProductName;
        p.ProductDescription = ProductDescription;
        p.UnitPrice = UnitPrice;
        return p;
    }
}

public class ProductLookupDto
{
    public int ProductId { get; set; }
    public string? ProductName { get; set; }
    public string? ProductCode { get; set; }
    public decimal? UnitPrice { get; set; }
}

public class ProductOrderDto
{
    public int OrderId { get; set; }
    public DateTime? OrderDate { get; set; }
    public string? CustomerName { get; set; }
    public short? Quantity { get; set; }
    public decimal? UnitPrice { get; set; }
    public decimal ExtendedPrice { get; set; }
}
