// > Generated by booster-apidev | 2026-04-07 11:36:00

namespace ApiApp.DTOs;

public class SalesYtdDto
{
    public int Year { get; set; }
    public decimal TotalRevenue { get; set; }
}

public class SalesByEmployeeDto
{
    public int EmployeeId { get; set; }
    public string? EmployeeFullName { get; set; }
    public decimal TotalRevenue { get; set; }
}

public class SalesByProductDto
{
    public int ProductId { get; set; }
    public string? ProductName { get; set; }
    public string? MonthYear { get; set; }
    public string? MonthYearSort { get; set; }
    public decimal OrderTotal { get; set; }
}

public class SalesByProductQuarterlyDto
{
    public int ProductId { get; set; }
    public string? ProductName { get; set; }
    public string? QuarterYear { get; set; }
    public decimal OrderTotal { get; set; }
}

public class SalesByEmployeeMonthlyDto
{
    public int EmployeeId { get; set; }
    public string? EmployeeFullName { get; set; }
    public string? MonthYear { get; set; }
    public string? MonthYearSort { get; set; }
    public decimal OrderTotal { get; set; }
}

public class InvoiceLineItemDto
{
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public short Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal ExtendedPrice { get; set; }
}

public class InvoiceDto
{
    public int OrderId { get; set; }
    public DateTime? OrderDate { get; set; }
    public string? CustomerName { get; set; }
    public string? CustomerAddress { get; set; }
    public string? CustomerCity { get; set; }
    public string? CustomerState { get; set; }
    public string? CustomerZip { get; set; }
    public string? EmployeeFullName { get; set; }
    public string? StatusName { get; set; }
    public List<InvoiceLineItemDto> LineItems { get; set; } = [];
    public decimal OrderTotal { get; set; }
}

public class EmployeeEmailDto
{
    public int EmployeeId { get; set; }
    public string? FullNameLNFN { get; set; }
    public string? EmailAddress { get; set; }
}

public class EmployeePhoneDto
{
    public int EmployeeId { get; set; }
    public string? FullNameLNFN { get; set; }
    public string? PrimaryPhone { get; set; }
    public string? SecondaryPhone { get; set; }
}
