// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Models;

namespace ApiApp.DTOs;

public class SystemSettingDto
{
    public int SettingId { get; set; }
    public string? SettingName { get; set; }
    public string? SettingValue { get; set; }
    public string? Notes { get; set; }

    public static SystemSettingDto FromEntity(SystemSetting s) => new()
    {
        SettingId = s.SettingId,
        SettingName = s.SettingName,
        SettingValue = s.SettingValue,
        Notes = s.Notes
    };
}

public class SystemSettingUpdateRequest
{
    public string? SettingValue { get; set; }
}
