// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Models;
using Microsoft.EntityFrameworkCore;

namespace ApiApp.Data;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    public DbSet<Customer> Customers => Set<Customer>();
    public DbSet<Employee> Employees => Set<Employee>();
    public DbSet<Order> Orders => Set<Order>();
    public DbSet<OrderDetail> OrderDetails => Set<OrderDetail>();
    public DbSet<Product> Products => Set<Product>();
    public DbSet<OrderStatus> OrderStatuses => Set<OrderStatus>();
    public DbSet<SystemSetting> SystemSettings => Set<SystemSetting>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Customer
        modelBuilder.Entity<Customer>(e =>
        {
            e.HasKey(c => c.CustomerId);
            e.HasMany(c => c.Orders).WithOne(o => o.Customer).HasForeignKey(o => o.CustomerId).OnDelete(DeleteBehavior.SetNull);
        });

        // Employee
        modelBuilder.Entity<Employee>(e =>
        {
            e.HasKey(emp => emp.EmployeeId);
            e.HasIndex(emp => emp.WindowsUserName).IsUnique();
            e.HasMany(emp => emp.Orders).WithOne(o => o.Employee).HasForeignKey(o => o.EmployeeId).OnDelete(DeleteBehavior.SetNull);
        });

        // Order
        modelBuilder.Entity<Order>(e =>
        {
            e.HasKey(o => o.OrderId);
            e.HasMany(o => o.OrderDetails).WithOne(od => od.Order).HasForeignKey(od => od.OrderId).OnDelete(DeleteBehavior.Cascade);
            e.HasOne(o => o.Status).WithMany(s => s.Orders).HasForeignKey(o => o.StatusId).OnDelete(DeleteBehavior.SetNull);
        });

        // OrderDetail
        modelBuilder.Entity<OrderDetail>(e =>
        {
            e.HasKey(od => od.OrderDetailId);
            e.HasOne(od => od.Product).WithMany(p => p.OrderDetails).HasForeignKey(od => od.ProductId).OnDelete(DeleteBehavior.SetNull);
        });

        // Product
        modelBuilder.Entity<Product>(e =>
        {
            e.HasKey(p => p.ProductId);
            e.HasIndex(p => p.ProductCode).IsUnique();
        });

        // OrderStatus - static lookup, seeded with fixed IDs
        modelBuilder.Entity<OrderStatus>(e =>
        {
            e.HasKey(s => s.StatusId);
            e.Property(s => s.StatusId).ValueGeneratedNever();
            e.HasData(
                new OrderStatus { StatusId = 3, StatusCode = "NEW", StatusName = "New", SortOrder = 10 },
                new OrderStatus { StatusId = 2, StatusCode = "INV", StatusName = "Invoiced", SortOrder = 20 },
                new OrderStatus { StatusId = 4, StatusCode = "SHI", StatusName = "Shipped", SortOrder = 30 },
                new OrderStatus { StatusId = 5, StatusCode = "PAY", StatusName = "Paid", SortOrder = 35 },
                new OrderStatus { StatusId = 1, StatusCode = "CLO", StatusName = "Closed", SortOrder = 40 }
            );
        });

        // SystemSetting - seeded with TaxRate
        modelBuilder.Entity<SystemSetting>(e =>
        {
            e.HasKey(s => s.SettingId);
            e.HasIndex(s => s.SettingName).IsUnique();
            e.HasData(
                new SystemSetting { SettingId = 1, SettingName = "TaxRate", SettingValue = "85", Notes = "Divide by 1000 to get rate (85 -> 0.085 = 8.5%)" }
            );
        });

        // Employee ID 10 - Internet Sales system employee (required for generate-orders)
        modelBuilder.Entity<Employee>().Property(e => e.EmployeeId).ValueGeneratedOnAdd();
        modelBuilder.Entity<Employee>().HasData(
            new Employee
            {
                EmployeeId = 10,
                FirstName = "Internet",
                LastName = "Sales",
                JobTitle = "Internet Sales",
                WindowsUserName = "internet_sales",
                EmailAddress = "internet_sales@northwind.com"
            }
        );
    }
}
