// Generated by booster-apidev | 2026-04-06 19:37:30

using ApiApp.Models;
using Microsoft.EntityFrameworkCore;

namespace ApiApp.Data;

public class AppDbContext : DbContext
{
    private readonly ICurrentUserService _currentUserService;

    public AppDbContext(DbContextOptions<AppDbContext> options, ICurrentUserService currentUserService)
        : base(options)
    {
        _currentUserService = currentUserService;
    }

    public DbSet<Customer> Customers => Set<Customer>();
    public DbSet<Employee> Employees => Set<Employee>();
    public DbSet<Order> Orders => Set<Order>();
    public DbSet<OrderDetail> OrderDetails => Set<OrderDetail>();
    public DbSet<Product> Products => Set<Product>();
    public DbSet<SystemSetting> SystemSettings => Set<SystemSetting>();

    public override int SaveChanges()
    {
        ApplyAuditFields();
        return base.SaveChanges();
    }

    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        ApplyAuditFields();
        return base.SaveChangesAsync(cancellationToken);
    }

    private void ApplyAuditFields()
    {
        var now = DateTime.UtcNow;
        var user = _currentUserService.CurrentUser;

        foreach (var entry in ChangeTracker.Entries<AuditableEntity>())
        {
            if (entry.State == EntityState.Added)
            {
                entry.Entity.AddedBy = user;
                entry.Entity.AddedOn = now;
                entry.Entity.ModifiedBy = user;
                entry.Entity.ModifiedOn = now;
            }
            else if (entry.State == EntityState.Modified)
            {
                entry.Entity.ModifiedBy = user;
                entry.Entity.ModifiedOn = now;
            }
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<Customer>(e =>
        {
            e.HasKey(x => x.Id);
            e.Property(x => x.CustomerName).HasMaxLength(50);
            e.Property(x => x.PrimaryContactLastName).HasMaxLength(30);
            e.Property(x => x.PrimaryContactFirstName).HasMaxLength(20);
            e.Property(x => x.PrimaryContactJobTitle).HasMaxLength(50);
            e.Property(x => x.PrimaryContactEmailAddress).HasMaxLength(255);
            e.Property(x => x.BusinessPhone).HasMaxLength(20);
            e.Property(x => x.Address).HasMaxLength(255);
            e.Property(x => x.City).HasMaxLength(255);
            e.Property(x => x.State).HasMaxLength(2);
            e.Property(x => x.Zip).HasMaxLength(10);
            e.Ignore(x => x.PrimaryContactFullName);
        });

        modelBuilder.Entity<Employee>(e =>
        {
            e.HasKey(x => x.Id);
            e.Property(x => x.FirstName).HasMaxLength(20);
            e.Property(x => x.LastName).HasMaxLength(30);
            e.Property(x => x.EmailAddress).HasMaxLength(255);
            e.Property(x => x.JobTitle).HasMaxLength(50);
            e.Property(x => x.PrimaryPhone).HasMaxLength(20);
            e.Property(x => x.SecondaryPhone).HasMaxLength(20);
            e.Property(x => x.Title).HasMaxLength(20);
            e.Property(x => x.WindowsUserName).HasMaxLength(50);
            e.HasIndex(x => x.WindowsUserName).IsUnique();
            e.Ignore(x => x.FullNameFNLN);
            e.Ignore(x => x.FullNameLNFN);
        });

        modelBuilder.Entity<Order>(e =>
        {
            e.HasKey(x => x.Id);
            e.Property(x => x.Status).HasConversion<int>();
            e.HasIndex(x => x.CustomerId);
            e.HasIndex(x => x.EmployeeId);
            e.HasOne(x => x.Customer)
                .WithMany(c => c.Orders)
                .HasForeignKey(x => x.CustomerId)
                .OnDelete(DeleteBehavior.SetNull);
            e.HasOne(x => x.Employee)
                .WithMany(emp => emp.Orders)
                .HasForeignKey(x => x.EmployeeId)
                .OnDelete(DeleteBehavior.SetNull);
            e.Ignore(x => x.OrderTotal);
        });

        modelBuilder.Entity<OrderDetail>(e =>
        {
            e.HasKey(x => x.Id);
            e.Property(x => x.UnitPrice).HasColumnType("decimal(18,4)");
            e.HasIndex(x => x.OrderId);
            e.HasIndex(x => x.ProductId);
            e.HasOne(x => x.Order)
                .WithMany(o => o.OrderDetails)
                .HasForeignKey(x => x.OrderId)
                .OnDelete(DeleteBehavior.Cascade);
            e.HasOne(x => x.Product)
                .WithMany(p => p.OrderDetails)
                .HasForeignKey(x => x.ProductId)
                .OnDelete(DeleteBehavior.Restrict);
            e.Ignore(x => x.ExtendedPrice);
        });

        modelBuilder.Entity<Product>(e =>
        {
            e.HasKey(x => x.Id);
            e.Property(x => x.ProductCode).HasMaxLength(20);
            e.Property(x => x.ProductName).HasMaxLength(50);
            e.Property(x => x.UnitPrice).HasColumnType("decimal(18,4)");
            e.HasIndex(x => x.ProductCode).IsUnique();
        });

        modelBuilder.Entity<SystemSetting>(e =>
        {
            e.HasKey(x => x.Id);
            e.Property(x => x.SettingName).HasMaxLength(50).IsRequired();
            e.Property(x => x.SettingValue).HasMaxLength(255).IsRequired();
            e.Property(x => x.Notes).HasMaxLength(255);
        });
    }
}
