// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.Data;

public interface ICurrentUserService
{
    string CurrentUser { get; }
}

public class HttpContextCurrentUserService : ICurrentUserService
{
    private readonly IHttpContextAccessor _httpContextAccessor;
    private readonly IWebHostEnvironment _env;

    public HttpContextCurrentUserService(IHttpContextAccessor httpContextAccessor, IWebHostEnvironment env)
    {
        _httpContextAccessor = httpContextAccessor;
        _env = env;
    }

    public string CurrentUser
    {
        get
        {
            if (_env.IsDevelopment())
            {
                return "dev-user";
            }

            // In cloud environments, identity is from Managed Identity / JWT claim
            var user = _httpContextAccessor.HttpContext?.User;
            return user?.Identity?.Name ?? "system";
        }
    }
}
