// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Models;
using Microsoft.EntityFrameworkCore;

namespace ApiApp.Data;

public static class DataSeeder
{
    public static async Task SeedAsync(AppDbContext db)
    {
        await SeedEmployeesAsync(db);
        await SeedCustomersAsync(db);
        await SeedProductsAsync(db);
        await SeedOrdersAsync(db);
    }

    private static async Task SeedEmployeesAsync(AppDbContext db)
    {
        if (await db.Employees.AnyAsync(e => e.EmployeeId != 10)) return;

        db.Employees.AddRange(
            new Employee { FirstName = "Nancy", LastName = "Freehafer", EmailAddress = "nancy@northwind.com", JobTitle = "Sales Representative", PrimaryPhone = "555-1001", Title = "Ms.", WindowsUserName = "nfreehafer" },
            new Employee { FirstName = "Andrew", LastName = "Cencini", EmailAddress = "andrew@northwind.com", JobTitle = "Sales Representative", PrimaryPhone = "555-1002", Title = "Mr.", WindowsUserName = "acencini" },
            new Employee { FirstName = "Jan", LastName = "Kotas", EmailAddress = "jan@northwind.com", JobTitle = "Sales Representative", PrimaryPhone = "555-1003", Title = "Mr.", WindowsUserName = "jkotas" },
            new Employee { FirstName = "Mariya", LastName = "Sergienko", EmailAddress = "mariya@northwind.com", JobTitle = "Sales Representative", PrimaryPhone = "555-1004", Title = "Ms.", WindowsUserName = "msergienko" },
            new Employee { FirstName = "Steven", LastName = "Thorpe", EmailAddress = "steven@northwind.com", JobTitle = "Sales Manager", PrimaryPhone = "555-1005", Title = "Mr.", WindowsUserName = "sthorpe" },
            new Employee { FirstName = "Michael", LastName = "Neipper", EmailAddress = "michael@northwind.com", JobTitle = "Sales Representative", PrimaryPhone = "555-1006", Title = "Mr.", WindowsUserName = "mneipper" },
            new Employee { FirstName = "Robert", LastName = "Zare", EmailAddress = "robert@northwind.com", JobTitle = "Sales Representative", PrimaryPhone = "555-1007", Title = "Mr.", WindowsUserName = "rzare" },
            new Employee { FirstName = "Laura", LastName = "Giussani", EmailAddress = "laura@northwind.com", JobTitle = "Sales Representative", PrimaryPhone = "555-1008", Title = "Ms.", WindowsUserName = "lgiussani" },
            new Employee { FirstName = "Anne", LastName = "Hellung-Larsen", EmailAddress = "anne@northwind.com", JobTitle = "Sales Representative", PrimaryPhone = "555-1009", Title = "Ms.", WindowsUserName = "ahellung" }
        );
        await db.SaveChangesAsync();
    }

    private static async Task SeedCustomersAsync(AppDbContext db)
    {
        if (await db.Customers.AnyAsync()) return;

        db.Customers.AddRange(
            new Customer { CustomerName = "Contoso Ltd", PrimaryContactFirstName = "Jane", PrimaryContactLastName = "Doe", PrimaryContactJobTitle = "Buyer", PrimaryContactEmailAddress = "jane@contoso.com", BusinessPhone = "555-2001", Address = "123 Main St", City = "Seattle", State = "WA", Zip = "98101", Website = "https://contoso.com", AddedBy = "System", AddedOn = DateTime.UtcNow },
            new Customer { CustomerName = "Fabrikam Inc", PrimaryContactFirstName = "John", PrimaryContactLastName = "Smith", PrimaryContactJobTitle = "Purchasing Manager", PrimaryContactEmailAddress = "john@fabrikam.com", BusinessPhone = "555-2002", Address = "456 Oak Ave", City = "Portland", State = "OR", Zip = "97201", AddedBy = "System", AddedOn = DateTime.UtcNow },
            new Customer { CustomerName = "Northwind Retail", PrimaryContactFirstName = "Alice", PrimaryContactLastName = "Johnson", PrimaryContactJobTitle = "Buyer", PrimaryContactEmailAddress = "alice@nwretail.com", BusinessPhone = "555-2003", Address = "789 Pine Rd", City = "Bellevue", State = "WA", Zip = "98004", AddedBy = "System", AddedOn = DateTime.UtcNow },
            new Customer { CustomerName = "Adventure Works", PrimaryContactFirstName = "Bob", PrimaryContactLastName = "Williams", PrimaryContactJobTitle = "Procurement Lead", PrimaryContactEmailAddress = "bob@adventure.com", BusinessPhone = "555-2004", Address = "321 Elm St", City = "Redmond", State = "WA", Zip = "98052", AddedBy = "System", AddedOn = DateTime.UtcNow },
            new Customer { CustomerName = "Wide World Importers", PrimaryContactFirstName = "Carol", PrimaryContactLastName = "Martinez", PrimaryContactJobTitle = "VP Procurement", PrimaryContactEmailAddress = "carol@wwi.com", BusinessPhone = "555-2005", Address = "654 Birch Blvd", City = "Kirkland", State = "WA", Zip = "98033", AddedBy = "System", AddedOn = DateTime.UtcNow },
            new Customer { CustomerName = "Coho Winery", PrimaryContactFirstName = "David", PrimaryContactLastName = "Brown", PrimaryContactJobTitle = "Buyer", PrimaryContactEmailAddress = "david@coho.com", BusinessPhone = "555-2006", Address = "987 Vine Ln", City = "Woodinville", State = "WA", Zip = "98072", AddedBy = "System", AddedOn = DateTime.UtcNow }
        );
        await db.SaveChangesAsync();
    }

    private static async Task SeedProductsAsync(AppDbContext db)
    {
        if (await db.Products.AnyAsync()) return;

        db.Products.AddRange(
            new Product { ProductCode = "NWT01", ProductName = "Northwind Chai", ProductDescription = "A fine chai blend from the Pacific Northwest.", UnitPrice = 18.00m, AddedBy = "System", AddedOn = DateTime.UtcNow },
            new Product { ProductCode = "NWT02", ProductName = "Northwind Syrup", ProductDescription = "Pure maple syrup, Grade A amber.", UnitPrice = 10.00m, AddedBy = "System", AddedOn = DateTime.UtcNow },
            new Product { ProductCode = "NWT03", ProductName = "Northwind Cajun Seasoning", ProductDescription = "Premium Cajun spice blend.", UnitPrice = 22.00m, AddedBy = "System", AddedOn = DateTime.UtcNow },
            new Product { ProductCode = "NWT04", ProductName = "Northwind Olive Oil", ProductDescription = "Extra-virgin cold-pressed olive oil.", UnitPrice = 21.35m, AddedBy = "System", AddedOn = DateTime.UtcNow },
            new Product { ProductCode = "NWT05", ProductName = "Northwind Boysenberry Spread", ProductDescription = "Wild-harvest boysenberry preserves.", UnitPrice = 25.00m, AddedBy = "System", AddedOn = DateTime.UtcNow },
            new Product { ProductCode = "NWT06", ProductName = "Northwind Dried Pears", ProductDescription = "Sun-dried Pacific Anjou pears.", UnitPrice = 30.00m, AddedBy = "System", AddedOn = DateTime.UtcNow },
            new Product { ProductCode = "NWT07", ProductName = "Northwind Curry Sauce", ProductDescription = "Rich traditional curry sauce blend.", UnitPrice = 40.00m, AddedBy = "System", AddedOn = DateTime.UtcNow },
            new Product { ProductCode = "NWT08", ProductName = "Northwind Walnuts", ProductDescription = "Premium Oregon black walnuts.", UnitPrice = 23.25m, AddedBy = "System", AddedOn = DateTime.UtcNow },
            new Product { ProductCode = "NWT09", ProductName = "Northwind Fruit Cocktail", ProductDescription = "Seasonal mixed fruit cocktail.", UnitPrice = 39.00m, AddedBy = "System", AddedOn = DateTime.UtcNow },
            new Product { ProductCode = "NWT10", ProductName = "Northwind Clam Chowder", ProductDescription = "New England style clam chowder concentrate.", UnitPrice = 9.65m, AddedBy = "System", AddedOn = DateTime.UtcNow }
        );
        await db.SaveChangesAsync();
    }

    private static async Task SeedOrdersAsync(AppDbContext db)
    {
        if (await db.Orders.AnyAsync()) return;

        var customers = await db.Customers.Select(c => c.CustomerId).ToListAsync();
        var employees = await db.Employees.Where(e => e.EmployeeId != 10).Select(e => e.EmployeeId).ToListAsync();
        var products = await db.Products.ToListAsync();

        if (!customers.Any() || !employees.Any() || !products.Any()) return;

        var random = new Random(42);
        var baseDate = DateTime.UtcNow.AddDays(-90);

        for (int i = 0; i < 12; i++)
        {
            var orderDate = baseDate.AddDays(random.Next(0, 85));
            var order = new Order
            {
                CustomerId = customers[random.Next(customers.Count)],
                EmployeeId = employees[random.Next(employees.Count)],
                StatusId = new[] { 3, 2, 4, 5, 1 }[random.Next(5)],
                OrderDate = orderDate,
                ShippedDate = random.Next(2) == 0 ? orderDate.AddDays(random.Next(3, 10)) : null,
                AddedBy = "System",
                AddedOn = orderDate
            };
            db.Orders.Add(order);
            await db.SaveChangesAsync();

            int lineCount = random.Next(1, 4);
            var pickedProducts = products.OrderBy(_ => random.Next()).Take(lineCount).ToList();
            foreach (var product in pickedProducts)
            {
                db.OrderDetails.Add(new OrderDetail
                {
                    OrderId = order.OrderId,
                    ProductId = product.ProductId,
                    Quantity = (short)random.Next(1, 8),
                    UnitPrice = product.UnitPrice,
                    AddedBy = "System",
                    AddedOn = orderDate
                });
            }
            await db.SaveChangesAsync();
        }
    }
}
