// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace ApiApp;

/// <summary>
/// Design-time factory for EF Core migrations. Uses SQL Server (production database provider).
/// </summary>
public class DesignTimeDbContextFactory : IDesignTimeDbContextFactory<AppDbContext>
{
    public AppDbContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<AppDbContext>();
        // Use SQL Server for migration generation (production database)
        optionsBuilder.UseSqlServer(
            "Server=design-time;Database=design-time;Trusted_Connection=True;TrustServerCertificate=True;");
        return new AppDbContext(optionsBuilder.Options);
    }
}
