// Generated by booster-apidev | 2026-04-06 19:37:30

using System.ComponentModel.DataAnnotations;

namespace ApiApp.DTOs.OrderDetails;

public class OrderDetailCreateUpdateDto
{
    [Required]
    public int ProductId { get; set; }

    [Required]
    [Range(1, short.MaxValue)]
    public short Quantity { get; set; }

    public decimal? UnitPrice { get; set; }
}
