// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.DTOs.OrderDetails;

public class OrderDetailItemDto
{
    public int Id { get; set; }
    public int OrderId { get; set; }
    public int ProductId { get; set; }
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public int Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal ExtendedPrice { get; set; }
}
