// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.DTOs.Reports;

public class SalesYtdDto
{
    public int Year { get; set; }
    public decimal TotalSales { get; set; }
}

public class SalesByEmployeeDto
{
    public int EmployeeId { get; set; }
    public string? EmployeeFullName { get; set; }
    public string? MonthYear { get; set; }
    public string? MonthYearSort { get; set; }
    public decimal TotalSales { get; set; }
}

public class SalesByProductDto
{
    public int ProductId { get; set; }
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public string? Period { get; set; }
    public string? PeriodSort { get; set; }
    public decimal TotalSales { get; set; }
}

public class InvoiceDto
{
    public int OrderId { get; set; }
    public DateTime? OrderDate { get; set; }
    public InvoiceCustomerDto? Customer { get; set; }
    public InvoiceEmployeeDto? Employee { get; set; }
    public string? Status { get; set; }
    public List<InvoiceLineItemDto> LineItems { get; set; } = new();
    public decimal Subtotal { get; set; }
    public decimal TaxRate { get; set; }
    public decimal TaxAmount { get; set; }
    public decimal Total { get; set; }
}

public class InvoiceCustomerDto
{
    public int Id { get; set; }
    public string? CustomerName { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? Zip { get; set; }
}

public class InvoiceEmployeeDto
{
    public int Id { get; set; }
    public string? FullName { get; set; }
}

public class InvoiceLineItemDto
{
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public int Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal ExtendedPrice { get; set; }
}

public class EmployeeEmailListDto
{
    public int EmployeeId { get; set; }
    public string? FullNameLNFN { get; set; }
    public string? EmailAddress { get; set; }
}

public class EmployeePhoneListDto
{
    public int EmployeeId { get; set; }
    public string? FullNameLNFN { get; set; }
    public string? PrimaryPhone { get; set; }
    public string? SecondaryPhone { get; set; }
}
