// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Data;
using ApiApp.DTOs;
using ApiApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ApiApp.Controllers;

[ApiController]
[Route("api/admin")]
public class AdminController : ControllerBase
{
    private readonly AppDbContext _db;
    public AdminController(AppDbContext db) => _db = db;

    // GET api/admin/settings
    [HttpGet("settings")]
    public async Task<ActionResult<IEnumerable<SystemSettingDto>>> GetSettings()
    {
        var settings = await _db.SystemSettings
            .OrderBy(s => s.SettingName)
            .Select(s => SystemSettingDto.FromEntity(s))
            .ToListAsync();
        return Ok(settings);
    }

    // PUT api/admin/settings/{id}
    [HttpPut("settings/{id:int}")]
    public async Task<ActionResult<SystemSettingDto>> UpdateSetting(int id, [FromBody] SystemSettingUpdateRequest request)
    {
        var setting = await _db.SystemSettings.FindAsync(id);
        if (setting is null) return NotFound();
        setting.SettingValue = request.SettingValue;
        await _db.SaveChangesAsync();
        return Ok(SystemSettingDto.FromEntity(setting));
    }

    // POST api/admin/generate-orders
    [HttpPost("generate-orders")]
    public async Task<ActionResult<GenerateOrdersResponse>> GenerateOrders([FromBody] GenerateOrdersRequest request)
    {
        if (request.Count <= 0 || request.Count > 100)
            return BadRequest("Count must be between 1 and 100.");

        var customers = await _db.Customers.Select(c => c.CustomerId).ToListAsync();
        var products = await _db.Products.ToListAsync();

        if (!customers.Any() || !products.Any())
            return BadRequest("No customers or products available to generate orders.");

        var random = new Random();
        int ordersCreated = 0;

        for (int i = 0; i < request.Count; i++)
        {
            var order = new Order
            {
                CustomerId = customers[random.Next(customers.Count)],
                EmployeeId = 10, // INTERNET_SALES_EMPLOYEEID
                StatusId = 3, // NEW
                OrderDate = DateTime.UtcNow,
                AddedBy = "System",
                AddedOn = DateTime.UtcNow
            };
            _db.Orders.Add(order);
            await _db.SaveChangesAsync();

            int lineCount = random.Next(1, 4);
            var picked = products.OrderBy(_ => random.Next()).Take(lineCount).ToList();
            foreach (var product in picked)
            {
                _db.OrderDetails.Add(new OrderDetail
                {
                    OrderId = order.OrderId,
                    ProductId = product.ProductId,
                    Quantity = (short)random.Next(1, 10),
                    UnitPrice = product.UnitPrice,
                    AddedBy = "System",
                    AddedOn = DateTime.UtcNow
                });
            }
            await _db.SaveChangesAsync();
            ordersCreated++;
        }

        return Ok(new GenerateOrdersResponse { OrdersCreated = ordersCreated });
    }

    // DELETE api/admin/test-data
    [HttpDelete("test-data")]
    public async Task<IActionResult> DeleteTestData()
    {
        // Delete in FK-safe order
        await _db.OrderDetails.ExecuteDeleteAsync();
        await _db.Orders.ExecuteDeleteAsync();
        await _db.Customers.ExecuteDeleteAsync();
        await _db.Products.ExecuteDeleteAsync();
        await _db.Employees.ExecuteDeleteAsync();
        return NoContent();
    }
}
