// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Data;
using ApiApp.DTOs;
using ApiApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ApiApp.Controllers;

[ApiController]
[Route("api/customers")]
public class CustomersController : ControllerBase
{
    private readonly AppDbContext _db;
    public CustomersController(AppDbContext db) => _db = db;

    // GET api/customers[?search=...]
    [HttpGet]
    public async Task<ActionResult<IEnumerable<CustomerDto>>> GetCustomers([FromQuery] string? search)
    {
        var query = _db.Customers.AsQueryable();
        if (!string.IsNullOrWhiteSpace(search))
        {
            query = query.Where(c =>
                (c.CustomerName != null && c.CustomerName.Contains(search)) ||
                (c.City != null && c.City.Contains(search)) ||
                (c.State != null && c.State.Contains(search)));
        }
        var customers = await query
            .OrderBy(c => c.CustomerName)
            .Select(c => CustomerDto.FromEntity(c))
            .ToListAsync();
        return Ok(customers);
    }

    // GET api/customers/lookup
    [HttpGet("lookup")]
    public async Task<ActionResult<IEnumerable<CustomerLookupDto>>> GetLookup()
    {
        var result = await _db.Customers
            .OrderBy(c => c.CustomerName)
            .Select(c => new CustomerLookupDto { CustomerId = c.CustomerId, CustomerName = c.CustomerName })
            .ToListAsync();
        return Ok(result);
    }

    // GET api/customers/{id}
    [HttpGet("{id:int}")]
    public async Task<ActionResult<CustomerDto>> GetCustomer(int id)
    {
        var customer = await _db.Customers.FindAsync(id);
        if (customer is null) return NotFound();
        return Ok(CustomerDto.FromEntity(customer));
    }

    // POST api/customers
    [HttpPost]
    public async Task<ActionResult<CustomerDto>> CreateCustomer([FromBody] CustomerRequest request)
    {
        var customer = request.ToEntity();
        customer.AddedBy = "System";
        customer.AddedOn = DateTime.UtcNow;
        _db.Customers.Add(customer);
        await _db.SaveChangesAsync();
        return CreatedAtAction(nameof(GetCustomer), new { id = customer.CustomerId }, CustomerDto.FromEntity(customer));
    }

    // PUT api/customers/{id}
    [HttpPut("{id:int}")]
    public async Task<ActionResult<CustomerDto>> UpdateCustomer(int id, [FromBody] CustomerRequest request)
    {
        var customer = await _db.Customers.FindAsync(id);
        if (customer is null) return NotFound();
        request.ApplyTo(customer);
        customer.ModifiedBy = "System";
        customer.ModifiedOn = DateTime.UtcNow;
        await _db.SaveChangesAsync();
        return Ok(CustomerDto.FromEntity(customer));
    }

    // DELETE api/customers/{id}
    [HttpDelete("{id:int}")]
    public async Task<IActionResult> DeleteCustomer(int id)
    {
        var customer = await _db.Customers.FindAsync(id);
        if (customer is null) return NotFound();
        _db.Customers.Remove(customer);
        await _db.SaveChangesAsync();
        return NoContent();
    }

    // GET api/customers/{id}/orders
    [HttpGet("{id:int}/orders")]
    public async Task<ActionResult<IEnumerable<OrderSummaryDto>>> GetCustomerOrders(int id)
    {
        var exists = await _db.Customers.AnyAsync(c => c.CustomerId == id);
        if (!exists) return NotFound();

        var orders = await _db.Orders
            .Where(o => o.CustomerId == id)
            .Include(o => o.Customer)
            .Include(o => o.Employee)
            .Include(o => o.Status)
            .Include(o => o.OrderDetails)
            .OrderByDescending(o => o.OrderDate)
            .ToListAsync();

        return Ok(orders.Select(OrderSummaryDto.FromEntity));
    }

    // GET api/customers/{id}/products
    [HttpGet("{id:int}/products")]
    public async Task<ActionResult<IEnumerable<CustomerProductDto>>> GetCustomerProducts(int id)
    {
        var exists = await _db.Customers.AnyAsync(c => c.CustomerId == id);
        if (!exists) return NotFound();

        var raw = await _db.OrderDetails
            .Where(od => od.Order!.CustomerId == id && od.ProductId.HasValue)
            .Select(od => new
            {
                od.ProductId,
                od.Product!.ProductCode,
                od.Product.ProductName,
                od.Quantity,
                od.OrderId,
                OrderDate = od.Order!.OrderDate
            })
            .ToListAsync();

        var result = raw
            .GroupBy(x => new { x.ProductId, x.ProductCode, x.ProductName })
            .Select(g => new CustomerProductDto
            {
                ProductId = g.Key.ProductId!.Value,
                ProductCode = g.Key.ProductCode,
                ProductName = g.Key.ProductName,
                TotalQuantity = g.Sum(x => x.Quantity ?? 0),
                OrderCount = g.Select(x => x.OrderId).Distinct().Count(),
                FirstOrderDate = g.Min(x => x.OrderDate),
                LastOrderDate = g.Max(x => x.OrderDate)
            })
            .ToList();

        return Ok(result);
    }
}
