// Generated by booster-apidev | 2026-04-06 19:37:30

using ApiApp.Data;
using ApiApp.DTOs.Customers;
using ApiApp.DTOs.Orders;
using ApiApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ApiApp.Controllers;

[ApiController]
[Route("api/customers")]
public class CustomersController : ControllerBase
{
    private readonly AppDbContext _db;

    public CustomersController(AppDbContext db)
    {
        _db = db;
    }

    // GET /api/customers
    [HttpGet]
    public async Task<ActionResult<DTOs.PagedResult<CustomerListItemDto>>> GetCustomers(
        [FromQuery] string? search,
        [FromQuery] bool activeOnly = false,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 20)
    {
        pageSize = Math.Min(pageSize, 100);
        page = Math.Max(page, 1);

        var query = _db.Customers.AsQueryable();

        if (!string.IsNullOrWhiteSpace(search))
        {
            var s = search.ToLower();
            query = query.Where(c =>
                (c.CustomerName != null && c.CustomerName.ToLower().Contains(s)) ||
                (c.City != null && c.City.ToLower().Contains(s)) ||
                (c.PrimaryContactLastName != null && c.PrimaryContactLastName.ToLower().Contains(s)));
        }

        if (activeOnly)
        {
            query = query.Where(c => c.Orders.Any(o => o.Status != OrderStatus.Closed));
        }

        var totalCount = await query.CountAsync();
        var items = await query
            .OrderBy(c => c.CustomerName)
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .Select(c => new CustomerListItemDto
            {
                Id = c.Id,
                CustomerName = c.CustomerName,
                PrimaryContactFirstName = c.PrimaryContactFirstName,
                PrimaryContactLastName = c.PrimaryContactLastName,
                PrimaryContactFullName = (c.PrimaryContactFirstName + " " + c.PrimaryContactLastName).Trim(),
                PrimaryContactJobTitle = c.PrimaryContactJobTitle,
                PrimaryContactEmailAddress = c.PrimaryContactEmailAddress,
                BusinessPhone = c.BusinessPhone,
                Address = c.Address,
                City = c.City,
                State = c.State,
                Zip = c.Zip
            })
            .ToListAsync();

        return Ok(new DTOs.PagedResult<CustomerListItemDto>
        {
            Items = items,
            TotalCount = totalCount,
            Page = page,
            PageSize = pageSize
        });
    }

    // GET /api/customers/{id}
    [HttpGet("{id:int}")]
    public async Task<ActionResult<CustomerDetailDto>> GetCustomer(int id)
    {
        var c = await _db.Customers.FindAsync(id);
        if (c == null) return NotFound(new { error = $"Customer {id} not found." });
        return Ok(MapToDetail(c));
    }

    // POST /api/customers
    [HttpPost]
    public async Task<ActionResult<CustomerDetailDto>> CreateCustomer([FromBody] CustomerCreateUpdateDto dto)
    {
        var customer = new Customer
        {
            CustomerName = dto.CustomerName,
            PrimaryContactFirstName = dto.PrimaryContactFirstName,
            PrimaryContactLastName = dto.PrimaryContactLastName,
            PrimaryContactJobTitle = dto.PrimaryContactJobTitle,
            PrimaryContactEmailAddress = dto.PrimaryContactEmailAddress,
            BusinessPhone = dto.BusinessPhone,
            Address = dto.Address,
            City = dto.City,
            State = dto.State,
            Zip = dto.Zip,
            Website = dto.Website,
            Notes = dto.Notes
        };

        _db.Customers.Add(customer);
        await _db.SaveChangesAsync();

        return CreatedAtAction(nameof(GetCustomer), new { id = customer.Id }, MapToDetail(customer));
    }

    // PUT /api/customers/{id}
    [HttpPut("{id:int}")]
    public async Task<ActionResult<CustomerDetailDto>> UpdateCustomer(int id, [FromBody] CustomerCreateUpdateDto dto)
    {
        var customer = await _db.Customers.FindAsync(id);
        if (customer == null) return NotFound(new { error = $"Customer {id} not found." });

        customer.CustomerName = dto.CustomerName;
        customer.PrimaryContactFirstName = dto.PrimaryContactFirstName;
        customer.PrimaryContactLastName = dto.PrimaryContactLastName;
        customer.PrimaryContactJobTitle = dto.PrimaryContactJobTitle;
        customer.PrimaryContactEmailAddress = dto.PrimaryContactEmailAddress;
        customer.BusinessPhone = dto.BusinessPhone;
        customer.Address = dto.Address;
        customer.City = dto.City;
        customer.State = dto.State;
        customer.Zip = dto.Zip;
        customer.Website = dto.Website;
        customer.Notes = dto.Notes;

        await _db.SaveChangesAsync();
        return Ok(MapToDetail(customer));
    }

    // DELETE /api/customers/{id}
    [HttpDelete("{id:int}")]
    public async Task<IActionResult> DeleteCustomer(int id)
    {
        var customer = await _db.Customers.FindAsync(id);
        if (customer == null) return NotFound(new { error = $"Customer {id} not found." });

        // Nullify FK on associated orders (matching nullable FK behavior)
        var orders = await _db.Orders.Where(o => o.CustomerId == id).ToListAsync();
        foreach (var order in orders)
            order.CustomerId = null;

        _db.Customers.Remove(customer);
        await _db.SaveChangesAsync();
        return NoContent();
    }

    // GET /api/customers/{id}/orders
    [HttpGet("{id:int}/orders")]
    public async Task<ActionResult<DTOs.PagedResult<OrderListItemDto>>> GetCustomerOrders(
        int id,
        [FromQuery] int? top,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 20)
    {
        var exists = await _db.Customers.AnyAsync(c => c.Id == id);
        if (!exists) return NotFound(new { error = $"Customer {id} not found." });

        var query = _db.Orders
            .Where(o => o.CustomerId == id)
            .Include(o => o.Customer)
            .Include(o => o.Employee)
            .Include(o => o.OrderDetails)
            .OrderByDescending(o => o.OrderDate);

        if (top.HasValue && top.Value > 0)
        {
            var topItems = await query.Take(top.Value).ToListAsync();
            return Ok(new DTOs.PagedResult<OrderListItemDto>
            {
                Items = topItems.Select(MapOrderToListItem),
                TotalCount = topItems.Count,
                Page = 1,
                PageSize = top.Value
            });
        }

        pageSize = Math.Min(pageSize, 100);
        page = Math.Max(page, 1);
        var total = await query.CountAsync();
        var items = await query.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

        return Ok(new DTOs.PagedResult<OrderListItemDto>
        {
            Items = items.Select(MapOrderToListItem),
            TotalCount = total,
            Page = page,
            PageSize = pageSize
        });
    }

    // GET /api/customers/{id}/products
    [HttpGet("{id:int}/products")]
    public async Task<ActionResult<IEnumerable<CustomerProductSummaryDto>>> GetCustomerProducts(int id)
    {
        var exists = await _db.Customers.AnyAsync(c => c.Id == id);
        if (!exists) return NotFound(new { error = $"Customer {id} not found." });

        var result = await _db.OrderDetails
            .Where(od => od.Order != null && od.Order.CustomerId == id)
            .Include(od => od.Product)
            .Include(od => od.Order)
            .GroupBy(od => new { od.ProductId, od.Product!.ProductCode, od.Product!.ProductName })
            .Select(g => new CustomerProductSummaryDto
            {
                ProductId = g.Key.ProductId,
                ProductCode = g.Key.ProductCode,
                ProductName = g.Key.ProductName,
                TotalQuantity = g.Sum(x => (int)x.Quantity),
                OrderCount = g.Select(x => x.OrderId).Distinct().Count(),
                FirstOrderDate = g.Min(x => x.Order!.OrderDate),
                LastOrderDate = g.Max(x => x.Order!.OrderDate)
            })
            .ToListAsync();

        return Ok(result);
    }

    private static CustomerDetailDto MapToDetail(Customer c) => new()
    {
        Id = c.Id,
        CustomerName = c.CustomerName,
        PrimaryContactFirstName = c.PrimaryContactFirstName,
        PrimaryContactLastName = c.PrimaryContactLastName,
        PrimaryContactFullName = c.PrimaryContactFullName,
        PrimaryContactJobTitle = c.PrimaryContactJobTitle,
        PrimaryContactEmailAddress = c.PrimaryContactEmailAddress,
        BusinessPhone = c.BusinessPhone,
        Address = c.Address,
        City = c.City,
        State = c.State,
        Zip = c.Zip,
        Website = c.Website,
        Notes = c.Notes,
        AddedBy = c.AddedBy,
        AddedOn = c.AddedOn,
        ModifiedBy = c.ModifiedBy,
        ModifiedOn = c.ModifiedOn
    };

    private static OrderListItemDto MapOrderToListItem(Order o) => new()
    {
        Id = o.Id,
        CustomerId = o.CustomerId,
        CustomerName = o.Customer?.CustomerName,
        EmployeeId = o.EmployeeId,
        EmployeeFullName = o.Employee != null
            ? $"{o.Employee.FirstName} {o.Employee.LastName}".Trim()
            : null,
        OrderDate = o.OrderDate,
        ShippedDate = o.ShippedDate,
        PaidDate = o.PaidDate,
        Status = o.Status.ToString(),
        StatusDisplay = o.Status.ToString(),
        OrderTotal = o.OrderTotal,
        ModifiedOn = o.ModifiedOn
    };
}
