// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Data;
using ApiApp.DTOs;
using ApiApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ApiApp.Controllers;

[ApiController]
[Route("api/employees")]
public class EmployeesController : ControllerBase
{
    private readonly AppDbContext _db;
    public EmployeesController(AppDbContext db) => _db = db;

    // GET api/employees
    [HttpGet]
    public async Task<ActionResult<IEnumerable<EmployeeDto>>> GetEmployees()
    {
        var employees = await _db.Employees
            .OrderBy(e => e.LastName).ThenBy(e => e.FirstName)
            .Select(e => EmployeeDto.FromEntity(e))
            .ToListAsync();
        return Ok(employees);
    }

    // GET api/employees/lookup
    [HttpGet("lookup")]
    public async Task<ActionResult<IEnumerable<EmployeeLookupDto>>> GetLookup()
    {
        var result = await _db.Employees
            .OrderBy(e => e.LastName).ThenBy(e => e.FirstName)
            .Select(e => new EmployeeLookupDto
            {
                EmployeeId = e.EmployeeId,
                FullNameFNLN = (e.FirstName ?? "") + " " + (e.LastName ?? "")
            })
            .ToListAsync();
        return Ok(result);
    }

    // GET api/employees/{id}
    [HttpGet("{id:int}")]
    public async Task<ActionResult<EmployeeDto>> GetEmployee(int id)
    {
        var employee = await _db.Employees.FindAsync(id);
        if (employee is null) return NotFound();
        return Ok(EmployeeDto.FromEntity(employee));
    }

    // POST api/employees
    [HttpPost]
    public async Task<ActionResult<EmployeeDto>> CreateEmployee([FromBody] EmployeeRequest request)
    {
        var employee = request.ToEntity();
        employee.AddedBy = "System";
        employee.AddedOn = DateTime.UtcNow;
        _db.Employees.Add(employee);
        await _db.SaveChangesAsync();
        return CreatedAtAction(nameof(GetEmployee), new { id = employee.EmployeeId }, EmployeeDto.FromEntity(employee));
    }

    // PUT api/employees/{id}
    [HttpPut("{id:int}")]
    public async Task<ActionResult<EmployeeDto>> UpdateEmployee(int id, [FromBody] EmployeeRequest request)
    {
        var employee = await _db.Employees.FindAsync(id);
        if (employee is null) return NotFound();
        request.ApplyTo(employee);
        employee.ModifiedBy = "System";
        employee.ModifiedOn = DateTime.UtcNow;
        await _db.SaveChangesAsync();
        return Ok(EmployeeDto.FromEntity(employee));
    }

    // DELETE api/employees/{id}
    [HttpDelete("{id:int}")]
    public async Task<IActionResult> DeleteEmployee(int id)
    {
        var employee = await _db.Employees.FindAsync(id);
        if (employee is null) return NotFound();
        _db.Employees.Remove(employee);
        await _db.SaveChangesAsync();
        return NoContent();
    }

    // GET api/employees/{id}/orders
    [HttpGet("{id:int}/orders")]
    public async Task<ActionResult<IEnumerable<OrderSummaryDto>>> GetEmployeeOrders(int id)
    {
        var exists = await _db.Employees.AnyAsync(e => e.EmployeeId == id);
        if (!exists) return NotFound();

        var orders = await _db.Orders
            .Where(o => o.EmployeeId == id)
            .Include(o => o.Customer)
            .Include(o => o.Employee)
            .Include(o => o.Status)
            .Include(o => o.OrderDetails)
            .OrderByDescending(o => o.OrderDate)
            .ToListAsync();

        return Ok(orders.Select(OrderSummaryDto.FromEntity));
    }
}
