// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Data;
using ApiApp.DTOs;
using ApiApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ApiApp.Controllers;

[ApiController]
[Route("api/orders")]
public class OrdersController : ControllerBase
{
    private readonly AppDbContext _db;
    public OrdersController(AppDbContext db) => _db = db;

    // GET api/orders[?customerId=&employeeId=&statusId=&orderDate=&top=]
    [HttpGet]
    public async Task<ActionResult<IEnumerable<OrderSummaryDto>>> GetOrders(
        [FromQuery] int? customerId,
        [FromQuery] int? employeeId,
        [FromQuery] int? statusId,
        [FromQuery] string? orderDate,
        [FromQuery] int? top)
    {
        var query = _db.Orders
            .Include(o => o.Customer)
            .Include(o => o.Employee)
            .Include(o => o.Status)
            .Include(o => o.OrderDetails)
            .AsQueryable();

        if (customerId.HasValue)
            query = query.Where(o => o.CustomerId == customerId.Value);
        if (employeeId.HasValue)
            query = query.Where(o => o.EmployeeId == employeeId.Value);
        if (statusId.HasValue)
            query = query.Where(o => o.StatusId == statusId.Value);
        if (!string.IsNullOrWhiteSpace(orderDate) && DateOnly.TryParse(orderDate, out var parsedDate))
        {
            var date = parsedDate.ToDateTime(TimeOnly.MinValue);
            query = query.Where(o => o.OrderDate.HasValue &&
                o.OrderDate.Value.Date == date.Date);
        }

        int limit = Math.Min(top ?? 20, 100);
        var orders = await query
            .OrderByDescending(o => o.OrderDate)
            .Take(limit)
            .ToListAsync();

        return Ok(orders.Select(OrderSummaryDto.FromEntity));
    }

    // GET api/orders/{id}
    [HttpGet("{id:int}")]
    public async Task<ActionResult<OrderFullDto>> GetOrder(int id)
    {
        var order = await _db.Orders
            .Include(o => o.Customer)
            .Include(o => o.Employee)
            .Include(o => o.Status)
            .Include(o => o.OrderDetails).ThenInclude(od => od.Product)
            .FirstOrDefaultAsync(o => o.OrderId == id);

        if (order is null) return NotFound();
        return Ok(OrderFullDto.FromEntity(order));
    }

    // POST api/orders
    [HttpPost]
    public async Task<ActionResult<OrderSummaryDto>> CreateOrder([FromBody] OrderRequest request)
    {
        var order = request.ToEntity();
        order.StatusId ??= 3; // Default to NEW
        order.AddedBy = "System";
        order.AddedOn = DateTime.UtcNow;
        _db.Orders.Add(order);
        await _db.SaveChangesAsync();

        // Reload with includes for response
        var created = await _db.Orders
            .Include(o => o.Customer)
            .Include(o => o.Employee)
            .Include(o => o.Status)
            .Include(o => o.OrderDetails)
            .FirstAsync(o => o.OrderId == order.OrderId);

        return CreatedAtAction(nameof(GetOrder), new { id = order.OrderId }, OrderSummaryDto.FromEntity(created));
    }

    // PUT api/orders/{id}
    [HttpPut("{id:int}")]
    public async Task<ActionResult<OrderSummaryDto>> UpdateOrder(int id, [FromBody] OrderRequest request)
    {
        var order = await _db.Orders
            .Include(o => o.Customer)
            .Include(o => o.Employee)
            .Include(o => o.Status)
            .Include(o => o.OrderDetails)
            .FirstOrDefaultAsync(o => o.OrderId == id);

        if (order is null) return NotFound();
        request.ApplyTo(order);
        order.ModifiedBy = "System";
        order.ModifiedOn = DateTime.UtcNow;
        await _db.SaveChangesAsync();

        // Reload after update
        await _db.Entry(order).Reference(o => o.Customer).LoadAsync();
        await _db.Entry(order).Reference(o => o.Employee).LoadAsync();
        await _db.Entry(order).Reference(o => o.Status).LoadAsync();

        return Ok(OrderSummaryDto.FromEntity(order));
    }

    // DELETE api/orders/{id}
    [HttpDelete("{id:int}")]
    public async Task<IActionResult> DeleteOrder(int id)
    {
        var order = await _db.Orders.FindAsync(id);
        if (order is null) return NotFound();
        _db.Orders.Remove(order); // Cascade deletes OrderDetails
        await _db.SaveChangesAsync();
        return NoContent();
    }
}
