// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Data;
using ApiApp.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ApiApp.Controllers;

[ApiController]
[Route("api/orderstatuses")]
public class OrderStatusesController : ControllerBase
{
    private readonly AppDbContext _db;
    public OrderStatusesController(AppDbContext db) => _db = db;

    // GET api/orderstatuses
    [HttpGet]
    public async Task<ActionResult<IEnumerable<OrderStatusDto>>> GetOrderStatuses()
    {
        var statuses = await _db.OrderStatuses
            .OrderBy(s => s.SortOrder)
            .Select(s => OrderStatusDto.FromEntity(s))
            .ToListAsync();
        return Ok(statuses);
    }
}
