// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Data;
using ApiApp.DTOs;
using ApiApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ApiApp.Controllers;

[ApiController]
[Route("api/orders/{orderId:int}/details")]
public class OrderDetailsController : ControllerBase
{
    private readonly AppDbContext _db;
    public OrderDetailsController(AppDbContext db) => _db = db;

    // GET api/orders/{orderId}/details
    [HttpGet]
    public async Task<ActionResult<IEnumerable<OrderLineDto>>> GetDetails(int orderId)
    {
        var orderExists = await _db.Orders.AnyAsync(o => o.OrderId == orderId);
        if (!orderExists) return NotFound();

        var details = await _db.OrderDetails
            .Where(od => od.OrderId == orderId)
            .Include(od => od.Product)
            .Select(od => OrderLineDto.FromEntity(od))
            .ToListAsync();

        return Ok(details);
    }

    // POST api/orders/{orderId}/details
    [HttpPost]
    public async Task<ActionResult<OrderLineDto>> CreateDetail(int orderId, [FromBody] OrderLineRequest request)
    {
        var orderExists = await _db.Orders.AnyAsync(o => o.OrderId == orderId);
        if (!orderExists) return NotFound();

        // Default UnitPrice from product if not provided
        decimal? unitPrice = request.UnitPrice;
        if (!unitPrice.HasValue && request.ProductId.HasValue)
        {
            var product = await _db.Products.FindAsync(request.ProductId.Value);
            unitPrice = product?.UnitPrice;
        }

        var detail = new OrderDetail
        {
            OrderId = orderId,
            ProductId = request.ProductId,
            Quantity = request.Quantity,
            UnitPrice = unitPrice,
            AddedBy = "System",
            AddedOn = DateTime.UtcNow
        };
        _db.OrderDetails.Add(detail);
        await _db.SaveChangesAsync();

        await _db.Entry(detail).Reference(od => od.Product).LoadAsync();
        return StatusCode(201, OrderLineDto.FromEntity(detail));
    }

    // PUT api/orders/{orderId}/details/{detailId}
    [HttpPut("{detailId:int}")]
    public async Task<ActionResult<OrderLineDto>> UpdateDetail(int orderId, int detailId, [FromBody] OrderLineRequest request)
    {
        var detail = await _db.OrderDetails
            .Include(od => od.Product)
            .FirstOrDefaultAsync(od => od.OrderDetailId == detailId && od.OrderId == orderId);

        if (detail is null) return NotFound();

        detail.ProductId = request.ProductId ?? detail.ProductId;
        detail.Quantity = request.Quantity ?? detail.Quantity;
        detail.UnitPrice = request.UnitPrice ?? detail.UnitPrice;
        detail.ModifiedBy = "System";
        detail.ModifiedOn = DateTime.UtcNow;
        await _db.SaveChangesAsync();

        if (detail.ProductId.HasValue && detail.Product?.ProductId != detail.ProductId)
            await _db.Entry(detail).Reference(od => od.Product).LoadAsync();

        return Ok(OrderLineDto.FromEntity(detail));
    }

    // DELETE api/orders/{orderId}/details/{detailId}
    [HttpDelete("{detailId:int}")]
    public async Task<IActionResult> DeleteDetail(int orderId, int detailId)
    {
        var detail = await _db.OrderDetails
            .FirstOrDefaultAsync(od => od.OrderDetailId == detailId && od.OrderId == orderId);

        if (detail is null) return NotFound();
        _db.OrderDetails.Remove(detail);
        await _db.SaveChangesAsync();
        return NoContent();
    }
}
