// Generated by booster-apidev | 2026-04-06 19:37:30

using ApiApp.Data;
using ApiApp.DTOs.Products;
using ApiApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ApiApp.Controllers;

[ApiController]
[Route("api/products")]
public class ProductsController : ControllerBase
{
    private readonly AppDbContext _db;

    public ProductsController(AppDbContext db)
    {
        _db = db;
    }

    // GET /api/products
    [HttpGet]
    public async Task<ActionResult<DTOs.PagedResult<ProductListItemDto>>> GetProducts(
        [FromQuery] string? search,
        [FromQuery] bool includeSalesStats = false,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 20)
    {
        pageSize = Math.Min(pageSize, 100);
        page = Math.Max(page, 1);

        var query = _db.Products.AsQueryable();

        if (!string.IsNullOrWhiteSpace(search))
        {
            var s = search.ToLower();
            query = query.Where(p =>
                (p.ProductCode != null && p.ProductCode.ToLower().Contains(s)) ||
                (p.ProductName != null && p.ProductName.ToLower().Contains(s)));
        }

        var totalCount = await query.CountAsync();

        if (includeSalesStats)
        {
            // Calculate ISO week bounds for "sold this week"
            var today = DateTime.UtcNow.Date;
            var dow = (int)today.DayOfWeek;
            // ISO week starts Monday
            var weekStart = today.AddDays(-(dow == 0 ? 6 : dow - 1));
            var weekEnd = weekStart.AddDays(7);

            var items = await query
                .OrderBy(p => p.ProductName)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .Select(p => new ProductListItemDto
                {
                    Id = p.Id,
                    ProductCode = p.ProductCode,
                    ProductName = p.ProductName,
                    UnitPrice = p.UnitPrice,
                    TotalQuantitySold = p.OrderDetails.Sum(od => (int)od.Quantity),
                    OrderCount = p.OrderDetails.Select(od => od.OrderId).Distinct().Count(),
                    SoldThisWeek = p.OrderDetails
                        .Where(od => od.Order != null && od.Order.OrderDate >= weekStart && od.Order.OrderDate < weekEnd)
                        .Select(od => od.OrderId)
                        .Distinct()
                        .Count()
                })
                .ToListAsync();

            return Ok(new DTOs.PagedResult<ProductListItemDto>
            {
                Items = items,
                TotalCount = totalCount,
                Page = page,
                PageSize = pageSize
            });
        }
        else
        {
            var items = await query
                .OrderBy(p => p.ProductName)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .Select(p => new ProductListItemDto
                {
                    Id = p.Id,
                    ProductCode = p.ProductCode,
                    ProductName = p.ProductName,
                    UnitPrice = p.UnitPrice,
                    TotalQuantitySold = null,
                    OrderCount = null,
                    SoldThisWeek = null
                })
                .ToListAsync();

            return Ok(new DTOs.PagedResult<ProductListItemDto>
            {
                Items = items,
                TotalCount = totalCount,
                Page = page,
                PageSize = pageSize
            });
        }
    }

    // GET /api/products/{id}
    [HttpGet("{id:int}")]
    public async Task<ActionResult<ProductDetailDto>> GetProduct(int id)
    {
        var p = await _db.Products.FindAsync(id);
        if (p == null) return NotFound(new { error = $"Product {id} not found." });
        return Ok(MapToDetail(p));
    }

    // POST /api/products
    [HttpPost]
    public async Task<ActionResult<ProductDetailDto>> CreateProduct([FromBody] ProductCreateUpdateDto dto)
    {
        if (await _db.Products.AnyAsync(p => p.ProductCode == dto.ProductCode))
        {
            return BadRequest(new { errors = new { ProductCode = new[] { $"ProductCode '{dto.ProductCode}' already exists." } } });
        }

        var product = new Product
        {
            ProductCode = dto.ProductCode,
            ProductName = dto.ProductName,
            ProductDescription = dto.ProductDescription,
            UnitPrice = dto.UnitPrice
        };

        _db.Products.Add(product);
        await _db.SaveChangesAsync();

        return CreatedAtAction(nameof(GetProduct), new { id = product.Id }, MapToDetail(product));
    }

    // PUT /api/products/{id}
    [HttpPut("{id:int}")]
    public async Task<ActionResult<ProductDetailDto>> UpdateProduct(int id, [FromBody] ProductCreateUpdateDto dto)
    {
        var product = await _db.Products.FindAsync(id);
        if (product == null) return NotFound(new { error = $"Product {id} not found." });

        if (await _db.Products.AnyAsync(p => p.ProductCode == dto.ProductCode && p.Id != id))
        {
            return BadRequest(new { errors = new { ProductCode = new[] { $"ProductCode '{dto.ProductCode}' already exists." } } });
        }

        product.ProductCode = dto.ProductCode;
        product.ProductName = dto.ProductName;
        product.ProductDescription = dto.ProductDescription;
        product.UnitPrice = dto.UnitPrice;

        await _db.SaveChangesAsync();
        return Ok(MapToDetail(product));
    }

    // DELETE /api/products/{id}
    [HttpDelete("{id:int}")]
    public async Task<IActionResult> DeleteProduct(int id)
    {
        var product = await _db.Products.FindAsync(id);
        if (product == null) return NotFound(new { error = $"Product {id} not found." });

        if (await _db.OrderDetails.AnyAsync(od => od.ProductId == id))
        {
            return Conflict(new { error = "Cannot delete product with existing order history." });
        }

        _db.Products.Remove(product);
        await _db.SaveChangesAsync();
        return NoContent();
    }

    // GET /api/products/{id}/orders
    [HttpGet("{id:int}/orders")]
    public async Task<ActionResult<IEnumerable<ProductOrderSummaryDto>>> GetProductOrders(int id)
    {
        var exists = await _db.Products.AnyAsync(p => p.Id == id);
        if (!exists) return NotFound(new { error = $"Product {id} not found." });

        var result = await _db.OrderDetails
            .Where(od => od.ProductId == id)
            .Include(od => od.Order).ThenInclude(o => o!.Customer)
            .Select(od => new ProductOrderSummaryDto
            {
                OrderId = od.OrderId,
                OrderDate = od.Order != null ? od.Order.OrderDate : null,
                CustomerName = od.Order != null && od.Order.Customer != null ? od.Order.Customer.CustomerName : null,
                Quantity = od.Quantity,
                UnitPrice = od.UnitPrice,
                ExtendedPrice = od.Quantity * od.UnitPrice
            })
            .ToListAsync();

        return Ok(result);
    }

    private static ProductDetailDto MapToDetail(Product p) => new()
    {
        Id = p.Id,
        ProductCode = p.ProductCode,
        ProductName = p.ProductName,
        ProductDescription = p.ProductDescription,
        UnitPrice = p.UnitPrice,
        AddedBy = p.AddedBy,
        AddedOn = p.AddedOn,
        ModifiedBy = p.ModifiedBy,
        ModifiedOn = p.ModifiedOn
    };
}
