// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Data;
using ApiApp.DTOs;
using ApiApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ApiApp.Controllers;

[ApiController]
[Route("api/products")]
public class ProductsController : ControllerBase
{
    private readonly AppDbContext _db;
    public ProductsController(AppDbContext db) => _db = db;

    // GET api/products[?search=...]
    [HttpGet]
    public async Task<ActionResult<IEnumerable<ProductDto>>> GetProducts([FromQuery] string? search)
    {
        var weekAgo = DateTime.UtcNow.AddDays(-7);

        var query = _db.Products.AsQueryable();
        if (!string.IsNullOrWhiteSpace(search))
        {
            query = query.Where(p =>
                (p.ProductCode != null && p.ProductCode.Contains(search)) ||
                (p.ProductName != null && p.ProductName.Contains(search)));
        }

        var products = await query
            .OrderBy(p => p.ProductName)
            .Select(p => new
            {
                Product = p,
                TotalOrderCount = p.OrderDetails.Count(),
                SoldThisWeek = p.OrderDetails
                    .Where(od => od.Order!.OrderDate >= weekAgo)
                    .Sum(od => (int?)(int)(od.Quantity ?? 0))
            })
            .ToListAsync();

        return Ok(products.Select(x => ProductDto.FromEntity(x.Product, x.TotalOrderCount, x.SoldThisWeek ?? 0)));
    }

    // GET api/products/lookup
    [HttpGet("lookup")]
    public async Task<ActionResult<IEnumerable<ProductLookupDto>>> GetLookup()
    {
        var result = await _db.Products
            .OrderBy(p => p.ProductName)
            .Select(p => new ProductLookupDto
            {
                ProductId = p.ProductId,
                ProductName = p.ProductName,
                ProductCode = p.ProductCode,
                UnitPrice = p.UnitPrice
            })
            .ToListAsync();
        return Ok(result);
    }

    // GET api/products/{id}
    [HttpGet("{id:int}")]
    public async Task<ActionResult<ProductDto>> GetProduct(int id)
    {
        var weekAgo = DateTime.UtcNow.AddDays(-7);
        var p = await _db.Products
            .Where(p => p.ProductId == id)
            .Select(p => new
            {
                Product = p,
                TotalOrderCount = p.OrderDetails.Count(),
                SoldThisWeek = p.OrderDetails
                    .Where(od => od.Order!.OrderDate >= weekAgo)
                    .Sum(od => (int?)(int)(od.Quantity ?? 0))
            })
            .FirstOrDefaultAsync();

        if (p is null) return NotFound();
        return Ok(ProductDto.FromEntity(p.Product, p.TotalOrderCount, p.SoldThisWeek ?? 0));
    }

    // POST api/products
    [HttpPost]
    public async Task<ActionResult<ProductDto>> CreateProduct([FromBody] ProductRequest request)
    {
        var product = request.ToEntity();
        product.AddedBy = "System";
        product.AddedOn = DateTime.UtcNow;
        _db.Products.Add(product);
        await _db.SaveChangesAsync();
        return CreatedAtAction(nameof(GetProduct), new { id = product.ProductId }, ProductDto.FromEntity(product));
    }

    // PUT api/products/{id}
    [HttpPut("{id:int}")]
    public async Task<ActionResult<ProductDto>> UpdateProduct(int id, [FromBody] ProductRequest request)
    {
        var product = await _db.Products.FindAsync(id);
        if (product is null) return NotFound();
        request.ApplyTo(product);
        product.ModifiedBy = "System";
        product.ModifiedOn = DateTime.UtcNow;
        await _db.SaveChangesAsync();
        return Ok(ProductDto.FromEntity(product));
    }

    // DELETE api/products/{id}
    [HttpDelete("{id:int}")]
    public async Task<IActionResult> DeleteProduct(int id)
    {
        var product = await _db.Products.FindAsync(id);
        if (product is null) return NotFound();
        _db.Products.Remove(product);
        await _db.SaveChangesAsync();
        return NoContent();
    }

    // GET api/products/{id}/orders
    [HttpGet("{id:int}/orders")]
    public async Task<ActionResult<IEnumerable<ProductOrderDto>>> GetProductOrders(int id)
    {
        var exists = await _db.Products.AnyAsync(p => p.ProductId == id);
        if (!exists) return NotFound();

        var result = await _db.OrderDetails
            .Where(od => od.ProductId == id)
            .Include(od => od.Order).ThenInclude(o => o!.Customer)
            .OrderByDescending(od => od.Order!.OrderDate)
            .Select(od => new ProductOrderDto
            {
                OrderId = od.Order!.OrderId,
                OrderDate = od.Order.OrderDate,
                CustomerName = od.Order.Customer != null ? od.Order.Customer.CustomerName : null,
                Quantity = od.Quantity,
                UnitPrice = od.UnitPrice,
                ExtendedPrice = (od.Quantity ?? 0) * (od.UnitPrice ?? 0)
            })
            .ToListAsync();

        return Ok(result);
    }
}
