// Generated by booster-apidev | 2026-04-06 19:37:30

using ApiApp.Data;
using ApiApp.DTOs.Reports;
using ApiApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ApiApp.Controllers;

[ApiController]
[Route("api/reports")]
public class ReportsController : ControllerBase
{
    private readonly AppDbContext _db;

    public ReportsController(AppDbContext db)
    {
        _db = db;
    }

    // GET /api/reports/sales-ytd
    [HttpGet("sales-ytd")]
    public async Task<ActionResult<SalesYtdDto>> GetSalesYtd()
    {
        var year = DateTime.UtcNow.Year;
        var start = new DateTime(year, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        var end = start.AddYears(1);

        var total = await _db.OrderDetails
            .Where(od => od.Order != null && od.Order.OrderDate >= start && od.Order.OrderDate < end)
            .SumAsync(od => (decimal?)((decimal)od.Quantity * od.UnitPrice)) ?? 0m;

        return Ok(new SalesYtdDto { Year = year, TotalSales = total });
    }

    // GET /api/reports/sales-by-employee
    [HttpGet("sales-by-employee")]
    public async Task<ActionResult<IEnumerable<SalesByEmployeeDto>>> GetSalesByEmployee(
        [FromQuery] int? year,
        [FromQuery] string? groupBy)
    {
        var targetYear = year ?? DateTime.UtcNow.Year;
        var start = new DateTime(targetYear, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        var end = start.AddYears(1);

        var data = await _db.OrderDetails
            .Where(od => od.Order != null
                && od.Order.EmployeeId != null
                && od.Order.OrderDate >= start
                && od.Order.OrderDate < end)
            .Include(od => od.Order).ThenInclude(o => o!.Employee)
            .ToListAsync();

        var result = data
            .GroupBy(od => new
            {
                EmployeeId = od.Order!.EmployeeId!.Value,
                EmployeeName = od.Order.Employee != null
                    ? $"{od.Order.Employee.FirstName} {od.Order.Employee.LastName}".Trim()
                    : "Unknown",
                Month = od.Order.OrderDate!.Value.Month,
                Year = od.Order.OrderDate.Value.Year
            })
            .Select(g => new SalesByEmployeeDto
            {
                EmployeeId = g.Key.EmployeeId,
                EmployeeFullName = g.Key.EmployeeName,
                MonthYear = $"{g.Key.Year:D4}-{g.Key.Month:D2}",
                MonthYearSort = $"{g.Key.Year:D4}-{g.Key.Month:D2}",
                TotalSales = g.Sum(od => od.Quantity * od.UnitPrice)
            })
            .OrderBy(x => x.EmployeeFullName)
            .ThenBy(x => x.MonthYearSort)
            .ToList();

        // Reformat MonthYear for display after sorting
        foreach (var item in result)
        {
            if (DateTime.TryParse(item.MonthYear + "-01", out var dt))
                item.MonthYear = dt.ToString("MMM-yyyy");
        }

        return Ok(result);
    }

    // GET /api/reports/sales-by-product
    [HttpGet("sales-by-product")]
    public async Task<ActionResult<IEnumerable<SalesByProductDto>>> GetSalesByProduct(
        [FromQuery] int? year,
        [FromQuery] string? groupBy)
    {
        var targetYear = year ?? DateTime.UtcNow.Year;
        var start = new DateTime(targetYear, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        var end = start.AddYears(1);

        var data = await _db.OrderDetails
            .Where(od => od.Order != null && od.Order.OrderDate >= start && od.Order.OrderDate < end)
            .Include(od => od.Product)
            .Include(od => od.Order)
            .ToListAsync();

        bool byQuarter = groupBy?.ToLower() == "quarter";

        IEnumerable<SalesByProductDto> result;

        if (byQuarter)
        {
            result = data
                .GroupBy(od => new
                {
                    ProductId = od.ProductId,
                    ProductCode = od.Product?.ProductCode,
                    ProductName = od.Product?.ProductName,
                    Quarter = (od.Order!.OrderDate!.Value.Month - 1) / 3 + 1,
                    Year = od.Order.OrderDate.Value.Year
                })
                .Select(g => new SalesByProductDto
                {
                    ProductId = g.Key.ProductId,
                    ProductCode = g.Key.ProductCode,
                    ProductName = g.Key.ProductName,
                    Period = $"Q{g.Key.Quarter}-{g.Key.Year}",
                    PeriodSort = $"{g.Key.Year:D4}-Q{g.Key.Quarter}",
                    TotalSales = g.Sum(od => od.Quantity * od.UnitPrice)
                })
                .OrderBy(x => x.ProductName)
                .ThenBy(x => x.PeriodSort);
        }
        else
        {
            result = data
                .GroupBy(od => new
                {
                    ProductId = od.ProductId,
                    ProductCode = od.Product?.ProductCode,
                    ProductName = od.Product?.ProductName,
                    Month = od.Order!.OrderDate!.Value.Month,
                    Year = od.Order.OrderDate.Value.Year
                })
                .Select(g => new SalesByProductDto
                {
                    ProductId = g.Key.ProductId,
                    ProductCode = g.Key.ProductCode,
                    ProductName = g.Key.ProductName,
                    Period = $"{g.Key.Year:D4}-{g.Key.Month:D2}",
                    PeriodSort = $"{g.Key.Year:D4}-{g.Key.Month:D2}",
                    TotalSales = g.Sum(od => od.Quantity * od.UnitPrice)
                })
                .OrderBy(x => x.ProductName)
                .ThenBy(x => x.PeriodSort)
                .ToList();

            // Reformat period for display
            foreach (var item in result)
            {
                if (DateTime.TryParse(item.Period + "-01", out var dt))
                    item.Period = dt.ToString("MMM-yyyy");
            }
        }

        return Ok(result);
    }

    // GET /api/reports/invoice/{orderId}
    [HttpGet("invoice/{orderId:int}")]
    public async Task<ActionResult<InvoiceDto>> GetInvoice(int orderId)
    {
        var order = await _db.Orders
            .Include(o => o.Customer)
            .Include(o => o.Employee)
            .Include(o => o.OrderDetails).ThenInclude(od => od.Product)
            .FirstOrDefaultAsync(o => o.Id == orderId);

        if (order == null) return NotFound(new { error = $"Order {orderId} not found." });

        // Load tax rate from system settings
        var taxSetting = await _db.SystemSettings
            .FirstOrDefaultAsync(s => s.SettingName == "TaxRate");

        decimal taxRate = 0m;
        if (taxSetting != null && decimal.TryParse(taxSetting.SettingValue, out var rawRate))
        {
            taxRate = rawRate / 1000m;
        }

        decimal subtotal = order.OrderDetails.Sum(od => od.Quantity * od.UnitPrice);
        decimal taxAmount = Math.Round(subtotal * taxRate, 2);
        decimal total = subtotal + taxAmount;

        var invoice = new InvoiceDto
        {
            OrderId = order.Id,
            OrderDate = order.OrderDate,
            Customer = order.Customer == null ? null : new InvoiceCustomerDto
            {
                Id = order.Customer.Id,
                CustomerName = order.Customer.CustomerName,
                Address = order.Customer.Address,
                City = order.Customer.City,
                State = order.Customer.State,
                Zip = order.Customer.Zip
            },
            Employee = order.Employee == null ? null : new InvoiceEmployeeDto
            {
                Id = order.Employee.Id,
                FullName = $"{order.Employee.FirstName} {order.Employee.LastName}".Trim()
            },
            Status = order.Status.ToString(),
            LineItems = order.OrderDetails.Select(od => new InvoiceLineItemDto
            {
                ProductCode = od.Product?.ProductCode,
                ProductName = od.Product?.ProductName,
                Quantity = od.Quantity,
                UnitPrice = od.UnitPrice,
                ExtendedPrice = od.ExtendedPrice
            }).ToList(),
            Subtotal = subtotal,
            TaxRate = taxRate,
            TaxAmount = taxAmount,
            Total = total
        };

        return Ok(invoice);
    }

    // GET /api/reports/employee-email-list
    [HttpGet("employee-email-list")]
    public async Task<ActionResult<IEnumerable<EmployeeEmailListDto>>> GetEmployeeEmailList()
    {
        var result = await _db.Employees
            .OrderBy(e => e.LastName).ThenBy(e => e.FirstName)
            .Select(e => new EmployeeEmailListDto
            {
                EmployeeId = e.Id,
                FullNameLNFN = (e.LastName != null && e.FirstName != null)
                    ? e.LastName + ", " + e.FirstName
                    : (e.LastName ?? e.FirstName ?? ""),
                EmailAddress = e.EmailAddress
            })
            .ToListAsync();

        return Ok(result);
    }

    // GET /api/reports/employee-phone-list
    [HttpGet("employee-phone-list")]
    public async Task<ActionResult<IEnumerable<EmployeePhoneListDto>>> GetEmployeePhoneList()
    {
        var result = await _db.Employees
            .OrderBy(e => e.LastName).ThenBy(e => e.FirstName)
            .Select(e => new EmployeePhoneListDto
            {
                EmployeeId = e.Id,
                FullNameLNFN = (e.LastName != null && e.FirstName != null)
                    ? e.LastName + ", " + e.FirstName
                    : (e.LastName ?? e.FirstName ?? ""),
                PrimaryPhone = e.PrimaryPhone,
                SecondaryPhone = e.SecondaryPhone
            })
            .ToListAsync();

        return Ok(result);
    }
}
