// > Generated by booster-apidev | 2026-04-07 11:36:00
using ApiApp.Data;
using ApiApp.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ApiApp.Controllers;

[ApiController]
[Route("api/reports")]
public class ReportsController : ControllerBase
{
    private readonly AppDbContext _db;
    public ReportsController(AppDbContext db) => _db = db;

    // GET api/reports/sales-ytd
    [HttpGet("sales-ytd")]
    public async Task<ActionResult<SalesYtdDto>> GetSalesYtd()
    {
        var year = DateTime.UtcNow.Year;
        var yearStart = new DateTime(year, 1, 1);
        var yearEnd = new DateTime(year + 1, 1, 1);

        var total = await _db.OrderDetails
            .Where(od => od.Order!.OrderDate.HasValue &&
                         od.Order.OrderDate >= yearStart &&
                         od.Order.OrderDate < yearEnd)
            .SumAsync(od => (decimal?)(od.Quantity ?? 0) * (od.UnitPrice ?? 0));

        return Ok(new SalesYtdDto { Year = year, TotalRevenue = total ?? 0m });
    }

    // GET api/reports/sales-by-employee
    [HttpGet("sales-by-employee")]
    public async Task<ActionResult<IEnumerable<SalesByEmployeeDto>>> GetSalesByEmployee()
    {
        var year = DateTime.UtcNow.Year;
        var yearStart = new DateTime(year, 1, 1);
        var yearEnd = new DateTime(year + 1, 1, 1);

        var raw = await _db.OrderDetails
            .Where(od => od.Order!.OrderDate.HasValue &&
                         od.Order.OrderDate >= yearStart &&
                         od.Order.OrderDate < yearEnd &&
                         od.Order.EmployeeId.HasValue)
            .Select(od => new
            {
                od.Order!.EmployeeId,
                FirstName = od.Order.Employee != null ? od.Order.Employee.FirstName : null,
                LastName = od.Order.Employee != null ? od.Order.Employee.LastName : null,
                LineTotal = (decimal?)(od.Quantity ?? 0) * (od.UnitPrice ?? 0)
            })
            .ToListAsync();

        var result = raw
            .GroupBy(x => new { x.EmployeeId, x.FirstName, x.LastName })
            .Select(g => new SalesByEmployeeDto
            {
                EmployeeId = g.Key.EmployeeId!.Value,
                EmployeeFullName = $"{g.Key.FirstName} {g.Key.LastName}".Trim(),
                TotalRevenue = g.Sum(x => x.LineTotal ?? 0m)
            })
            .OrderByDescending(x => x.TotalRevenue)
            .ToList();

        return Ok(result);
    }

    // GET api/reports/sales-by-product[?from=&to=]
    [HttpGet("sales-by-product")]
    public async Task<ActionResult<IEnumerable<SalesByProductDto>>> GetSalesByProduct(
        [FromQuery] string? from, [FromQuery] string? to)
    {
        var query = _db.OrderDetails
            .Where(od => od.Order!.OrderDate.HasValue && od.ProductId.HasValue);

        if (!string.IsNullOrEmpty(from) && DateOnly.TryParse(from, out var fromDate))
            query = query.Where(od => od.Order!.OrderDate >= fromDate.ToDateTime(TimeOnly.MinValue));
        if (!string.IsNullOrEmpty(to) && DateOnly.TryParse(to, out var toDate))
            query = query.Where(od => od.Order!.OrderDate <= toDate.ToDateTime(TimeOnly.MaxValue));

        var raw = await query
            .Select(od => new
            {
                od.ProductId,
                ProductName = od.Product != null ? od.Product.ProductName : null,
                Year = od.Order!.OrderDate!.Value.Year,
                Month = od.Order.OrderDate!.Value.Month,
                LineTotal = (decimal?)(od.Quantity ?? 0) * (od.UnitPrice ?? 0)
            })
            .ToListAsync();

        var result = raw
            .GroupBy(x => new { x.ProductId, x.ProductName, x.Year, x.Month })
            .Select(g => new SalesByProductDto
            {
                ProductId = g.Key.ProductId!.Value,
                ProductName = g.Key.ProductName,
                MonthYear = new DateTime(g.Key.Year, g.Key.Month, 1).ToString("MMM-yyyy"),
                MonthYearSort = $"{g.Key.Year:D4}-{g.Key.Month:D2}",
                OrderTotal = g.Sum(x => x.LineTotal ?? 0m)
            })
            .OrderBy(x => x.MonthYearSort).ThenBy(x => x.ProductName)
            .ToList();

        return Ok(result);
    }

    // GET api/reports/sales-by-product-quarterly[?from=&to=]
    [HttpGet("sales-by-product-quarterly")]
    public async Task<ActionResult<IEnumerable<SalesByProductQuarterlyDto>>> GetSalesByProductQuarterly(
        [FromQuery] string? from, [FromQuery] string? to)
    {
        var query = _db.OrderDetails
            .Where(od => od.Order!.OrderDate.HasValue && od.ProductId.HasValue);

        if (!string.IsNullOrEmpty(from) && DateOnly.TryParse(from, out var fromDate))
            query = query.Where(od => od.Order!.OrderDate >= fromDate.ToDateTime(TimeOnly.MinValue));
        if (!string.IsNullOrEmpty(to) && DateOnly.TryParse(to, out var toDate))
            query = query.Where(od => od.Order!.OrderDate <= toDate.ToDateTime(TimeOnly.MaxValue));

        var raw = await query
            .Select(od => new
            {
                od.ProductId,
                ProductName = od.Product != null ? od.Product.ProductName : null,
                Year = od.Order!.OrderDate!.Value.Year,
                Month = od.Order.OrderDate!.Value.Month,
                LineTotal = (decimal?)(od.Quantity ?? 0) * (od.UnitPrice ?? 0)
            })
            .ToListAsync();

        var result = raw
            .GroupBy(x => new { x.ProductId, x.ProductName, x.Year, Quarter = (x.Month - 1) / 3 + 1 })
            .Select(g => new SalesByProductQuarterlyDto
            {
                ProductId = g.Key.ProductId!.Value,
                ProductName = g.Key.ProductName,
                QuarterYear = $"{g.Key.Quarter}-{g.Key.Year}",
                OrderTotal = g.Sum(x => x.LineTotal ?? 0m)
            })
            .OrderBy(x => x.QuarterYear).ThenBy(x => x.ProductName)
            .ToList();

        return Ok(result);
    }

    // GET api/reports/sales-by-employee-monthly[?from=&to=]
    [HttpGet("sales-by-employee-monthly")]
    public async Task<ActionResult<IEnumerable<SalesByEmployeeMonthlyDto>>> GetSalesByEmployeeMonthly(
        [FromQuery] string? from, [FromQuery] string? to)
    {
        var query = _db.OrderDetails
            .Where(od => od.Order!.OrderDate.HasValue && od.Order.EmployeeId.HasValue);

        if (!string.IsNullOrEmpty(from) && DateOnly.TryParse(from, out var fromDate))
            query = query.Where(od => od.Order!.OrderDate >= fromDate.ToDateTime(TimeOnly.MinValue));
        if (!string.IsNullOrEmpty(to) && DateOnly.TryParse(to, out var toDate))
            query = query.Where(od => od.Order!.OrderDate <= toDate.ToDateTime(TimeOnly.MaxValue));

        var raw = await query
            .Select(od => new
            {
                od.Order!.EmployeeId,
                FirstName = od.Order.Employee != null ? od.Order.Employee.FirstName : null,
                LastName = od.Order.Employee != null ? od.Order.Employee.LastName : null,
                Year = od.Order.OrderDate!.Value.Year,
                Month = od.Order.OrderDate.Value.Month,
                LineTotal = (decimal?)(od.Quantity ?? 0) * (od.UnitPrice ?? 0)
            })
            .ToListAsync();

        var result = raw
            .GroupBy(x => new { x.EmployeeId, x.FirstName, x.LastName, x.Year, x.Month })
            .Select(g => new SalesByEmployeeMonthlyDto
            {
                EmployeeId = g.Key.EmployeeId!.Value,
                EmployeeFullName = $"{g.Key.FirstName} {g.Key.LastName}".Trim(),
                MonthYear = new DateTime(g.Key.Year, g.Key.Month, 1).ToString("MMM-yyyy"),
                MonthYearSort = $"{g.Key.Year:D4}-{g.Key.Month:D2}",
                OrderTotal = g.Sum(x => x.LineTotal ?? 0m)
            })
            .OrderBy(x => x.MonthYearSort).ThenBy(x => x.EmployeeFullName)
            .ToList();

        return Ok(result);
    }

    // GET api/reports/invoice/{orderId}
    [HttpGet("invoice/{orderId:int}")]
    public async Task<ActionResult<InvoiceDto>> GetInvoice(int orderId)
    {
        var order = await _db.Orders
            .Include(o => o.Customer)
            .Include(o => o.Employee)
            .Include(o => o.Status)
            .Include(o => o.OrderDetails).ThenInclude(od => od.Product)
            .FirstOrDefaultAsync(o => o.OrderId == orderId);

        if (order is null) return NotFound();

        var invoice = new InvoiceDto
        {
            OrderId = order.OrderId,
            OrderDate = order.OrderDate,
            CustomerName = order.Customer?.CustomerName,
            CustomerAddress = order.Customer?.Address,
            CustomerCity = order.Customer?.City,
            CustomerState = order.Customer?.State,
            CustomerZip = order.Customer?.Zip,
            EmployeeFullName = order.Employee != null
                ? $"{order.Employee.FirstName} {order.Employee.LastName}".Trim()
                : null,
            StatusName = order.Status?.StatusName,
            LineItems = order.OrderDetails.Select(od => new InvoiceLineItemDto
            {
                ProductCode = od.Product?.ProductCode,
                ProductName = od.Product?.ProductName,
                Quantity = od.Quantity ?? 0,
                UnitPrice = od.UnitPrice ?? 0m,
                ExtendedPrice = (od.Quantity ?? 0) * (od.UnitPrice ?? 0m)
            }).ToList(),
            OrderTotal = order.OrderDetails.Sum(od => (od.Quantity ?? 0) * (od.UnitPrice ?? 0m))
        };
        return Ok(invoice);
    }

    // GET api/reports/employee-email-list
    [HttpGet("employee-email-list")]
    public async Task<ActionResult<IEnumerable<EmployeeEmailDto>>> GetEmployeeEmailList()
    {
        var result = await _db.Employees
            .OrderBy(e => e.LastName).ThenBy(e => e.FirstName)
            .Select(e => new EmployeeEmailDto
            {
                EmployeeId = e.EmployeeId,
                FullNameLNFN = (e.LastName ?? "") + ", " + (e.FirstName ?? ""),
                EmailAddress = e.EmailAddress
            })
            .ToListAsync();
        return Ok(result);
    }

    // GET api/reports/employee-phone-list
    [HttpGet("employee-phone-list")]
    public async Task<ActionResult<IEnumerable<EmployeePhoneDto>>> GetEmployeePhoneList()
    {
        var result = await _db.Employees
            .OrderBy(e => e.LastName).ThenBy(e => e.FirstName)
            .Select(e => new EmployeePhoneDto
            {
                EmployeeId = e.EmployeeId,
                FullNameLNFN = (e.LastName ?? "") + ", " + (e.FirstName ?? ""),
                PrimaryPhone = e.PrimaryPhone,
                SecondaryPhone = e.SecondaryPhone
            })
            .ToListAsync();
        return Ok(result);
    }
}
