# Generated by booster-iac | 2026-04-07 15:53:19
# delete-infra.ps1 — Tears down Azure resources for a given environment
# Usage: .\delete-infra.ps1 -Environment dev [-AppName northwind2] [-Force]
# Idempotent — safe to rerun

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("dev", "staging", "prod")]
    [string]$Environment,

    [Parameter(Mandatory = $false)]
    [string]$AppName = "northwind2",

    [Parameter(Mandatory = $false)]
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$resourceGroup = "rg-$AppName-$Environment"

Write-Host "=== Deleting infrastructure for environment: $Environment ===" -ForegroundColor Cyan
Write-Host "Resource Group: $resourceGroup"

# Check if resource group exists
$rgExists = az group exists --name $resourceGroup 2>$null
if ($rgExists -ne "true") {
    Write-Host "Resource group '$resourceGroup' does not exist. Nothing to delete." -ForegroundColor Yellow
    exit 0
}

# Confirm deletion unless Force is specified
if (-not $Force) {
    Write-Host "`nWARNING: This will permanently delete ALL resources in '$resourceGroup'." -ForegroundColor Red
    $confirmation = Read-Host "Type the environment name ('$Environment') to confirm"
    if ($confirmation -ne $Environment) {
        Write-Host "Confirmation did not match. Aborting." -ForegroundColor Yellow
        exit 1
    }
}

Write-Host "`nDeleting resource group '$resourceGroup' and all contained resources..."
az group delete --name $resourceGroup --yes --no-wait --output none

Write-Host "`n=== Resource group '$resourceGroup' deletion initiated ===" -ForegroundColor Green
Write-Host "Deletion runs in the background. Use 'az group show --name $resourceGroup' to check status."
