# Generated by booster | 2026-04-07
# deploy-web.ps1 - Builds and deploys Web App to Azure App Service
# Usage: .\deploy-web.ps1 -Environment dev [-AppName northwind2]
# Requires: az CLI logged in, dotnet SDK

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("dev", "staging", "prod")]
    [string]$Environment,

    [Parameter(Mandatory = $false)]
    [string]$AppName = "northwind2"
)

$ErrorActionPreference = "Stop"

$resourceGroup = "rg-$AppName-$Environment"
$webAppName    = "app-$AppName-web-$Environment"

$repoRoot   = Resolve-Path "$PSScriptRoot\..\.."
$webProject = "$repoRoot\output\src\WebApp\WebApp.csproj"
$publishDir = "$env:TEMP\northwind-publish-$Environment"
$webOut     = "$publishDir\web"

Write-Host "=== Deploying Web App to '$Environment' ===" -ForegroundColor Cyan
Write-Host "Web App : $webAppName"

# --- Build & Publish ---
Write-Host "`n--- Building Web App ---" -ForegroundColor Yellow
dotnet publish $webProject --configuration Release --output $webOut
if ($LASTEXITCODE -ne 0) { Write-Error "Web App publish failed."; exit 1 }

# --- Zip artifact ---
$webZip = "$publishDir\web.zip"

Write-Host "`n--- Packaging artifact ---" -ForegroundColor Yellow
if (Test-Path $webZip) { Remove-Item $webZip }
Compress-Archive -Path "$webOut\*" -DestinationPath $webZip
Write-Host "Packaged: $webZip"

# --- Deploy ---
Write-Host "`n--- Deploying Web App ---" -ForegroundColor Yellow
az webapp deploy `
    --name $webAppName `
    --resource-group $resourceGroup `
    --src-path $webZip `
    --type zip `
    --async false
if ($LASTEXITCODE -ne 0) { Write-Error "Web App deployment failed."; exit 1 }
Write-Host "Web App deployed."

# --- Cleanup ---
Remove-Item $publishDir -Recurse -Force -ErrorAction SilentlyContinue

Write-Host "`n=== Web App deployment complete for '$Environment' ===" -ForegroundColor Green
Write-Host "  Web App : https://$webAppName.azurewebsites.net"
