# Generated by booster-iac | 2026-04-07 15:53:19
# deploy-infra.ps1 — Provisions Azure resources for a given environment
# Usage: .\deploy-infra.ps1 -Environment dev [-Location eastus2] [-AppServiceSku B1] [-AppName northwind2]
# Idempotent — safe to rerun

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("dev", "staging", "prod")]
    [string]$Environment,

    [Parameter(Mandatory = $false)]
    [string]$Location = "westeurope",

    [Parameter(Mandatory = $false)]
    [string]$AppServiceSku = "B1",

    [Parameter(Mandatory = $false)]
    [string]$AppName = "northwind2"
)

$ErrorActionPreference = "Stop"

# --- Naming Convention: {resourcetype}-{app}-{env} ---
$resourceGroup = "rg-$AppName-$Environment"
$appServicePlan = "plan-$AppName-$Environment"
$apiAppName = "app-$AppName-api-$Environment"
$webAppName = "app-$AppName-web-$Environment"
$sqlServerName = "sql-$AppName-$Environment"
$sqlDatabaseName = "sqldb-$AppName-$Environment"
$appInsightsName = "appi-$AppName-$Environment"
$logAnalyticsName = "log-$AppName-$Environment"

Write-Host "=== Deploying infrastructure for environment: $Environment ===" -ForegroundColor Cyan
Write-Host "Resource Group: $resourceGroup"
Write-Host "Location: $Location"

# --- Resource Group ---
Write-Host "`n--- Resource Group ---" -ForegroundColor Yellow
$rgExists = az group exists --name $resourceGroup 2>$null
if ($rgExists -eq "true") {
    Write-Host "Resource group '$resourceGroup' already exists."
} else {
    Write-Host "Creating resource group '$resourceGroup'..."
    az group create --name $resourceGroup --location $Location --output none
    Write-Host "Resource group created."
}

# --- App Service Plan (Linux, shared by both web apps) ---
Write-Host "`n--- App Service Plan ---" -ForegroundColor Yellow
$planExists = az appservice plan show --name $appServicePlan --resource-group $resourceGroup 2>$null
if ($planExists) {
    Write-Host "App Service Plan '$appServicePlan' already exists."
} else {
    Write-Host "Creating App Service Plan '$appServicePlan' (Linux, $AppServiceSku)..."
    az appservice plan create `
        --name $appServicePlan `
        --resource-group $resourceGroup `
        --location $Location `
        --sku $AppServiceSku `
        --is-linux `
        --output none
    Write-Host "App Service Plan created."
}

# --- API App (ASP.NET Core on Linux) ---
Write-Host "`n--- API App ---" -ForegroundColor Yellow
$apiAppExists = az webapp show --name $apiAppName --resource-group $resourceGroup 2>$null
if ($apiAppExists) {
    Write-Host "API App '$apiAppName' already exists."
} else {
    Write-Host "Creating API App '$apiAppName'..."
    az webapp create `
        --name $apiAppName `
        --resource-group $resourceGroup `
        --plan $appServicePlan `
        --runtime "DOTNETCORE:10.0" `
        --output none
    Write-Host "API App created."
}

# Enable system-assigned managed identity for API App
Write-Host "Ensuring managed identity is enabled for API App..."
az webapp identity assign --name $apiAppName --resource-group $resourceGroup --output none

# Configure API App settings
$connectionString = "Server=$sqlServerName.database.windows.net;Database=$sqlDatabaseName;Authentication=Active Directory Managed Identity;TrustServerCertificate=True;"
Write-Host "Configuring API App settings..."
az webapp config appsettings set `
    --name $apiAppName `
    --resource-group $resourceGroup `
    --settings `
        "ASPNETCORE_ENVIRONMENT=$Environment" `
        "DatabaseProvider=SqlServer" `
        "ConnectionStrings__DefaultConnection=$connectionString" `
        "WEBSITES_PORT=8080" `
        "DisableHttpsRedirect=true" `
    --output none

# Configure HTTPS-only and TLS 1.2
Write-Host "Configuring HTTPS-only and TLS 1.2 for API App..."
az webapp update --name $apiAppName --resource-group $resourceGroup --https-only true --output none
az webapp config set --name $apiAppName --resource-group $resourceGroup --min-tls-version 1.2 --output none

# Configure health check
Write-Host "Configuring health check for API App..."
az webapp config set `
    --name $apiAppName `
    --resource-group $resourceGroup `
    --generic-configurations '{\"healthCheckPath\": \"/health\"}' `
    --output none

# --- Web App (ASP.NET Core on Linux) ---
Write-Host "`n--- Web App ---" -ForegroundColor Yellow
$webAppExists = az webapp show --name $webAppName --resource-group $resourceGroup 2>$null
if ($webAppExists) {
    Write-Host "Web App '$webAppName' already exists."
} else {
    Write-Host "Creating Web App '$webAppName'..."
    az webapp create `
        --name $webAppName `
        --resource-group $resourceGroup `
        --plan $appServicePlan `
        --runtime "DOTNETCORE:10.0" `
        --output none
    Write-Host "Web App created."
}

# Enable system-assigned managed identity for Web App
Write-Host "Ensuring managed identity is enabled for Web App..."
az webapp identity assign --name $webAppName --resource-group $resourceGroup --output none

# Configure Web App settings
$apiBaseUrl = "https://$apiAppName.azurewebsites.net"
Write-Host "Configuring Web App settings..."
az webapp config appsettings set `
    --name $webAppName `
    --resource-group $resourceGroup `
    --settings `
        "ASPNETCORE_ENVIRONMENT=$Environment" `
        "ApiApp__BaseUrl=$apiBaseUrl" `
        "WEBSITES_PORT=8080" `
        "DisableHttpsRedirect=true" `
    --output none

# Configure HTTPS-only and TLS 1.2
Write-Host "Configuring HTTPS-only and TLS 1.2 for Web App..."
az webapp update --name $webAppName --resource-group $resourceGroup --https-only true --output none
az webapp config set --name $webAppName --resource-group $resourceGroup --min-tls-version 1.2 --output none

# --- Azure SQL Server (Azure AD-only authentication) ---
Write-Host "`n--- Azure SQL Server ---" -ForegroundColor Yellow
$sqlExists = az sql server show --name $sqlServerName --resource-group $resourceGroup 2>$null
if ($sqlExists) {
    Write-Host "SQL Server '$sqlServerName' already exists."
} else {
    # Get the current signed-in user as the Azure AD admin
    # Try az ad signed-in-user first; fall back to az account show (works for guests)
    $currentUserJson = az ad signed-in-user show --query "{displayName: displayName, id: id}" --output json 2>$null
    if ($currentUserJson) {
        $currentUser = $currentUserJson | ConvertFrom-Json
    }

    if (-not $currentUser -or [string]::IsNullOrWhiteSpace($currentUser.id)) {
        Write-Host "Note: 'az ad signed-in-user show' failed. Extracting identity from access token..."
        $upn = az account show --query "user.name" --output tsv 2>$null
        # Decode the OID claim from the JWT access token (works for MSA and guest accounts)
        $rawToken = az account get-access-token --query accessToken --output tsv 2>$null
        if ($rawToken) {
            $payload = $rawToken.Split('.')[1]
            $paddingNeeded = (4 - ($payload.Length % 4)) % 4
            $payload = $payload + ('=' * $paddingNeeded)
            $decoded = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($payload)) | ConvertFrom-Json
            $objectId = $decoded.oid
        }
        if ([string]::IsNullOrWhiteSpace($objectId)) {
            Write-Error "Could not determine Azure AD object ID. Ensure you are logged in with 'az login'."
            exit 1
        }
        $currentUser = [PSCustomObject]@{ displayName = $upn; id = $objectId }
    }

    if ([string]::IsNullOrWhiteSpace($currentUser.displayName) -or [string]::IsNullOrWhiteSpace($currentUser.id)) {
        Write-Error "Could not determine signed-in user display name or object ID. Ensure you are logged in with 'az login'."
        exit 1
    }

    # Remove any ghost/broken resource entry before attempting create
    $ghostCheck = az sql server delete --name $sqlServerName --resource-group $resourceGroup --yes 2>$null
    Start-Sleep -Seconds 5

    # Try requested location first, then fallback regions if SQL is restricted there
    $sqlLocations = @($Location, "northeurope", "uksouth", "eastus", "eastus2", "westus2")
    $sqlCreated = $false
    foreach ($sqlLoc in $sqlLocations) {
        Write-Host "Creating SQL Server '$sqlServerName' in '$sqlLoc' (Azure AD-only auth) with admin '$($currentUser.displayName)'..."
        $sqlOutput = az sql server create `
            --name $sqlServerName `
            --resource-group $resourceGroup `
            --location $sqlLoc `
            --enable-ad-only-auth `
            --external-admin-principal-type User `
            --external-admin-name "$($currentUser.displayName)" `
            --external-admin-sid $currentUser.id `
            --output json 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Host "SQL Server created in '$sqlLoc' with Azure AD-only authentication."
            $sqlCreated = $true
            break
        } else {
            Write-Host "  Failed in '$sqlLoc': $($sqlOutput | Select-String 'Message:' | Select-Object -First 1)"
        }
    }
    if (-not $sqlCreated) {
        Write-Error "Could not create SQL Server in any region. Check subscription SQL quota."
        exit 1
    }
}

# Verify SQL Server exists before proceeding
$sqlCheck = az sql server show --name $sqlServerName --resource-group $resourceGroup --query name --output tsv 2>$null
if ([string]::IsNullOrWhiteSpace($sqlCheck)) {
    Write-Error "SQL Server '$sqlServerName' does not exist. Cannot continue."
    exit 1
}

# Ensure Azure AD-only auth is enabled (idempotent)
Write-Host "Ensuring Azure AD-only authentication is enabled..."
az sql server ad-only-auth enable --name $sqlServerName --resource-group $resourceGroup --output none

# Configure SQL Server TLS 1.2
Write-Host "Configuring TLS 1.2 for SQL Server..."
az sql server update --name $sqlServerName --resource-group $resourceGroup --minimal-tls-version 1.2 --output none

# Allow Azure services to access SQL Server
Write-Host "Configuring firewall to allow Azure services..."
az sql server firewall-rule create `
    --server $sqlServerName `
    --resource-group $resourceGroup `
    --name "AllowAzureServices" `
    --start-ip-address 0.0.0.0 `
    --end-ip-address 0.0.0.0 `
    --output none 2>$null

# --- Azure SQL Database ---
Write-Host "`n--- Azure SQL Database ---" -ForegroundColor Yellow
$dbExists = az sql db show --name $sqlDatabaseName --server $sqlServerName --resource-group $resourceGroup 2>$null
if ($dbExists) {
    Write-Host "SQL Database '$sqlDatabaseName' already exists."
} else {
    Write-Host "Creating SQL Database '$sqlDatabaseName' (Basic tier)..."
    az sql db create `
        --name $sqlDatabaseName `
        --server $sqlServerName `
        --resource-group $resourceGroup `
        --edition Basic `
        --capacity 5 `
        --max-size 2GB `
        --output none
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Failed to create SQL Database '$sqlDatabaseName'."
        exit 1
    }
    Write-Host "SQL Database created."
}

# --- Grant API App managed identity access to SQL Database ---
Write-Host "`n--- Database Access ---" -ForegroundColor Yellow
Write-Host "Retrieving API App managed identity principal ID..."
$apiIdentity = az webapp identity show --name $apiAppName --resource-group $resourceGroup --query principalId --output tsv 2>$null
if ($apiIdentity) {
    Write-Host "API App principal ID: $apiIdentity"
    Write-Host "NOTE: To grant database access, run the following T-SQL as the Azure AD admin:"
    Write-Host "  CREATE USER [$apiAppName] FROM EXTERNAL PROVIDER;"
    Write-Host "  ALTER ROLE db_datareader ADD MEMBER [$apiAppName];"
    Write-Host "  ALTER ROLE db_datawriter ADD MEMBER [$apiAppName];"
    Write-Host "  ALTER ROLE db_ddladmin ADD MEMBER [$apiAppName];"
} else {
    Write-Host "WARNING: Could not retrieve API App managed identity. Ensure identity is assigned."
}

# --- Application Insights (prod only) ---
if ($Environment -eq "prod") {
    Write-Host "`n--- Application Insights (prod only) ---" -ForegroundColor Yellow

    # Create Log Analytics workspace (required for Application Insights)
    $logExists = az monitor log-analytics workspace show --workspace-name $logAnalyticsName --resource-group $resourceGroup 2>$null
    if ($logExists) {
        Write-Host "Log Analytics workspace '$logAnalyticsName' already exists."
    } else {
        Write-Host "Creating Log Analytics workspace '$logAnalyticsName'..."
        az monitor log-analytics workspace create `
            --workspace-name $logAnalyticsName `
            --resource-group $resourceGroup `
            --location $Location `
            --output none
        Write-Host "Log Analytics workspace created."
    }

    $logAnalyticsId = az monitor log-analytics workspace show `
        --workspace-name $logAnalyticsName `
        --resource-group $resourceGroup `
        --query id --output tsv

    # Create Application Insights
    $appiExists = az monitor app-insights component show --app $appInsightsName --resource-group $resourceGroup 2>$null
    if ($appiExists) {
        Write-Host "Application Insights '$appInsightsName' already exists."
    } else {
        Write-Host "Creating Application Insights '$appInsightsName'..."
        az monitor app-insights component create `
            --app $appInsightsName `
            --resource-group $resourceGroup `
            --location $Location `
            --kind web `
            --application-type web `
            --workspace $logAnalyticsId `
            --output none
        Write-Host "Application Insights created."
    }

    # Get the connection string and configure both apps
    $appiConnStr = az monitor app-insights component show `
        --app $appInsightsName `
        --resource-group $resourceGroup `
        --query connectionString --output tsv

    Write-Host "Configuring Application Insights for API App..."
    az webapp config appsettings set `
        --name $apiAppName `
        --resource-group $resourceGroup `
        --settings "APPLICATIONINSIGHTS_CONNECTION_STRING=$appiConnStr" `
        --output none

    Write-Host "Configuring Application Insights for Web App..."
    az webapp config appsettings set `
        --name $webAppName `
        --resource-group $resourceGroup `
        --settings "APPLICATIONINSIGHTS_CONNECTION_STRING=$appiConnStr" `
        --output none

    Write-Host "Application Insights configured for both apps."
} else {
    Write-Host "`n--- Application Insights skipped (not prod environment) ---" -ForegroundColor DarkGray
}

Write-Host "`n=== Infrastructure deployment complete for '$Environment' ===" -ForegroundColor Green
Write-Host "Resources:"
Write-Host "  Resource Group:    $resourceGroup"
Write-Host "  App Service Plan:  $appServicePlan"
Write-Host "  API App:           $apiAppName (https://$apiAppName.azurewebsites.net)"
Write-Host "  Web App:           $webAppName (https://$webAppName.azurewebsites.net)"
Write-Host "  SQL Server:        $sqlServerName.database.windows.net"
Write-Host "  SQL Database:      $sqlDatabaseName"
if ($Environment -eq "prod") {
    Write-Host "  App Insights:      $appInsightsName"
    Write-Host "  Log Analytics:     $logAnalyticsName"
}
