# Generated by booster | 2026-04-07
# deploy-api.ps1 - Builds and deploys API App to Azure App Service
# Usage: .\deploy-api.ps1 -Environment dev [-AppName northwind2]
# Requires: az CLI logged in, dotnet SDK

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("dev", "staging", "prod")]
    [string]$Environment,

    [Parameter(Mandatory = $false)]
    [string]$AppName = "northwind2"
)

$ErrorActionPreference = "Stop"

$resourceGroup = "rg-$AppName-$Environment"
$apiAppName    = "app-$AppName-api-$Environment"

$repoRoot   = Resolve-Path "$PSScriptRoot\..\.."
$apiProject = "$repoRoot\output\src\ApiApp\ApiApp.csproj"
$publishDir = "$env:TEMP\northwind-publish-$Environment"
$apiOut     = "$publishDir\api"

Write-Host "=== Deploying API App to '$Environment' ===" -ForegroundColor Cyan
Write-Host "API App : $apiAppName"

# --- Build & Publish ---
Write-Host "`n--- Building API App ---" -ForegroundColor Yellow
dotnet publish $apiProject --configuration Release --output $apiOut
if ($LASTEXITCODE -ne 0) { Write-Error "API App publish failed."; exit 1 }

# --- Zip artifact ---
$apiZip = "$publishDir\api.zip"

Write-Host "`n--- Packaging artifact ---" -ForegroundColor Yellow
if (Test-Path $apiZip) { Remove-Item $apiZip }
Compress-Archive -Path "$apiOut\*" -DestinationPath $apiZip
Write-Host "Packaged: $apiZip"

# --- Deploy ---
Write-Host "`n--- Deploying API App ---" -ForegroundColor Yellow
az webapp deploy `
    --name $apiAppName `
    --resource-group $resourceGroup `
    --src-path $apiZip `
    --type zip `
    --async false
if ($LASTEXITCODE -ne 0) { Write-Error "API App deployment failed."; exit 1 }
Write-Host "API App deployed."

# --- Health check ---
Write-Host "`n--- Health Check ---" -ForegroundColor Yellow
$apiUrl = "https://$apiAppName.azurewebsites.net/health"
Write-Host "Checking $apiUrl ..."
$retries = 0; $maxRetries = 10; $delay = 15
while ($retries -lt $maxRetries) {
    try {
        $r = Invoke-WebRequest -Uri $apiUrl -UseBasicParsing -TimeoutSec 10
        if ($r.StatusCode -eq 200) { Write-Host "API App is healthy." -ForegroundColor Green; break }
    } catch {}
    Write-Host "  Attempt $($retries+1)/$maxRetries - waiting ${delay}s..."
    Start-Sleep -Seconds $delay
    $retries++
}
if ($retries -eq $maxRetries) {
    Write-Host "WARNING: Health check did not return 200 - app may still be starting up." -ForegroundColor Yellow
}

# --- Cleanup ---
Remove-Item $publishDir -Recurse -Force -ErrorAction SilentlyContinue

Write-Host "`n=== API App deployment complete for '$Environment' ===" -ForegroundColor Green
Write-Host "  API App : https://$apiAppName.azurewebsites.net"
