# Generated by booster-iac | 2026-04-07 15:53:19
# grant-db-access.ps1 — Grants managed identity access to Azure SQL Database
# Usage: .\grant-db-access.ps1 -Environment dev [-AppName northwind2]
# Idempotent — safe to rerun
# Requires: SqlServer PowerShell module or sqlcmd with Azure AD auth

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("dev", "staging", "prod")]
    [string]$Environment,

    [Parameter(Mandatory = $false)]
    [string]$AppName = "northwind2"
)

$ErrorActionPreference = "Stop"

$resourceGroup = "rg-$AppName-$Environment"
$sqlServerName = "sql-$AppName-$Environment"
$sqlDatabaseName = "sqldb-$AppName-$Environment"
$apiAppName = "app-$AppName-api-$Environment"

Write-Host "=== Granting database access for '$Environment' ===" -ForegroundColor Cyan

# Get an access token for Azure SQL using the current signed-in user
Write-Host "Acquiring access token for Azure SQL..."
$accessToken = az account get-access-token --resource https://database.windows.net/ --query accessToken --output tsv

if (-not $accessToken) {
    Write-Host "ERROR: Could not acquire access token. Ensure you are signed in with 'az login'." -ForegroundColor Red
    exit 1
}

$sqlServer = "$sqlServerName.database.windows.net"

# T-SQL to create user from external provider and grant roles (idempotent)
$tsql = @"
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = '$apiAppName')
BEGIN
    CREATE USER [$apiAppName] FROM EXTERNAL PROVIDER;
END

IF IS_ROLEMEMBER('db_datareader', '$apiAppName') = 0
    ALTER ROLE db_datareader ADD MEMBER [$apiAppName];

IF IS_ROLEMEMBER('db_datawriter', '$apiAppName') = 0
    ALTER ROLE db_datawriter ADD MEMBER [$apiAppName];

IF IS_ROLEMEMBER('db_ddladmin', '$apiAppName') = 0
    ALTER ROLE db_ddladmin ADD MEMBER [$apiAppName];

PRINT 'Database access granted for $apiAppName';
"@

Write-Host "Granting database access to '$apiAppName' on '$sqlDatabaseName'..."
Write-Host "Server: $sqlServer"

# Execute using Invoke-Sqlcmd with -AccessToken (SqlServer module v22+)
try {
    Import-Module SqlServer -ErrorAction Stop
    Invoke-Sqlcmd -ServerInstance $sqlServer -Database $sqlDatabaseName -AccessToken $accessToken -Query $tsql -ErrorAction Stop
    Write-Host "`n=== Database access granted successfully ===" -ForegroundColor Green
} catch {
    Write-Host "`nNote: Invoke-Sqlcmd failed: $_" -ForegroundColor Yellow
    Write-Host "You can run the following T-SQL manually:" -ForegroundColor Yellow
    Write-Host $tsql
    Write-Host "`nConnect to: $sqlServer, Database: $sqlDatabaseName" -ForegroundColor Yellow
    Write-Host "Use Azure AD authentication as the SQL Server admin." -ForegroundColor Yellow
}
