// Generated by booster-apidev | 2026-04-06 19:37:30

using System.ComponentModel.DataAnnotations;

namespace ApiApp.DTOs.Orders;

public class OrderStatusPatchDto
{
    [Required]
    public string Status { get; set; } = string.Empty;
}
