// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.DTOs.Orders;

public class OrderStatusPatchResponseDto
{
    public int Id { get; set; }
    public string? Status { get; set; }
    public string? StatusDisplay { get; set; }
    public DateTime? ModifiedOn { get; set; }
}
