// Generated by booster-apidev | 2026-04-06 19:37:30

using ApiApp.DTOs.OrderDetails;

namespace ApiApp.DTOs.Orders;

public class OrderDetailDto
{
    public int Id { get; set; }
    public int? CustomerId { get; set; }
    public string? CustomerName { get; set; }
    public int? EmployeeId { get; set; }
    public string? EmployeeFullName { get; set; }
    public DateTime? OrderDate { get; set; }
    public DateTime? ShippedDate { get; set; }
    public DateTime? PaidDate { get; set; }
    public string? Status { get; set; }
    public string? StatusDisplay { get; set; }
    public string? Notes { get; set; }
    public decimal OrderTotal { get; set; }
    public List<OrderDetailItemDto> OrderDetails { get; set; } = new();
    public string? AddedBy { get; set; }
    public DateTime? AddedOn { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }
}
