// > Generated by booster-webdev | 2026-04-07 12:29:26
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers;

[Route("admin")]
public class AdminController : Controller
{
    private readonly NorthwindApiService _api;

    public AdminController(NorthwindApiService api)
    {
        _api = api;
    }

    // GET /admin
    [HttpGet("")]
    public async Task<IActionResult> Index()
    {
        var settings = await _api.GetSettingsAsync();
        ViewBag.Settings = settings ?? [];
        return View();
    }

    // GET /admin/settings
    [HttpGet("settings")]
    public async Task<IActionResult> Settings()
    {
        var settings = await _api.GetSettingsAsync();
        return View(settings ?? []);
    }

    // POST /admin/settings/save/{id}
    [HttpPost("settings/save/{id:int}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SaveSetting(int id, string? settingValue)
    {
        await _api.UpdateSettingAsync(id, new SystemSettingUpdateRequest { SettingValue = settingValue });
        TempData["Success"] = "Setting saved.";
        return RedirectToAction(nameof(Settings));
    }

    // POST /admin/generate-orders
    [HttpPost("generate-orders")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> GenerateOrders(int count)
    {
        var result = await _api.GenerateOrdersAsync(count);
        TempData["Success"] = $"{result?.OrdersCreated ?? 0} orders generated.";
        return RedirectToAction(nameof(Index));
    }

    // POST /admin/delete-test-data
    [HttpPost("delete-test-data")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteTestData()
    {
        await _api.DeleteTestDataAsync();
        TempData["Success"] = "Test data deleted.";
        return RedirectToAction(nameof(Index));
    }
}
