// Generated by booster-webdev | 2026-04-06
using Microsoft.AspNetCore.Mvc;
using WebApp.Services;

namespace WebApp.Controllers;

public class AdminController : Controller
{
    private readonly ApiClient _api;
    public AdminController(ApiClient api) => _api = api;

    // GET /admin
    public async Task<IActionResult> Index()
    {
        var settings = await _api.GetSettingsAsync();
        ViewBag.Settings = settings ?? new();
        return View();
    }

    // POST /admin/settings/{id}
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> UpdateSetting(int id, string settingValue)
    {
        await _api.UpdateSettingAsync(id, settingValue);
        TempData["Success"] = "Setting updated.";
        return RedirectToAction("Index");
    }

    // POST /admin/generate-orders
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> GenerateOrders(int count)
    {
        var result = await _api.GenerateOrdersAsync(count);
        TempData["Success"] = $"{result?.OrdersCreated ?? 0} orders generated.";
        return RedirectToAction("Index");
    }

    // POST /admin/delete-test-data
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteTestData()
    {
        var result = await _api.DeleteTestDataAsync();
        if (result != null)
            TempData["Success"] = $"Deleted: {result.CustomersDeleted} customers, {result.EmployeesDeleted} employees, {result.OrdersDeleted} orders, {result.ProductsDeleted} products.";
        return RedirectToAction("Index");
    }
}
