// Generated by booster-webdev | 2026-04-06
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers;

public class CustomersController : Controller
{
    private readonly ApiClient _api;
    public CustomersController(ApiClient api) => _api = api;

    // GET /customers
    public async Task<IActionResult> Index(string? search, bool activeOnly = false, int page = 1)
    {
        var result = await _api.GetCustomersAsync(search, activeOnly, page);
        ViewBag.Search = search;
        ViewBag.ActiveOnly = activeOnly;
        return View(result);
    }

    // GET /customers/new
    public IActionResult New() => View(new CustomerFormData());

    // POST /customers/new
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> New(CustomerFormData form)
    {
        if (!ModelState.IsValid) return View(form);
        var created = await _api.CreateCustomerAsync(form);
        if (created == null) { ModelState.AddModelError("", "Failed to create customer."); return View(form); }
        return RedirectToAction("Detail", new { id = created.Id });
    }

    // GET /customers/{id}
    public async Task<IActionResult> Detail(int id)
    {
        var customer = await _api.GetCustomerAsync(id);
        if (customer == null) return NotFound();
        var orders = await _api.GetCustomerOrdersAsync(id);
        var products = await _api.GetCustomerProductsAsync(id);
        ViewBag.Orders = orders?.Items ?? new();
        ViewBag.Products = products ?? new();
        return View(customer);
    }

    // POST /customers/{id}
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Detail(int id, CustomerFormData form)
    {
        if (!ModelState.IsValid)
        {
            var c = await _api.GetCustomerAsync(id);
            if (c == null) return NotFound();
            var orders = await _api.GetCustomerOrdersAsync(id);
            var products = await _api.GetCustomerProductsAsync(id);
            ViewBag.Orders = orders?.Items ?? new();
            ViewBag.Products = products ?? new();
            return View(new CustomerDetail
            {
                Id = c.Id,
                CustomerName = form.CustomerName,
                PrimaryContactFirstName = form.PrimaryContactFirstName,
                PrimaryContactLastName = form.PrimaryContactLastName,
                PrimaryContactJobTitle = form.PrimaryContactJobTitle,
                PrimaryContactEmailAddress = form.PrimaryContactEmailAddress,
                BusinessPhone = form.BusinessPhone,
                Address = form.Address,
                City = form.City,
                State = form.State,
                Zip = form.Zip,
                Website = form.Website,
                Notes = form.Notes
            });
        }
        var updated = await _api.UpdateCustomerAsync(id, form);
        if (updated == null) { ModelState.AddModelError("", "Failed to update customer."); return View(form); }
        TempData["Success"] = "Customer updated.";
        return RedirectToAction("Detail", new { id });
    }

    // POST /customers/{id}/delete
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        await _api.DeleteCustomerAsync(id);
        return RedirectToAction("Index");
    }
}
