// > Generated by booster-webdev | 2026-04-07 12:29:26
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers;

[Route("customers")]
public class CustomersController : Controller
{
    private readonly NorthwindApiService _api;

    public CustomersController(NorthwindApiService api)
    {
        _api = api;
    }

    // GET /customers
    [HttpGet("")]
    public async Task<IActionResult> Index(string? search)
    {
        ViewBag.Search = search;
        var customers = await _api.GetCustomersAsync(search);
        return View(customers ?? []);
    }

    // GET /customers/create
    [HttpGet("create")]
    public IActionResult Create() => View(new CustomerRequest());

    // POST /customers/create
    [HttpPost("create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CustomerRequest req)
    {
        var created = await _api.CreateCustomerAsync(req);
        if (created == null) return View(req);
        return RedirectToAction(nameof(Detail), new { id = created.CustomerId });
    }

    // GET /customers/{id}
    [HttpGet("{id:int}")]
    public async Task<IActionResult> Detail(int id)
    {
        var customer = await _api.GetCustomerAsync(id);
        if (customer == null) return NotFound();
        var orders = await _api.GetCustomerOrdersAsync(id);
        var products = await _api.GetCustomerProductsAsync(id);
        ViewBag.Orders = orders ?? [];
        ViewBag.Products = products ?? [];
        return View(customer);
    }

    // POST /customers/{id} (edit)
    [HttpPost("{id:int}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Detail(int id, CustomerRequest req)
    {
        await _api.UpdateCustomerAsync(id, req);
        TempData["Success"] = "Customer saved.";
        return RedirectToAction(nameof(Detail), new { id });
    }

    // POST /customers/{id}/delete
    [HttpPost("{id:int}/delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        await _api.DeleteCustomerAsync(id);
        return RedirectToAction(nameof(Index));
    }
}
