// > Generated by booster-webdev | 2026-04-07 12:29:26
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers;

[Route("employees")]
public class EmployeesController : Controller
{
    private readonly NorthwindApiService _api;

    public EmployeesController(NorthwindApiService api)
    {
        _api = api;
    }

    // GET /employees
    [HttpGet("")]
    public async Task<IActionResult> Index()
    {
        var employees = await _api.GetEmployeesAsync();
        return View(employees ?? []);
    }

    // GET /employees/create
    [HttpGet("create")]
    public IActionResult Create() => View(new EmployeeRequest());

    // POST /employees/create
    [HttpPost("create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(EmployeeRequest req)
    {
        var created = await _api.CreateEmployeeAsync(req);
        if (created == null) return View(req);
        return RedirectToAction(nameof(Detail), new { id = created.EmployeeId });
    }

    // GET /employees/{id}
    [HttpGet("{id:int}")]
    public async Task<IActionResult> Detail(int id)
    {
        var employee = await _api.GetEmployeeAsync(id);
        if (employee == null) return NotFound();
        var orders = await _api.GetEmployeeOrdersAsync(id);
        ViewBag.Orders = orders ?? [];
        return View(employee);
    }

    // POST /employees/{id} (edit)
    [HttpPost("{id:int}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Detail(int id, EmployeeRequest req)
    {
        await _api.UpdateEmployeeAsync(id, req);
        TempData["Success"] = "Employee saved.";
        return RedirectToAction(nameof(Detail), new { id });
    }

    // POST /employees/{id}/delete
    [HttpPost("{id:int}/delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        await _api.DeleteEmployeeAsync(id);
        return RedirectToAction(nameof(Index));
    }
}
