// Generated by booster-webdev | 2026-04-06
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers;

public class EmployeesController : Controller
{
    private readonly ApiClient _api;
    public EmployeesController(ApiClient api) => _api = api;

    // GET /employees
    public async Task<IActionResult> Index(string? search, int page = 1)
    {
        var result = await _api.GetEmployeesAsync(search, page);
        ViewBag.Search = search;
        return View(result);
    }

    // GET /employees/new
    public IActionResult New() => View(new EmployeeFormData());

    // POST /employees/new
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> New(EmployeeFormData form)
    {
        if (!ModelState.IsValid) return View(form);
        var created = await _api.CreateEmployeeAsync(form);
        if (created == null) { ModelState.AddModelError("", "Failed to create employee."); return View(form); }
        return RedirectToAction("Detail", new { id = created.Id });
    }

    // GET /employees/{id}
    public async Task<IActionResult> Detail(int id)
    {
        var emp = await _api.GetEmployeeAsync(id);
        if (emp == null) return NotFound();
        var orders = await _api.GetEmployeeOrdersAsync(id);
        ViewBag.Orders = orders?.Items ?? new();
        return View(emp);
    }

    // POST /employees/{id}
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Detail(int id, EmployeeFormData form)
    {
        if (!ModelState.IsValid)
        {
            var emp = await _api.GetEmployeeAsync(id);
            var orders = await _api.GetEmployeeOrdersAsync(id);
            ViewBag.Orders = orders?.Items ?? new();
            return View(emp ?? new EmployeeDetail { Id = id });
        }
        var updated = await _api.UpdateEmployeeAsync(id, form);
        if (updated == null) { ModelState.AddModelError("", "Failed to update employee."); return View(form); }
        TempData["Success"] = "Employee updated.";
        return RedirectToAction("Detail", new { id });
    }

    // POST /employees/{id}/delete
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        await _api.DeleteEmployeeAsync(id);
        return RedirectToAction("Index");
    }
}
