// Generated by booster-webdev | 2026-04-06
using Microsoft.AspNetCore.Mvc;
using WebApp.Services;

namespace WebApp.Controllers;

public class HomeController : Controller
{
    private readonly ApiClient _api;

    public HomeController(ApiClient api) => _api = api;

    public async Task<IActionResult> Index()
    {
        var ytdTask = _api.GetSalesYtdAsync();
        var empSalesTask = _api.GetSalesByEmployeeAsync();
        var recentOrdersTask = _api.GetOrdersAsync(sortBy: "orderDate", top: 20);
        var productsTask = _api.GetProductsAsync(includeSalesStats: true, pageSize: 10);

        await Task.WhenAll(ytdTask, empSalesTask, recentOrdersTask, productsTask);

        ViewBag.YtdSales = ytdTask.Result;
        ViewBag.SalesByEmployee = empSalesTask.Result ?? new();
        ViewBag.RecentOrders = recentOrdersTask.Result?.Items ?? new();
        ViewBag.TopProducts = productsTask.Result?.Items ?? new();

        return View();
    }
}

