// > Generated by booster-webdev | 2026-04-07 12:29:26
using Microsoft.AspNetCore.Mvc;
using WebApp.Services;

namespace WebApp.Controllers;

[Route("")]
public class HomeController : Controller
{
    private readonly NorthwindApiService _api;

    public HomeController(NorthwindApiService api)
    {
        _api = api;
    }

    [HttpGet("")]
    public async Task<IActionResult> Index()
    {
        var ytd = await _api.GetSalesYtdAsync();
        var byEmployee = await _api.GetSalesByEmployeeAsync();
        var recentOrders = await _api.GetOrdersAsync(top: 20);

        ViewBag.Ytd = ytd;
        ViewBag.ByEmployee = byEmployee ?? [];
        ViewBag.RecentOrders = recentOrders ?? [];
        return View();
    }
}
