// > Generated by booster-webdev | 2026-04-07 12:29:26
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers;

[Route("orders")]
public class OrdersController : Controller
{
    private readonly NorthwindApiService _api;

    public OrdersController(NorthwindApiService api)
    {
        _api = api;
    }

    // GET /orders
    [HttpGet("")]
    public async Task<IActionResult> Index(int? customerId, int? employeeId, int? statusId, string? orderDate)
    {
        var orders = await _api.GetOrdersAsync(customerId, employeeId, statusId, orderDate);
        var customers = await _api.GetCustomerLookupAsync();
        var employees = await _api.GetEmployeeLookupAsync();
        var statuses = await _api.GetOrderStatusesAsync();

        ViewBag.Customers = customers ?? [];
        ViewBag.Employees = employees ?? [];
        ViewBag.Statuses = statuses ?? [];
        ViewBag.FilterCustomerId = customerId;
        ViewBag.FilterEmployeeId = employeeId;
        ViewBag.FilterStatusId = statusId;
        ViewBag.FilterOrderDate = orderDate;

        return View(orders ?? []);
    }

    // GET /orders/create
    [HttpGet("create")]
    public async Task<IActionResult> Create()
    {
        var customers = await _api.GetCustomerLookupAsync();
        var employees = await _api.GetEmployeeLookupAsync();
        var statuses = await _api.GetOrderStatusesAsync();
        ViewBag.Customers = customers ?? [];
        ViewBag.Employees = employees ?? [];
        ViewBag.Statuses = statuses ?? [];
        return View(new OrderRequest { OrderDate = DateTime.Today });
    }

    // POST /orders/create
    [HttpPost("create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(OrderRequest req)
    {
        var created = await _api.CreateOrderAsync(req);
        if (created == null)
        {
            var customers = await _api.GetCustomerLookupAsync();
            var employees = await _api.GetEmployeeLookupAsync();
            var statuses = await _api.GetOrderStatusesAsync();
            ViewBag.Customers = customers ?? [];
            ViewBag.Employees = employees ?? [];
            ViewBag.Statuses = statuses ?? [];
            return View(req);
        }
        return RedirectToAction(nameof(Detail), new { id = created.OrderId });
    }

    // GET /orders/{id}
    [HttpGet("{id:int}")]
    public async Task<IActionResult> Detail(int id)
    {
        var order = await _api.GetOrderAsync(id);
        if (order == null) return NotFound();

        var customers = await _api.GetCustomerLookupAsync();
        var employees = await _api.GetEmployeeLookupAsync();
        var statuses = await _api.GetOrderStatusesAsync();
        var products = await _api.GetProductLookupAsync();

        ViewBag.Customers = customers ?? [];
        ViewBag.Employees = employees ?? [];
        ViewBag.Statuses = statuses ?? [];
        ViewBag.Products = products ?? [];

        return View(order);
    }

    // POST /orders/{id} (save header)
    [HttpPost("{id:int}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Detail(int id, OrderRequest req)
    {
        await _api.UpdateOrderAsync(id, req);
        TempData["Success"] = "Order saved.";
        return RedirectToAction(nameof(Detail), new { id });
    }

    // POST /orders/{id}/delete
    [HttpPost("{id:int}/delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        await _api.DeleteOrderAsync(id);
        return RedirectToAction(nameof(Index));
    }

    // GET /orders/{id}/invoice
    [HttpGet("{id:int}/invoice")]
    public async Task<IActionResult> Invoice(int id)
    {
        var invoice = await _api.GetInvoiceAsync(id);
        if (invoice == null) return NotFound();
        return View(invoice);
    }

    // POST /orders/{id}/adddetail
    [HttpPost("{id:int}/adddetail")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddDetail(int id, OrderLineRequest req)
    {
        await _api.AddOrderDetailAsync(id, req);
        return RedirectToAction(nameof(Detail), new { id });
    }

    // POST /orders/{id}/updatedetail/{detailId}
    [HttpPost("{id:int}/updatedetail/{detailId:int}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> UpdateDetail(int id, int detailId, OrderLineRequest req)
    {
        await _api.UpdateOrderDetailAsync(id, detailId, req);
        return RedirectToAction(nameof(Detail), new { id });
    }

    // POST /orders/{id}/deletedetail/{detailId}
    [HttpPost("{id:int}/deletedetail/{detailId:int}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteDetail(int id, int detailId)
    {
        await _api.DeleteOrderDetailAsync(id, detailId);
        return RedirectToAction(nameof(Detail), new { id });
    }
}
