// Generated by booster-webdev | 2026-04-06
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers;

public class OrdersController : Controller
{
    private readonly ApiClient _api;
    public OrdersController(ApiClient api) => _api = api;

    // GET /orders
    public async Task<IActionResult> Index(int? customerId, int? employeeId, string? status,
        string? sortBy, int page = 1)
    {
        var ordersTask = _api.GetOrdersAsync(customerId, employeeId, status, sortBy, page: page);
        var custTask = _api.GetLookupCustomersAsync();
        var empTask = _api.GetLookupEmployeesAsync();
        var statusTask = _api.GetLookupOrderStatusesAsync();
        await Task.WhenAll(ordersTask, custTask, empTask, statusTask);

        ViewBag.Customers = custTask.Result ?? new();
        ViewBag.Employees = empTask.Result ?? new();
        ViewBag.Statuses = statusTask.Result ?? new();
        ViewBag.CustomerIdFilter = customerId;
        ViewBag.EmployeeIdFilter = employeeId;
        ViewBag.StatusFilter = status;
        ViewBag.SortBy = sortBy;
        return View(ordersTask.Result);
    }

    // GET /orders/new
    public async Task<IActionResult> New()
    {
        var custTask = _api.GetLookupCustomersAsync();
        var empTask = _api.GetLookupEmployeesAsync();
        var statusTask = _api.GetLookupOrderStatusesAsync();
        await Task.WhenAll(custTask, empTask, statusTask);
        ViewBag.Customers = custTask.Result ?? new();
        ViewBag.Employees = empTask.Result ?? new();
        ViewBag.Statuses = statusTask.Result ?? new();
        return View(new OrderFormData { OrderDate = DateTime.Today, Status = "New" });
    }

    // POST /orders/new
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> New(OrderFormData form)
    {
        var created = await _api.CreateOrderAsync(form);
        if (created == null)
        {
            var custTask = _api.GetLookupCustomersAsync();
            var empTask = _api.GetLookupEmployeesAsync();
            var statusTask = _api.GetLookupOrderStatusesAsync();
            await Task.WhenAll(custTask, empTask, statusTask);
            ViewBag.Customers = custTask.Result ?? new();
            ViewBag.Employees = empTask.Result ?? new();
            ViewBag.Statuses = statusTask.Result ?? new();
            ModelState.AddModelError("", "Failed to create order.");
            return View(form);
        }
        return RedirectToAction("Detail", new { id = created.Id });
    }

    // GET /orders/{id}
    public async Task<IActionResult> Detail(int id)
    {
        var orderTask = _api.GetOrderAsync(id);
        var custTask = _api.GetLookupCustomersAsync();
        var empTask = _api.GetLookupEmployeesAsync();
        var statusTask = _api.GetLookupOrderStatusesAsync();
        var prodTask = _api.GetLookupProductsAsync();
        await Task.WhenAll(orderTask, custTask, empTask, statusTask, prodTask);

        var order = orderTask.Result;
        if (order == null) return NotFound();

        // Side panel: recent orders for same customer
        if (order.CustomerId.HasValue)
        {
            var recent = await _api.GetCustomerOrdersAsync(order.CustomerId.Value, top: 20);
            ViewBag.RecentOrders = recent?.Items?.Where(o => o.Id != id).ToList() ?? new();
        }
        else
        {
            ViewBag.RecentOrders = new List<OrderListItem>();
        }

        ViewBag.Customers = custTask.Result ?? new();
        ViewBag.Employees = empTask.Result ?? new();
        ViewBag.Statuses = statusTask.Result ?? new();
        ViewBag.Products = prodTask.Result ?? new();
        return View(order);
    }

    // POST /orders/{id}
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Detail(int id, OrderFormData form)
    {
        var updated = await _api.UpdateOrderAsync(id, form);
        if (updated == null) { TempData["Error"] = "Failed to update order."; }
        else { TempData["Success"] = "Order updated."; }
        return RedirectToAction("Detail", new { id });
    }

    // POST /orders/{id}/delete
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        await _api.DeleteOrderAsync(id);
        return RedirectToAction("Index");
    }

    // POST /orders/{id}/status
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> UpdateStatus(int id, string status)
    {
        await _api.PatchOrderStatusAsync(id, status);
        return RedirectToAction("Detail", new { id });
    }

    // POST /orders/{id}/lines
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> AddLine(int id, int productId, int quantity, decimal unitPrice)
    {
        await _api.AddOrderLineAsync(id, new OrderLineFormData { ProductId = productId, Quantity = quantity, UnitPrice = unitPrice });
        return RedirectToAction("Detail", new { id });
    }

    // POST /orders/{id}/lines/{lineId}/delete
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteLine(int id, int lineId)
    {
        await _api.DeleteOrderLineAsync(id, lineId);
        return RedirectToAction("Detail", new { id });
    }

    // POST /orders/{id}/lines/{lineId}/edit
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> EditLine(int id, int lineId, int productId, int quantity, decimal unitPrice)
    {
        await _api.UpdateOrderLineAsync(id, lineId, new OrderLineFormData { ProductId = productId, Quantity = quantity, UnitPrice = unitPrice });
        return RedirectToAction("Detail", new { id });
    }
}
