// > Generated by booster-webdev | 2026-04-07 12:29:26
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers;

[Route("products")]
public class ProductsController : Controller
{
    private readonly NorthwindApiService _api;

    public ProductsController(NorthwindApiService api)
    {
        _api = api;
    }

    // GET /products
    [HttpGet("")]
    public async Task<IActionResult> Index(string? search)
    {
        ViewBag.Search = search;
        var products = await _api.GetProductsAsync(search);
        return View(products ?? []);
    }

    // GET /products/create
    [HttpGet("create")]
    public IActionResult Create() => View(new ProductRequest());

    // POST /products/create
    [HttpPost("create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ProductRequest req)
    {
        var created = await _api.CreateProductAsync(req);
        if (created == null) return View(req);
        return RedirectToAction(nameof(Detail), new { id = created.ProductId });
    }

    // GET /products/{id}
    [HttpGet("{id:int}")]
    public async Task<IActionResult> Detail(int id)
    {
        var product = await _api.GetProductAsync(id);
        if (product == null) return NotFound();
        var orders = await _api.GetProductOrdersAsync(id);
        ViewBag.Orders = orders ?? [];
        return View(product);
    }

    // POST /products/{id} (edit)
    [HttpPost("{id:int}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Detail(int id, ProductRequest req)
    {
        await _api.UpdateProductAsync(id, req);
        TempData["Success"] = "Product saved.";
        return RedirectToAction(nameof(Detail), new { id });
    }

    // POST /products/{id}/delete
    [HttpPost("{id:int}/delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        await _api.DeleteProductAsync(id);
        return RedirectToAction(nameof(Index));
    }
}
