// Generated by booster-webdev | 2026-04-06
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers;

public class ProductsController : Controller
{
    private readonly ApiClient _api;
    public ProductsController(ApiClient api) => _api = api;

    // GET /products
    public async Task<IActionResult> Index(string? search, int page = 1)
    {
        var result = await _api.GetProductsAsync(search, includeSalesStats: true, page: page);
        ViewBag.Search = search;
        return View(result);
    }

    // GET /products/new
    public IActionResult New() => View(new ProductFormData());

    // POST /products/new
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> New(ProductFormData form)
    {
        if (!ModelState.IsValid) return View(form);
        var created = await _api.CreateProductAsync(form);
        if (created == null) { ModelState.AddModelError("", "Failed to create product. Check that the Product Code is unique."); return View(form); }
        return RedirectToAction("Detail", new { id = created.Id });
    }

    // GET /products/{id}
    public async Task<IActionResult> Detail(int id)
    {
        var product = await _api.GetProductAsync(id);
        if (product == null) return NotFound();
        var orders = await _api.GetProductOrdersAsync(id);
        ViewBag.Orders = orders ?? new();
        return View(product);
    }

    // POST /products/{id}
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Detail(int id, ProductFormData form)
    {
        if (!ModelState.IsValid)
        {
            var product = await _api.GetProductAsync(id);
            var orders = await _api.GetProductOrdersAsync(id);
            ViewBag.Orders = orders ?? new();
            return View(product ?? new ProductDetail { Id = id });
        }
        var updated = await _api.UpdateProductAsync(id, form);
        if (updated == null) { ModelState.AddModelError("", "Failed to update product."); return View(form); }
        TempData["Success"] = "Product updated.";
        return RedirectToAction("Detail", new { id });
    }

    // POST /products/{id}/delete
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        var ok = await _api.DeleteProductAsync(id);
        if (!ok) TempData["Error"] = "Cannot delete product - it has existing order history.";
        return RedirectToAction("Index");
    }
}
