// Generated by booster-webdev | 2026-04-06
using Microsoft.AspNetCore.Mvc;
using WebApp.Services;

namespace WebApp.Controllers;

public class ReportsController : Controller
{
    private readonly ApiClient _api;
    public ReportsController(ApiClient api) => _api = api;

    // GET /reports
    public IActionResult Index() => View();

    // GET /reports/invoice/{orderId}
    public async Task<IActionResult> Invoice(int orderId)
    {
        var invoice = await _api.GetInvoiceAsync(orderId);
        if (invoice == null) return NotFound();
        return View(invoice);
    }

    // GET /reports/sales-by-employee
    public async Task<IActionResult> SalesByEmployee(int? year)
    {
        year ??= DateTime.UtcNow.Year;
        var data = await _api.GetSalesByEmployeeAsync(year, "month");
        ViewBag.Year = year;
        return View(data ?? new());
    }

    // GET /reports/sales-by-product
    public async Task<IActionResult> SalesByProduct(int? year, string groupBy = "month")
    {
        year ??= DateTime.UtcNow.Year;
        var data = await _api.GetSalesByProductAsync(year, groupBy);
        ViewBag.Year = year;
        ViewBag.GroupBy = groupBy;
        return View(data ?? new());
    }

    // GET /reports/employee-email-list
    public async Task<IActionResult> EmployeeEmailList()
    {
        var data = await _api.GetEmployeeEmailListAsync();
        return View(data ?? new());
    }

    // GET /reports/employee-phone-list
    public async Task<IActionResult> EmployeePhoneList()
    {
        var data = await _api.GetEmployeePhoneListAsync();
        return View(data ?? new());
    }
}
