// > Generated by booster-webdev | 2026-04-07 12:29:26
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers;

[Route("reports")]
public class ReportsController : Controller
{
    private readonly NorthwindApiService _api;

    public ReportsController(NorthwindApiService api)
    {
        _api = api;
    }

    // GET /reports
    [HttpGet("")]
    public IActionResult Index()
    {
        ViewBag.DefaultFrom = new DateTime(DateTime.Today.Year, 1, 1).ToString("yyyy-MM-dd");
        ViewBag.DefaultTo = DateTime.Today.ToString("yyyy-MM-dd");
        return View();
    }

    // GET /reports/sales-by-product
    [HttpGet("sales-by-product")]
    public async Task<IActionResult> SalesByProduct(string? from, string? to)
    {
        ViewBag.From = from ?? new DateTime(DateTime.Today.Year, 1, 1).ToString("yyyy-MM-dd");
        ViewBag.To = to ?? DateTime.Today.ToString("yyyy-MM-dd");
        string fromStr = ViewBag.From;
        string toStr = ViewBag.To;
        var data = await _api.GetSalesByProductAsync(fromStr, toStr);
        return View(data ?? new List<SalesByProductDto>());
    }

    // GET /reports/sales-by-product-quarterly
    [HttpGet("sales-by-product-quarterly")]
    public async Task<IActionResult> SalesByProductQuarterly(string? from, string? to)
    {
        ViewBag.From = from ?? new DateTime(DateTime.Today.Year, 1, 1).ToString("yyyy-MM-dd");
        ViewBag.To = to ?? DateTime.Today.ToString("yyyy-MM-dd");
        string fromStr = ViewBag.From;
        string toStr = ViewBag.To;
        var data = await _api.GetSalesByProductQuarterlyAsync(fromStr, toStr);
        return View(data ?? new List<SalesByProductQuarterlyDto>());
    }

    // GET /reports/sales-by-employee
    [HttpGet("sales-by-employee")]
    public async Task<IActionResult> SalesByEmployee(string? from, string? to)
    {
        ViewBag.From = from ?? new DateTime(DateTime.Today.Year, 1, 1).ToString("yyyy-MM-dd");
        ViewBag.To = to ?? DateTime.Today.ToString("yyyy-MM-dd");
        string fromStr = ViewBag.From;
        string toStr = ViewBag.To;
        var data = await _api.GetSalesByEmployeeMonthlyAsync(fromStr, toStr);
        return View(data ?? new List<SalesByEmployeeMonthlyDto>());
    }

    // GET /reports/employee-email-list
    [HttpGet("employee-email-list")]
    public async Task<IActionResult> EmployeeEmailList()
    {
        var data = await _api.GetEmployeeEmailListAsync();
        return View(data ?? []);
    }

    // GET /reports/employee-phone-list
    [HttpGet("employee-phone-list")]
    public async Task<IActionResult> EmployeePhoneList()
    {
        var data = await _api.GetEmployeePhoneListAsync();
        return View(data ?? []);
    }
}
