// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.DTOs.Employees;

public class EmployeeCreateUpdateDto
{
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? EmailAddress { get; set; }
    public string? JobTitle { get; set; }
    public string? PrimaryPhone { get; set; }
    public string? SecondaryPhone { get; set; }
    public string? Title { get; set; }
    public string? Notes { get; set; }
    public string? WindowsUserName { get; set; }
}
