// Generated by booster-apidev | 2026-04-06 19:37:30

using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using ApiApp.DTOs.Admin;
using ApiApp.DTOs.Products;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class AdminControllerTests
{
    private CustomWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNameCaseInsensitive = true };

    [SetUp]
    public void SetUp()
    {
        _factory = new CustomWebApplicationFactory();
        _client = _factory.CreateClient();
    }

    [TearDown]
    public void TearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    [Test]
    public async Task GetSettings_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/admin/settings");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var settings = await response.Content.ReadFromJsonAsync<List<SystemSettingDto>>(JsonOpts);
        Assert.That(settings, Is.Not.Null);
        // Seeded data includes TaxRate
        Assert.That(settings!.Any(s => s.SettingName == "TaxRate"), Is.True);
    }

    [Test]
    public async Task UpdateSetting_ReturnsUpdated()
    {
        var settingsResp = await _client.GetAsync("/api/admin/settings");
        var settings = await settingsResp.Content.ReadFromJsonAsync<List<SystemSettingDto>>(JsonOpts);
        var taxSetting = settings!.First(s => s.SettingName == "TaxRate");

        var dto = new UpdateSettingDto { SettingValue = "90" };
        var updateResp = await _client.PutAsJsonAsync($"/api/admin/settings/{taxSetting.Id}", dto);
        Assert.That(updateResp.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var updated = await updateResp.Content.ReadFromJsonAsync<SystemSettingDto>(JsonOpts);
        Assert.That(updated!.SettingValue, Is.EqualTo("90"));
    }

    [Test]
    public async Task UpdateSetting_NotFound_Returns404()
    {
        var dto = new UpdateSettingDto { SettingValue = "0" };
        var response = await _client.PutAsJsonAsync("/api/admin/settings/99999", dto);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task GenerateOrders_NoInternetEmployee_Returns400()
    {
        // Clear all seed data (removes the internet-sales employee)
        var clearResp = await _client.DeleteAsync("/api/admin/test-data");
        Assert.That(clearResp.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        // Now there is no internet-sales employee - should return 400
        var dto = new GenerateOrdersDto { Count = 2 };
        var response = await _client.PostAsJsonAsync("/api/admin/generate-orders", dto);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.BadRequest));
    }

    [Test]
    public async Task GenerateOrders_WithSeedData_ReturnsOk()
    {
        // Seeded DB has internet-sales employee, customers, products
        var dto = new GenerateOrdersDto { Count = 2 };
        var response = await _client.PostAsJsonAsync("/api/admin/generate-orders", dto);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        Assert.That(doc.RootElement.GetProperty("ordersCreated").GetInt32(), Is.EqualTo(2));
    }

    [Test]
    public async Task DeleteTestData_ReturnsOk()
    {
        // Create some data first
        await _client.PostAsJsonAsync("/api/products",
            new ProductCreateUpdateDto { ProductCode = "CLR-001", ProductName = "Clear Me" });

        var response = await _client.DeleteAsync("/api/admin/test-data");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        Assert.That(doc.RootElement.TryGetProperty("message", out _), Is.True);
        Assert.That(doc.RootElement.TryGetProperty("productsDeleted", out _), Is.True);
    }
}
