// Generated by booster-apidev | 2026-04-06 19:37:30

using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using ApiApp.DTOs.Customers;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class CustomersControllerTests
{
    private CustomWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;

    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        PropertyNameCaseInsensitive = true
    };

    [SetUp]
    public void SetUp()
    {
        _factory = new CustomWebApplicationFactory();
        _client = _factory.CreateClient();
    }

    [TearDown]
    public void TearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    [Test]
    public async Task GetCustomers_ReturnsPagedResult()
    {
        var response = await _client.GetAsync("/api/customers");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        Assert.That(doc.RootElement.TryGetProperty("items", out _), Is.True);
        Assert.That(doc.RootElement.TryGetProperty("totalCount", out _), Is.True);
    }

    [Test]
    public async Task GetCustomers_WithSearch_FiltersResults()
    {
        // First create a customer
        var createDto = new CustomerCreateUpdateDto { CustomerName = "Acme Search Corp", City = "TestCity" };
        var createResp = await _client.PostAsJsonAsync("/api/customers", createDto);
        Assert.That(createResp.StatusCode, Is.EqualTo(HttpStatusCode.Created));

        var response = await _client.GetAsync("/api/customers?search=Acme Search");
        response.EnsureSuccessStatusCode();
        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        var items = doc.RootElement.GetProperty("items");
        Assert.That(items.GetArrayLength(), Is.GreaterThanOrEqualTo(1));
    }

    [Test]
    public async Task GetCustomer_NotFound_Returns404()
    {
        var response = await _client.GetAsync("/api/customers/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task CreateCustomer_ReturnsCreated()
    {
        var dto = new CustomerCreateUpdateDto
        {
            CustomerName = "Test Corp",
            PrimaryContactFirstName = "Jane",
            PrimaryContactLastName = "Doe",
            City = "Seattle",
            State = "WA"
        };

        var response = await _client.PostAsJsonAsync("/api/customers", dto);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.Created));

        var body = await response.Content.ReadFromJsonAsync<CustomerDetailDto>(JsonOpts);
        Assert.That(body, Is.Not.Null);
        Assert.That(body!.CustomerName, Is.EqualTo("Test Corp"));
        Assert.That(body.PrimaryContactFullName, Is.EqualTo("Jane Doe"));
        Assert.That(response.Headers.Location, Is.Not.Null);
    }

    [Test]
    public async Task CreateAndUpdateCustomer_ReturnsUpdated()
    {
        var createDto = new CustomerCreateUpdateDto { CustomerName = "Before", City = "OldCity" };
        var createResp = await _client.PostAsJsonAsync("/api/customers", createDto);
        var created = await createResp.Content.ReadFromJsonAsync<CustomerDetailDto>(JsonOpts);
        Assert.That(created, Is.Not.Null);

        var updateDto = new CustomerCreateUpdateDto { CustomerName = "After", City = "NewCity" };
        var updateResp = await _client.PutAsJsonAsync($"/api/customers/{created!.Id}", updateDto);
        Assert.That(updateResp.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var updated = await updateResp.Content.ReadFromJsonAsync<CustomerDetailDto>(JsonOpts);
        Assert.That(updated!.CustomerName, Is.EqualTo("After"));
        Assert.That(updated.City, Is.EqualTo("NewCity"));
    }

    [Test]
    public async Task UpdateCustomer_NotFound_Returns404()
    {
        var dto = new CustomerCreateUpdateDto { CustomerName = "Ghost" };
        var response = await _client.PutAsJsonAsync("/api/customers/99999", dto);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task DeleteCustomer_ReturnsNoContent()
    {
        var createDto = new CustomerCreateUpdateDto { CustomerName = "Delete Me" };
        var createResp = await _client.PostAsJsonAsync("/api/customers", createDto);
        var created = await createResp.Content.ReadFromJsonAsync<CustomerDetailDto>(JsonOpts);

        var deleteResp = await _client.DeleteAsync($"/api/customers/{created!.Id}");
        Assert.That(deleteResp.StatusCode, Is.EqualTo(HttpStatusCode.NoContent));

        var getResp = await _client.GetAsync($"/api/customers/{created.Id}");
        Assert.That(getResp.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task DeleteCustomer_NotFound_Returns404()
    {
        var response = await _client.DeleteAsync("/api/customers/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task GetCustomerOrders_NotFound_Returns404()
    {
        var response = await _client.GetAsync("/api/customers/99999/orders");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task GetCustomerProducts_NotFound_Returns404()
    {
        var response = await _client.GetAsync("/api/customers/99999/products");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task GetCustomerOrders_ReturnsPagedResult()
    {
        var createDto = new CustomerCreateUpdateDto { CustomerName = "Order Customer" };
        var createResp = await _client.PostAsJsonAsync("/api/customers", createDto);
        var customer = await createResp.Content.ReadFromJsonAsync<CustomerDetailDto>(JsonOpts);

        var response = await _client.GetAsync($"/api/customers/{customer!.Id}/orders");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        Assert.That(doc.RootElement.TryGetProperty("items", out _), Is.True);
    }

    [Test]
    public async Task GetCustomers_Pagination_Works()
    {
        for (int i = 0; i < 5; i++)
        {
            await _client.PostAsJsonAsync("/api/customers",
                new CustomerCreateUpdateDto { CustomerName = $"Paged Customer {i}" });
        }

        var response = await _client.GetAsync("/api/customers?page=1&pageSize=2");
        response.EnsureSuccessStatusCode();
        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        Assert.That(doc.RootElement.GetProperty("items").GetArrayLength(), Is.LessThanOrEqualTo(2));
        Assert.That(doc.RootElement.GetProperty("pageSize").GetInt32(), Is.EqualTo(2));
    }
}
