// Generated by booster-apidev | 2026-04-06 19:37:30

using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using ApiApp.DTOs.Employees;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class EmployeesControllerTests
{
    private CustomWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNameCaseInsensitive = true };

    [SetUp]
    public void SetUp()
    {
        _factory = new CustomWebApplicationFactory();
        _client = _factory.CreateClient();
    }

    [TearDown]
    public void TearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    [Test]
    public async Task GetEmployees_ReturnsPagedResult()
    {
        var response = await _client.GetAsync("/api/employees");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        Assert.That(doc.RootElement.TryGetProperty("items", out _), Is.True);
    }

    [Test]
    public async Task GetEmployee_NotFound_Returns404()
    {
        var response = await _client.GetAsync("/api/employees/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task CreateEmployee_ReturnsCreated()
    {
        var dto = new EmployeeCreateUpdateDto
        {
            FirstName = "Alice",
            LastName = "Smith",
            EmailAddress = "alice.smith@test.com",
            JobTitle = "Developer",
            WindowsUserName = "TEST\\ASmith_unique1"
        };

        var response = await _client.PostAsJsonAsync("/api/employees", dto);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.Created));

        var body = await response.Content.ReadFromJsonAsync<EmployeeDetailDto>(JsonOpts);
        Assert.That(body, Is.Not.Null);
        Assert.That(body!.FirstName, Is.EqualTo("Alice"));
        Assert.That(body.FullNameFNLN, Is.EqualTo("Alice Smith"));
        Assert.That(body.FullNameLNFN, Is.EqualTo("Smith, Alice"));
    }

    [Test]
    public async Task CreateEmployee_DuplicateWindowsUserName_Returns400()
    {
        var dto = new EmployeeCreateUpdateDto
        {
            FirstName = "Bob",
            LastName = "Jones",
            WindowsUserName = "NORTHWIND\\DuplicateUser"
        };

        var first = await _client.PostAsJsonAsync("/api/employees", dto);
        Assert.That(first.StatusCode, Is.EqualTo(HttpStatusCode.Created));

        var second = await _client.PostAsJsonAsync("/api/employees", dto);
        Assert.That(second.StatusCode, Is.EqualTo(HttpStatusCode.BadRequest));
    }

    [Test]
    public async Task UpdateEmployee_ReturnsUpdated()
    {
        var createDto = new EmployeeCreateUpdateDto
        {
            FirstName = "Old",
            LastName = "Name",
            WindowsUserName = "TEST\\OldName_upd"
        };
        var createResp = await _client.PostAsJsonAsync("/api/employees", createDto);
        var created = await createResp.Content.ReadFromJsonAsync<EmployeeDetailDto>(JsonOpts);

        var updateDto = new EmployeeCreateUpdateDto
        {
            FirstName = "New",
            LastName = "Name",
            WindowsUserName = "TEST\\OldName_upd"
        };
        var updateResp = await _client.PutAsJsonAsync($"/api/employees/{created!.Id}", updateDto);
        Assert.That(updateResp.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var updated = await updateResp.Content.ReadFromJsonAsync<EmployeeDetailDto>(JsonOpts);
        Assert.That(updated!.FirstName, Is.EqualTo("New"));
    }

    [Test]
    public async Task DeleteEmployee_ReturnsNoContent()
    {
        var dto = new EmployeeCreateUpdateDto { FirstName = "Temp", LastName = "Worker", WindowsUserName = "TEST\\TempWorker_del" };
        var createResp = await _client.PostAsJsonAsync("/api/employees", dto);
        var created = await createResp.Content.ReadFromJsonAsync<EmployeeDetailDto>(JsonOpts);

        var deleteResp = await _client.DeleteAsync($"/api/employees/{created!.Id}");
        Assert.That(deleteResp.StatusCode, Is.EqualTo(HttpStatusCode.NoContent));

        var getResp = await _client.GetAsync($"/api/employees/{created.Id}");
        Assert.That(getResp.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task DeleteEmployee_NotFound_Returns404()
    {
        var response = await _client.DeleteAsync("/api/employees/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task GetEmployees_WithSearch_FiltersResults()
    {
        var dto = new EmployeeCreateUpdateDto
        {
            FirstName = "SearchFirst",
            LastName = "SearchLast",
            EmailAddress = "search@test.com",
            WindowsUserName = "TEST\\SearchUser_fil"
        };
        await _client.PostAsJsonAsync("/api/employees", dto);

        var response = await _client.GetAsync("/api/employees?search=SearchLast");
        response.EnsureSuccessStatusCode();
        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        Assert.That(doc.RootElement.GetProperty("totalCount").GetInt32(), Is.GreaterThanOrEqualTo(1));
    }

    [Test]
    public async Task GetEmployeeOrders_NotFound_Returns404()
    {
        var response = await _client.GetAsync("/api/employees/99999/orders");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task GetEmployeeOrders_ReturnsPagedResult()
    {
        var dto = new EmployeeCreateUpdateDto { FirstName = "Order", LastName = "Emp", WindowsUserName = "TEST\\OrderEmp_ord" };
        var createResp = await _client.PostAsJsonAsync("/api/employees", dto);
        var employee = await createResp.Content.ReadFromJsonAsync<EmployeeDetailDto>(JsonOpts);

        var response = await _client.GetAsync($"/api/employees/{employee!.Id}/orders");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
    }
}
