// Generated by booster-apidev | 2026-04-06 19:37:30

using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using ApiApp.DTOs.Customers;
using ApiApp.DTOs.Lookup;
using ApiApp.DTOs.Orders;
using ApiApp.DTOs.Products;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class LookupControllerTests
{
    private CustomWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNameCaseInsensitive = true };

    [SetUp]
    public void SetUp()
    {
        _factory = new CustomWebApplicationFactory();
        _client = _factory.CreateClient();
    }

    [TearDown]
    public void TearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    [Test]
    public async Task GetOrderStatuses_ReturnsAllStatuses()
    {
        var response = await _client.GetAsync("/api/lookup/order-statuses");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var statuses = await response.Content.ReadFromJsonAsync<List<OrderStatusLookupDto>>(JsonOpts);
        Assert.That(statuses, Is.Not.Null);
        Assert.That(statuses!.Count, Is.EqualTo(5));

        var values = statuses.Select(s => s.Value).ToList();
        Assert.That(values, Does.Contain("New"));
        Assert.That(values, Does.Contain("Invoiced"));
        Assert.That(values, Does.Contain("Shipped"));
        Assert.That(values, Does.Contain("Paid"));
        Assert.That(values, Does.Contain("Closed"));
    }

    [Test]
    public async Task GetOrderStatuses_OrderedBySortOrder()
    {
        var response = await _client.GetAsync("/api/lookup/order-statuses");
        var statuses = await response.Content.ReadFromJsonAsync<List<OrderStatusLookupDto>>(JsonOpts);
        Assert.That(statuses, Is.Not.Null);

        var sortOrders = statuses!.Select(s => s.SortOrder).ToList();
        Assert.That(sortOrders, Is.Ordered.Ascending);
    }

    [Test]
    public async Task GetLookupCustomers_ReturnsOk()
    {
        await _client.PostAsJsonAsync("/api/customers",
            new CustomerCreateUpdateDto { CustomerName = "Lookup Corp" });

        var response = await _client.GetAsync("/api/lookup/customers");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var customers = await response.Content.ReadFromJsonAsync<List<CustomerLookupDto>>(JsonOpts);
        Assert.That(customers, Is.Not.Null);
        Assert.That(customers!.Count, Is.GreaterThanOrEqualTo(1));
    }

    [Test]
    public async Task GetLookupEmployees_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/lookup/employees");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
    }

    [Test]
    public async Task GetLookupProducts_ReturnsOk()
    {
        await _client.PostAsJsonAsync("/api/products",
            new ProductCreateUpdateDto { ProductCode = "LKP-001", ProductName = "Lookup Product", UnitPrice = 5.00m });

        var response = await _client.GetAsync("/api/lookup/products");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var products = await response.Content.ReadFromJsonAsync<List<ProductLookupDto>>(JsonOpts);
        Assert.That(products, Is.Not.Null);
        Assert.That(products!.Any(p => p.ProductCode == "LKP-001"), Is.True);
    }
}
