// Generated by booster-apidev | 2026-04-06 19:37:30

using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using ApiApp.DTOs.Customers;
using ApiApp.DTOs.OrderDetails;
using ApiApp.DTOs.Orders;
using ApiApp.DTOs.Products;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class OrderDetailsControllerTests
{
    private CustomWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNameCaseInsensitive = true };

    [SetUp]
    public void SetUp()
    {
        _factory = new CustomWebApplicationFactory();
        _client = _factory.CreateClient();
    }

    [TearDown]
    public void TearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    private async Task<int> CreateProductAsync(string code, string name, decimal price)
    {
        var resp = await _client.PostAsJsonAsync("/api/products",
            new ProductCreateUpdateDto { ProductCode = code, ProductName = name, UnitPrice = price });
        resp.EnsureSuccessStatusCode();
        var body = await resp.Content.ReadFromJsonAsync<JsonElement>(JsonOpts);
        return body.GetProperty("id").GetInt32();
    }

    private async Task<int> CreateOrderAsync()
    {
        var resp = await _client.PostAsJsonAsync("/api/orders",
            new OrderCreateDto { OrderDate = DateTime.UtcNow, Status = "New" });
        resp.EnsureSuccessStatusCode();
        var body = await resp.Content.ReadFromJsonAsync<JsonElement>(JsonOpts);
        return body.GetProperty("id").GetInt32();
    }

    [Test]
    public async Task GetOrderDetails_OrderNotFound_Returns404()
    {
        var response = await _client.GetAsync("/api/orders/99999/details");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task GetOrderDetails_ReturnsEmptyList_ForNewOrder()
    {
        var orderId = await CreateOrderAsync();
        var response = await _client.GetAsync($"/api/orders/{orderId}/details");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var items = await response.Content.ReadFromJsonAsync<List<OrderDetailItemDto>>(JsonOpts);
        Assert.That(items, Is.Not.Null);
        Assert.That(items, Is.Empty);
    }

    [Test]
    public async Task AddOrderDetail_ReturnsCreated()
    {
        var orderId = await CreateOrderAsync();
        var productId = await CreateProductAsync("OD-001", "Order Detail Product", 15.99m);

        var dto = new OrderDetailCreateUpdateDto { ProductId = productId, Quantity = 3 };
        var response = await _client.PostAsJsonAsync($"/api/orders/{orderId}/details", dto);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.Created));

        var body = await response.Content.ReadFromJsonAsync<OrderDetailItemDto>(JsonOpts);
        Assert.That(body, Is.Not.Null);
        Assert.That(body!.Quantity, Is.EqualTo(3));
        Assert.That(body.UnitPrice, Is.EqualTo(15.99m));
        Assert.That(body.ExtendedPrice, Is.EqualTo(3 * 15.99m));
    }

    [Test]
    public async Task AddOrderDetail_DefaultsUnitPriceFromProduct()
    {
        var orderId = await CreateOrderAsync();
        var productId = await CreateProductAsync("OD-002", "Price Default Product", 25.00m);

        // Do not pass UnitPrice in the request - should default from product
        var dto = new OrderDetailCreateUpdateDto { ProductId = productId, Quantity = 2 };
        var response = await _client.PostAsJsonAsync($"/api/orders/{orderId}/details", dto);
        response.EnsureSuccessStatusCode();

        var body = await response.Content.ReadFromJsonAsync<OrderDetailItemDto>(JsonOpts);
        Assert.That(body!.UnitPrice, Is.EqualTo(25.00m));
    }

    [Test]
    public async Task AddOrderDetail_InvalidProduct_Returns400()
    {
        var orderId = await CreateOrderAsync();
        var dto = new OrderDetailCreateUpdateDto { ProductId = 99999, Quantity = 1 };
        var response = await _client.PostAsJsonAsync($"/api/orders/{orderId}/details", dto);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.BadRequest));
    }

    [Test]
    public async Task UpdateOrderDetail_ReturnsUpdated()
    {
        var orderId = await CreateOrderAsync();
        var productId = await CreateProductAsync("OD-003", "Update Product", 10.00m);

        var addDto = new OrderDetailCreateUpdateDto { ProductId = productId, Quantity = 1 };
        var addResp = await _client.PostAsJsonAsync($"/api/orders/{orderId}/details", addDto);
        var added = await addResp.Content.ReadFromJsonAsync<OrderDetailItemDto>(JsonOpts);

        var updateDto = new OrderDetailCreateUpdateDto { ProductId = productId, Quantity = 5, UnitPrice = 10.00m };
        var updateResp = await _client.PutAsJsonAsync($"/api/orders/{orderId}/details/{added!.Id}", updateDto);
        Assert.That(updateResp.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var updated = await updateResp.Content.ReadFromJsonAsync<OrderDetailItemDto>(JsonOpts);
        Assert.That(updated!.Quantity, Is.EqualTo(5));
        Assert.That(updated.ExtendedPrice, Is.EqualTo(50.00m));
    }

    [Test]
    public async Task DeleteOrderDetail_ReturnsNoContent()
    {
        var orderId = await CreateOrderAsync();
        var productId = await CreateProductAsync("OD-004", "Delete Product", 8.00m);

        var addDto = new OrderDetailCreateUpdateDto { ProductId = productId, Quantity = 1 };
        var addResp = await _client.PostAsJsonAsync($"/api/orders/{orderId}/details", addDto);
        var added = await addResp.Content.ReadFromJsonAsync<OrderDetailItemDto>(JsonOpts);

        var deleteResp = await _client.DeleteAsync($"/api/orders/{orderId}/details/{added!.Id}");
        Assert.That(deleteResp.StatusCode, Is.EqualTo(HttpStatusCode.NoContent));

        var items = await _client.GetFromJsonAsync<List<OrderDetailItemDto>>($"/api/orders/{orderId}/details", JsonOpts);
        Assert.That(items, Is.Empty);
    }

    [Test]
    public async Task DeleteOrderDetail_NotFound_Returns404()
    {
        var orderId = await CreateOrderAsync();
        var response = await _client.DeleteAsync($"/api/orders/{orderId}/details/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }
}
