// Generated by booster-apidev | 2026-04-06 19:37:30

using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using ApiApp.DTOs.Customers;
using ApiApp.DTOs.Employees;
using ApiApp.DTOs.Orders;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class OrdersControllerTests
{
    private CustomWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNameCaseInsensitive = true };

    [SetUp]
    public void SetUp()
    {
        _factory = new CustomWebApplicationFactory();
        _client = _factory.CreateClient();
    }

    [TearDown]
    public void TearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    private async Task<int> CreateCustomerAsync(string name = "Test Customer")
    {
        var resp = await _client.PostAsJsonAsync("/api/customers",
            new CustomerCreateUpdateDto { CustomerName = name });
        var body = await resp.Content.ReadFromJsonAsync<JsonElement>(JsonOpts);
        return body.GetProperty("id").GetInt32();
    }

    private async Task<int> CreateEmployeeAsync(string firstName = "John", string lastName = "Doe", string winUser = "TEST\\JDoe_ord")
    {
        var resp = await _client.PostAsJsonAsync("/api/employees",
            new EmployeeCreateUpdateDto { FirstName = firstName, LastName = lastName, WindowsUserName = winUser });
        var body = await resp.Content.ReadFromJsonAsync<JsonElement>(JsonOpts);
        return body.GetProperty("id").GetInt32();
    }

    [Test]
    public async Task GetOrders_ReturnsPagedResult()
    {
        var response = await _client.GetAsync("/api/orders");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        Assert.That(doc.RootElement.TryGetProperty("items", out _), Is.True);
    }

    [Test]
    public async Task GetOrder_NotFound_Returns404()
    {
        var response = await _client.GetAsync("/api/orders/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task CreateOrder_ReturnsCreated()
    {
        var customerId = await CreateCustomerAsync("Order Test Customer");
        var employeeId = await CreateEmployeeAsync("Jane", "Roe", "TEST\\JRoe_cr");

        var dto = new OrderCreateDto
        {
            CustomerId = customerId,
            EmployeeId = employeeId,
            OrderDate = DateTime.UtcNow,
            Status = "New"
        };

        var response = await _client.PostAsJsonAsync("/api/orders", dto);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.Created));

        var body = await response.Content.ReadFromJsonAsync<OrderDetailDto>(JsonOpts);
        Assert.That(body, Is.Not.Null);
        Assert.That(body!.CustomerId, Is.EqualTo(customerId));
        Assert.That(body.Status, Is.EqualTo("New"));
        Assert.That(response.Headers.Location, Is.Not.Null);
    }

    [Test]
    public async Task CreateOrder_InvalidStatus_Returns400()
    {
        var dto = new OrderCreateDto { Status = "InvalidStatusXYZ" };
        var response = await _client.PostAsJsonAsync("/api/orders", dto);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.BadRequest));
    }

    [Test]
    public async Task UpdateOrder_ReturnsUpdated()
    {
        var customerId = await CreateCustomerAsync("Update Customer");

        var createDto = new OrderCreateDto { CustomerId = customerId, OrderDate = DateTime.UtcNow, Status = "New" };
        var createResp = await _client.PostAsJsonAsync("/api/orders", createDto);
        var created = await createResp.Content.ReadFromJsonAsync<OrderDetailDto>(JsonOpts);

        var updateDto = new OrderCreateDto { CustomerId = customerId, Status = "Invoiced", Notes = "Updated notes" };
        var updateResp = await _client.PutAsJsonAsync($"/api/orders/{created!.Id}", updateDto);
        Assert.That(updateResp.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var updated = await updateResp.Content.ReadFromJsonAsync<OrderDetailDto>(JsonOpts);
        Assert.That(updated!.Status, Is.EqualTo("Invoiced"));
        Assert.That(updated.Notes, Is.EqualTo("Updated notes"));
    }

    [Test]
    public async Task PatchOrderStatus_ReturnsUpdatedStatus()
    {
        var createDto = new OrderCreateDto { OrderDate = DateTime.UtcNow, Status = "New" };
        var createResp = await _client.PostAsJsonAsync("/api/orders", createDto);
        var created = await createResp.Content.ReadFromJsonAsync<OrderDetailDto>(JsonOpts);

        var patchDto = new OrderStatusPatchDto { Status = "Shipped" };
        var patchResp = await _client.PatchAsJsonAsync($"/api/orders/{created!.Id}/status", patchDto);
        Assert.That(patchResp.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var body = await patchResp.Content.ReadFromJsonAsync<OrderStatusPatchResponseDto>(JsonOpts);
        Assert.That(body!.Status, Is.EqualTo("Shipped"));
    }

    [Test]
    public async Task PatchOrderStatus_InvalidStatus_Returns400()
    {
        var createDto = new OrderCreateDto { OrderDate = DateTime.UtcNow, Status = "New" };
        var createResp = await _client.PostAsJsonAsync("/api/orders", createDto);
        var created = await createResp.Content.ReadFromJsonAsync<OrderDetailDto>(JsonOpts);

        var patchResp = await _client.PatchAsJsonAsync(
            $"/api/orders/{created!.Id}/status",
            new OrderStatusPatchDto { Status = "BADSTATUS" });
        Assert.That(patchResp.StatusCode, Is.EqualTo(HttpStatusCode.BadRequest));
    }

    [Test]
    public async Task PatchOrderStatus_NotFound_Returns404()
    {
        var patchResp = await _client.PatchAsJsonAsync(
            "/api/orders/99999/status",
            new OrderStatusPatchDto { Status = "Shipped" });
        Assert.That(patchResp.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task DeleteOrder_ReturnsNoContent()
    {
        var createDto = new OrderCreateDto { OrderDate = DateTime.UtcNow, Status = "New" };
        var createResp = await _client.PostAsJsonAsync("/api/orders", createDto);
        var created = await createResp.Content.ReadFromJsonAsync<OrderDetailDto>(JsonOpts);

        var deleteResp = await _client.DeleteAsync($"/api/orders/{created!.Id}");
        Assert.That(deleteResp.StatusCode, Is.EqualTo(HttpStatusCode.NoContent));

        var getResp = await _client.GetAsync($"/api/orders/{created.Id}");
        Assert.That(getResp.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task GetOrders_FilterByStatus_Works()
    {
        var customerId = await CreateCustomerAsync("Status Filter Customer");
        var createDto = new OrderCreateDto { CustomerId = customerId, OrderDate = DateTime.UtcNow, Status = "Paid" };
        await _client.PostAsJsonAsync("/api/orders", createDto);

        var response = await _client.GetAsync("/api/orders?status=Paid");
        response.EnsureSuccessStatusCode();
        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        var items = doc.RootElement.GetProperty("items");
        Assert.That(doc.RootElement.GetProperty("totalCount").GetInt32(), Is.GreaterThanOrEqualTo(1));
        foreach (var item in items.EnumerateArray())
        {
            Assert.That(item.GetProperty("status").GetString(), Is.EqualTo("Paid"));
        }
    }

    [Test]
    public async Task GetOrders_TopParameter_LimitsResults()
    {
        for (int i = 0; i < 5; i++)
        {
            await _client.PostAsJsonAsync("/api/orders",
                new OrderCreateDto { OrderDate = DateTime.UtcNow, Status = "New" });
        }

        var response = await _client.GetAsync("/api/orders?top=2");
        response.EnsureSuccessStatusCode();
        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        Assert.That(doc.RootElement.GetProperty("items").GetArrayLength(), Is.LessThanOrEqualTo(2));
    }
}
