// Generated by booster-apidev | 2026-04-06 19:37:30

using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using ApiApp.DTOs.Products;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class ProductsControllerTests
{
    private CustomWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNameCaseInsensitive = true };

    [SetUp]
    public void SetUp()
    {
        _factory = new CustomWebApplicationFactory();
        _client = _factory.CreateClient();
    }

    [TearDown]
    public void TearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    [Test]
    public async Task GetProducts_ReturnsPagedResult()
    {
        var response = await _client.GetAsync("/api/products");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        Assert.That(doc.RootElement.TryGetProperty("items", out _), Is.True);
    }

    [Test]
    public async Task GetProduct_NotFound_Returns404()
    {
        var response = await _client.GetAsync("/api/products/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task CreateProduct_ReturnsCreated()
    {
        var dto = new ProductCreateUpdateDto
        {
            ProductCode = "TEST-001",
            ProductName = "Test Product",
            ProductDescription = "A test product.",
            UnitPrice = 9.99m
        };

        var response = await _client.PostAsJsonAsync("/api/products", dto);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.Created));

        var body = await response.Content.ReadFromJsonAsync<ProductDetailDto>(JsonOpts);
        Assert.That(body, Is.Not.Null);
        Assert.That(body!.ProductCode, Is.EqualTo("TEST-001"));
        Assert.That(body.UnitPrice, Is.EqualTo(9.99m));
    }

    [Test]
    public async Task CreateProduct_DuplicateProductCode_Returns400()
    {
        var dto = new ProductCreateUpdateDto { ProductCode = "DUP-001", ProductName = "First" };
        var first = await _client.PostAsJsonAsync("/api/products", dto);
        Assert.That(first.StatusCode, Is.EqualTo(HttpStatusCode.Created));

        var second = await _client.PostAsJsonAsync("/api/products", dto);
        Assert.That(second.StatusCode, Is.EqualTo(HttpStatusCode.BadRequest));
    }

    [Test]
    public async Task UpdateProduct_ReturnsUpdated()
    {
        var createDto = new ProductCreateUpdateDto { ProductCode = "UPD-001", ProductName = "Old Name", UnitPrice = 1.00m };
        var createResp = await _client.PostAsJsonAsync("/api/products", createDto);
        var created = await createResp.Content.ReadFromJsonAsync<ProductDetailDto>(JsonOpts);

        var updateDto = new ProductCreateUpdateDto { ProductCode = "UPD-001", ProductName = "New Name", UnitPrice = 2.00m };
        var updateResp = await _client.PutAsJsonAsync($"/api/products/{created!.Id}", updateDto);
        Assert.That(updateResp.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var updated = await updateResp.Content.ReadFromJsonAsync<ProductDetailDto>(JsonOpts);
        Assert.That(updated!.ProductName, Is.EqualTo("New Name"));
        Assert.That(updated.UnitPrice, Is.EqualTo(2.00m));
    }

    [Test]
    public async Task DeleteProduct_NoOrders_ReturnsNoContent()
    {
        var dto = new ProductCreateUpdateDto { ProductCode = "DEL-001", ProductName = "Delete Me" };
        var createResp = await _client.PostAsJsonAsync("/api/products", dto);
        var created = await createResp.Content.ReadFromJsonAsync<ProductDetailDto>(JsonOpts);

        var deleteResp = await _client.DeleteAsync($"/api/products/{created!.Id}");
        Assert.That(deleteResp.StatusCode, Is.EqualTo(HttpStatusCode.NoContent));

        var getResp = await _client.GetAsync($"/api/products/{created.Id}");
        Assert.That(getResp.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task DeleteProduct_WithOrders_Returns409()
    {
        var createDto = new ProductCreateUpdateDto { ProductCode = "USED-001", ProductName = "Used Product", UnitPrice = 10.00m };
        var createResp = await _client.PostAsJsonAsync("/api/products", createDto);
        var product = await createResp.Content.ReadFromJsonAsync<ProductDetailDto>(JsonOpts);

        var orderResp = await _client.PostAsJsonAsync("/api/orders",
            new ApiApp.DTOs.Orders.OrderCreateDto { OrderDate = DateTime.UtcNow, Status = "New" });
        var order = await orderResp.Content.ReadFromJsonAsync<JsonElement>(JsonOpts);
        var orderId = order.GetProperty("id").GetInt32();

        await _client.PostAsJsonAsync($"/api/orders/{orderId}/details",
            new ApiApp.DTOs.OrderDetails.OrderDetailCreateUpdateDto { ProductId = product!.Id, Quantity = 1 });

        var deleteResp = await _client.DeleteAsync($"/api/products/{product.Id}");
        Assert.That(deleteResp.StatusCode, Is.EqualTo(HttpStatusCode.Conflict));
    }

    [Test]
    public async Task GetProducts_WithSalesStats_ReturnsStats()
    {
        var dto = new ProductCreateUpdateDto { ProductCode = "STAT-001", ProductName = "Stats Product", UnitPrice = 5.00m };
        await _client.PostAsJsonAsync("/api/products", dto);

        var response = await _client.GetAsync("/api/products?includeSalesStats=true");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        var items = doc.RootElement.GetProperty("items");
        Assert.That(items.GetArrayLength(), Is.GreaterThanOrEqualTo(1));
    }

    [Test]
    public async Task GetProductOrders_NotFound_Returns404()
    {
        var response = await _client.GetAsync("/api/products/99999/orders");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task GetProductOrders_ReturnsEmptyList()
    {
        var dto = new ProductCreateUpdateDto { ProductCode = "ORD-001", ProductName = "Order Product" };
        var createResp = await _client.PostAsJsonAsync("/api/products", dto);
        var product = await createResp.Content.ReadFromJsonAsync<ProductDetailDto>(JsonOpts);

        var response = await _client.GetAsync($"/api/products/{product!.Id}/orders");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var items = await response.Content.ReadFromJsonAsync<List<ProductOrderSummaryDto>>(JsonOpts);
        Assert.That(items, Is.Not.Null);
    }
}
