// Generated by booster-apidev | 2026-04-06 19:37:30

using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using ApiApp.DTOs.Customers;
using ApiApp.DTOs.Employees;
using ApiApp.DTOs.Orders;
using ApiApp.DTOs.OrderDetails;
using ApiApp.DTOs.Products;
using ApiApp.DTOs.Reports;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class ReportsControllerTests
{
    private CustomWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNameCaseInsensitive = true };

    [SetUp]
    public void SetUp()
    {
        _factory = new CustomWebApplicationFactory();
        _client = _factory.CreateClient();
    }

    [TearDown]
    public void TearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    private async Task<int> CreateProductAsync(string code, decimal price = 10m)
    {
        var resp = await _client.PostAsJsonAsync("/api/products",
            new ProductCreateUpdateDto { ProductCode = code, ProductName = $"Product {code}", UnitPrice = price });
        resp.EnsureSuccessStatusCode();
        var body = await resp.Content.ReadFromJsonAsync<JsonElement>(JsonOpts);
        return body.GetProperty("id").GetInt32();
    }

    private async Task<int> CreateOrderAsync(int? customerId = null)
    {
        var resp = await _client.PostAsJsonAsync("/api/orders",
            new OrderCreateDto { CustomerId = customerId, OrderDate = DateTime.UtcNow, Status = "New" });
        resp.EnsureSuccessStatusCode();
        var body = await resp.Content.ReadFromJsonAsync<JsonElement>(JsonOpts);
        return body.GetProperty("id").GetInt32();
    }

    [Test]
    public async Task GetSalesYtd_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reports/sales-ytd");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var dto = await response.Content.ReadFromJsonAsync<SalesYtdDto>(JsonOpts);
        Assert.That(dto, Is.Not.Null);
        Assert.That(dto!.Year, Is.EqualTo(DateTime.UtcNow.Year));
        Assert.That(dto.TotalSales, Is.GreaterThanOrEqualTo(0));
    }

    [Test]
    public async Task GetSalesByEmployee_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reports/sales-by-employee");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
    }

    [Test]
    public async Task GetSalesByEmployee_WithYear_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reports/sales-by-employee?year=2025");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
    }

    [Test]
    public async Task GetSalesByProduct_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reports/sales-by-product");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
    }

    [Test]
    public async Task GetSalesByProduct_ByQuarter_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reports/sales-by-product?groupBy=quarter");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
    }

    [Test]
    public async Task GetInvoice_NotFound_Returns404()
    {
        var response = await _client.GetAsync("/api/reports/invoice/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task GetInvoice_ReturnsInvoiceData()
    {
        var productId = await CreateProductAsync("INV-001", 20m);
        var orderId = await CreateOrderAsync();

        await _client.PostAsJsonAsync($"/api/orders/{orderId}/details",
            new OrderDetailCreateUpdateDto { ProductId = productId, Quantity = 2, UnitPrice = 20m });

        var response = await _client.GetAsync($"/api/reports/invoice/{orderId}");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var invoice = await response.Content.ReadFromJsonAsync<InvoiceDto>(JsonOpts);
        Assert.That(invoice, Is.Not.Null);
        Assert.That(invoice!.OrderId, Is.EqualTo(orderId));
        Assert.That(invoice.Subtotal, Is.EqualTo(40m));
        Assert.That(invoice.TaxRate, Is.EqualTo(0.085m));
        Assert.That(invoice.TaxAmount, Is.EqualTo(Math.Round(40m * 0.085m, 2)));
        Assert.That(invoice.Total, Is.EqualTo(invoice.Subtotal + invoice.TaxAmount));
    }

    [Test]
    public async Task GetEmployeeEmailList_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reports/employee-email-list");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var list = await response.Content.ReadFromJsonAsync<List<EmployeeEmailListDto>>(JsonOpts);
        Assert.That(list, Is.Not.Null);
    }

    [Test]
    public async Task GetEmployeePhoneList_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reports/employee-phone-list");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));

        var list = await response.Content.ReadFromJsonAsync<List<EmployeePhoneListDto>>(JsonOpts);
        Assert.That(list, Is.Not.Null);
    }

    [Test]
    public async Task GetSalesYtd_AfterAddingOrders_ReflectsCorrectTotal()
    {
        var productId = await CreateProductAsync("YTD-001", 100m);
        var orderId = await CreateOrderAsync();

        await _client.PostAsJsonAsync($"/api/orders/{orderId}/details",
            new OrderDetailCreateUpdateDto { ProductId = productId, Quantity = 3, UnitPrice = 100m });

        var response = await _client.GetAsync("/api/reports/sales-ytd");
        var dto = await response.Content.ReadFromJsonAsync<SalesYtdDto>(JsonOpts);
        Assert.That(dto!.TotalSales, Is.GreaterThanOrEqualTo(300m));
    }
}
