// > Generated by booster-webdev | 2026-04-07 12:29:26
namespace WebApp.Models;

// --- Customers ---

public class CustomerDto
{
    public int CustomerId { get; set; }
    public string? CustomerName { get; set; }
    public string? PrimaryContactFirstName { get; set; }
    public string? PrimaryContactLastName { get; set; }
    public string? PrimaryContactJobTitle { get; set; }
    public string? PrimaryContactEmailAddress { get; set; }
    public string? PrimaryContactFullName { get; set; }
    public string? BusinessPhone { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? Zip { get; set; }
    public string? Website { get; set; }
    public string? Notes { get; set; }
    public string? AddedBy { get; set; }
    public DateTime? AddedOn { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }
}

public class CustomerRequest
{
    public string? CustomerName { get; set; }
    public string? PrimaryContactFirstName { get; set; }
    public string? PrimaryContactLastName { get; set; }
    public string? PrimaryContactJobTitle { get; set; }
    public string? PrimaryContactEmailAddress { get; set; }
    public string? BusinessPhone { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? Zip { get; set; }
    public string? Website { get; set; }
    public string? Notes { get; set; }
}

public class CustomerLookupDto
{
    public int CustomerId { get; set; }
    public string? CustomerName { get; set; }
}

public class CustomerProductDto
{
    public int ProductId { get; set; }
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public int TotalQuantity { get; set; }
    public int OrderCount { get; set; }
    public DateTime? FirstOrderDate { get; set; }
    public DateTime? LastOrderDate { get; set; }
}

// --- Products ---

public class ProductDto
{
    public int ProductId { get; set; }
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public string? ProductDescription { get; set; }
    public decimal? UnitPrice { get; set; }
    public int TotalOrderCount { get; set; }
    public int SoldThisWeek { get; set; }
    public string? AddedBy { get; set; }
    public DateTime? AddedOn { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }
}

public class ProductRequest
{
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public string? ProductDescription { get; set; }
    public decimal? UnitPrice { get; set; }
}

public class ProductLookupDto
{
    public int ProductId { get; set; }
    public string? ProductName { get; set; }
    public string? ProductCode { get; set; }
    public decimal? UnitPrice { get; set; }
}

public class ProductOrderDto
{
    public int OrderId { get; set; }
    public DateTime? OrderDate { get; set; }
    public string? CustomerName { get; set; }
    public short? Quantity { get; set; }
    public decimal? UnitPrice { get; set; }
    public decimal ExtendedPrice { get; set; }
}

// --- Employees ---

public class EmployeeDto
{
    public int EmployeeId { get; set; }
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? FullNameFNLN { get; set; }
    public string? FullNameLNFN { get; set; }
    public string? EmailAddress { get; set; }
    public string? JobTitle { get; set; }
    public string? PrimaryPhone { get; set; }
    public string? SecondaryPhone { get; set; }
    public string? Title { get; set; }
    public string? Notes { get; set; }
    public string? WindowsUserName { get; set; }
    public string? AddedBy { get; set; }
    public DateTime? AddedOn { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }
}

public class EmployeeRequest
{
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? EmailAddress { get; set; }
    public string? JobTitle { get; set; }
    public string? PrimaryPhone { get; set; }
    public string? SecondaryPhone { get; set; }
    public string? Title { get; set; }
    public string? Notes { get; set; }
    public string? WindowsUserName { get; set; }
}

public class EmployeeLookupDto
{
    public int EmployeeId { get; set; }
    public string? FullNameFNLN { get; set; }
}

// --- Orders ---

public class OrderSummaryDto
{
    public int OrderId { get; set; }
    public int? CustomerId { get; set; }
    public string? CustomerName { get; set; }
    public int? EmployeeId { get; set; }
    public string? EmployeeFullName { get; set; }
    public int? StatusId { get; set; }
    public string? StatusName { get; set; }
    public DateTime? OrderDate { get; set; }
    public DateTime? ShippedDate { get; set; }
    public DateTime? PaidDate { get; set; }
    public string? Notes { get; set; }
    public decimal OrderTotal { get; set; }
    public string? AddedBy { get; set; }
    public DateTime? AddedOn { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }
}

public class OrderFullDto : OrderSummaryDto
{
    public List<OrderLineDto> OrderDetails { get; set; } = [];
}

public class OrderRequest
{
    public int? CustomerId { get; set; }
    public int? EmployeeId { get; set; }
    public int? StatusId { get; set; }
    public DateTime? OrderDate { get; set; }
    public DateTime? ShippedDate { get; set; }
    public DateTime? PaidDate { get; set; }
    public string? Notes { get; set; }
}

public class OrderLineDto
{
    public int OrderDetailId { get; set; }
    public int? ProductId { get; set; }
    public string? ProductName { get; set; }
    public string? ProductCode { get; set; }
    public short? Quantity { get; set; }
    public decimal? UnitPrice { get; set; }
    public decimal ExtendedPrice { get; set; }
}

public class OrderLineRequest
{
    public int? ProductId { get; set; }
    public short? Quantity { get; set; }
    public decimal? UnitPrice { get; set; }
}

// --- Order Statuses ---

public class OrderStatusDto
{
    public int StatusId { get; set; }
    public string? StatusCode { get; set; }
    public string? StatusName { get; set; }
    public byte? SortOrder { get; set; }
}

// --- System Settings ---

public class SystemSettingDto
{
    public int SettingId { get; set; }
    public string? SettingName { get; set; }
    public string? SettingValue { get; set; }
    public string? Notes { get; set; }
}

public class SystemSettingUpdateRequest
{
    public string? SettingValue { get; set; }
}

// --- Admin ---

public class GenerateOrdersRequest
{
    public int Count { get; set; } = 5;
}

public class GenerateOrdersResponse
{
    public int OrdersCreated { get; set; }
}

// --- Reports ---

public class SalesYtdDto
{
    public int Year { get; set; }
    public decimal TotalRevenue { get; set; }
}

public class SalesByEmployeeDto
{
    public int EmployeeId { get; set; }
    public string? EmployeeFullName { get; set; }
    public decimal TotalRevenue { get; set; }
}

public class SalesByProductDto
{
    public int ProductId { get; set; }
    public string? ProductName { get; set; }
    public string? MonthYear { get; set; }
    public string? MonthYearSort { get; set; }
    public decimal OrderTotal { get; set; }
}

public class SalesByProductQuarterlyDto
{
    public int ProductId { get; set; }
    public string? ProductName { get; set; }
    public string? QuarterYear { get; set; }
    public decimal OrderTotal { get; set; }
}

public class SalesByEmployeeMonthlyDto
{
    public int EmployeeId { get; set; }
    public string? EmployeeFullName { get; set; }
    public string? MonthYear { get; set; }
    public string? MonthYearSort { get; set; }
    public decimal OrderTotal { get; set; }
}

public class InvoiceLineItemDto
{
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public short Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal ExtendedPrice { get; set; }
}

public class InvoiceDto
{
    public int OrderId { get; set; }
    public DateTime? OrderDate { get; set; }
    public string? CustomerName { get; set; }
    public string? CustomerAddress { get; set; }
    public string? CustomerCity { get; set; }
    public string? CustomerState { get; set; }
    public string? CustomerZip { get; set; }
    public string? EmployeeFullName { get; set; }
    public string? StatusName { get; set; }
    public List<InvoiceLineItemDto> LineItems { get; set; } = [];
    public decimal OrderTotal { get; set; }
}

public class EmployeeEmailDto
{
    public int EmployeeId { get; set; }
    public string? FullNameLNFN { get; set; }
    public string? EmailAddress { get; set; }
}

public class EmployeePhoneDto
{
    public int EmployeeId { get; set; }
    public string? FullNameLNFN { get; set; }
    public string? PrimaryPhone { get; set; }
    public string? SecondaryPhone { get; set; }
}
