// Generated by booster-webdev | 2026-04-06
namespace WebApp.Models;

// ── Shared ───────────────────────────────────────────────────────────────────

public class PagedResult<T>
{
    public List<T> Items { get; set; } = [];
    public int TotalCount { get; set; }
    public int Page { get; set; }
    public int PageSize { get; set; }
    public int TotalPages => PageSize > 0 ? (int)Math.Ceiling((double)TotalCount / PageSize) : 1;
}

// ── Customers ─────────────────────────────────────────────────────────────────

public class CustomerListItem
{
    public int Id { get; set; }
    public string CustomerName { get; set; } = "";
    public string? PrimaryContactFirstName { get; set; }
    public string? PrimaryContactLastName { get; set; }
    public string? PrimaryContactFullName { get; set; }
    public string? PrimaryContactJobTitle { get; set; }
    public string? PrimaryContactEmailAddress { get; set; }
    public string? BusinessPhone { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? Zip { get; set; }
}

public class CustomerDetail : CustomerListItem
{
    public string? Website { get; set; }
    public string? Notes { get; set; }
    public string? AddedBy { get; set; }
    public DateTime? AddedOn { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }
}

public class CustomerFormData
{
    public string CustomerName { get; set; } = "";
    public string? PrimaryContactFirstName { get; set; }
    public string? PrimaryContactLastName { get; set; }
    public string? PrimaryContactJobTitle { get; set; }
    public string? PrimaryContactEmailAddress { get; set; }
    public string? BusinessPhone { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? Zip { get; set; }
    public string? Website { get; set; }
    public string? Notes { get; set; }
}

public class CustomerProductSummary
{
    public int ProductId { get; set; }
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public int TotalQuantity { get; set; }
    public int OrderCount { get; set; }
    public DateTime? FirstOrderDate { get; set; }
    public DateTime? LastOrderDate { get; set; }
}

// ── Employees ─────────────────────────────────────────────────────────────────

public class EmployeeListItem
{
    public int Id { get; set; }
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? FullNameFNLN { get; set; }
    public string? FullNameLNFN { get; set; }
    public string? EmailAddress { get; set; }
    public string? JobTitle { get; set; }
    public string? PrimaryPhone { get; set; }
    public string? SecondaryPhone { get; set; }
    public string? Title { get; set; }
}

public class EmployeeDetail : EmployeeListItem
{
    public string? Notes { get; set; }
    public string? WindowsUserName { get; set; }
    public string? AddedBy { get; set; }
    public DateTime? AddedOn { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }
}

public class EmployeeFormData
{
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? EmailAddress { get; set; }
    public string? JobTitle { get; set; }
    public string? PrimaryPhone { get; set; }
    public string? SecondaryPhone { get; set; }
    public string? Title { get; set; }
    public string? Notes { get; set; }
    public string? WindowsUserName { get; set; }
}

// ── Orders ────────────────────────────────────────────────────────────────────

public class OrderListItem
{
    public int Id { get; set; }
    public int? CustomerId { get; set; }
    public string? CustomerName { get; set; }
    public int? EmployeeId { get; set; }
    public string? EmployeeFullName { get; set; }
    public DateTime? OrderDate { get; set; }
    public DateTime? ShippedDate { get; set; }
    public DateTime? PaidDate { get; set; }
    public string? Status { get; set; }
    public string? StatusDisplay { get; set; }
    public decimal OrderTotal { get; set; }
    public DateTime? ModifiedOn { get; set; }
}

public class OrderDetail : OrderListItem
{
    public string? Notes { get; set; }
    public List<OrderLineItem> OrderDetails { get; set; } = [];
    public string? AddedBy { get; set; }
    public DateTime? AddedOn { get; set; }
    public string? ModifiedBy { get; set; }
}

public class OrderLineItem
{
    public int Id { get; set; }
    public int OrderId { get; set; }
    public int? ProductId { get; set; }
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public int Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal ExtendedPrice { get; set; }
}

public class OrderFormData
{
    public int? CustomerId { get; set; }
    public int? EmployeeId { get; set; }
    public DateTime? OrderDate { get; set; }
    public DateTime? ShippedDate { get; set; }
    public DateTime? PaidDate { get; set; }
    public string? Status { get; set; }
    public string? Notes { get; set; }
}

public class OrderLineFormData
{
    public int? ProductId { get; set; }
    public int Quantity { get; set; }
    public decimal UnitPrice { get; set; }
}

public class OrderStatusResult
{
    public int Id { get; set; }
    public string? Status { get; set; }
    public string? StatusDisplay { get; set; }
    public DateTime? ModifiedOn { get; set; }
}

// ── Products ──────────────────────────────────────────────────────────────────

public class ProductListItem
{
    public int Id { get; set; }
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public decimal UnitPrice { get; set; }
    public int? TotalQuantitySold { get; set; }
    public int? OrderCount { get; set; }
    public int? SoldThisWeek { get; set; }
}

public class ProductDetail : ProductListItem
{
    public string? ProductDescription { get; set; }
    public string? AddedBy { get; set; }
    public DateTime? AddedOn { get; set; }
    public string? ModifiedBy { get; set; }
    public DateTime? ModifiedOn { get; set; }
}

public class ProductFormData
{
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public string? ProductDescription { get; set; }
    public decimal UnitPrice { get; set; }
}

public class ProductOrderSummary
{
    public int OrderId { get; set; }
    public DateTime? OrderDate { get; set; }
    public string? CustomerName { get; set; }
    public int Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal ExtendedPrice { get; set; }
}

// ── Lookup ────────────────────────────────────────────────────────────────────

public class LookupCustomer
{
    public int Id { get; set; }
    public string? CustomerName { get; set; }
}

public class LookupEmployee
{
    public int Id { get; set; }
    public string? FullNameFNLN { get; set; }
}

public class LookupProduct
{
    public int Id { get; set; }
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public decimal UnitPrice { get; set; }
}

public class LookupOrderStatus
{
    public string? Value { get; set; }
    public string? Display { get; set; }
    public int SortOrder { get; set; }
}

// ── Reports ───────────────────────────────────────────────────────────────────

public class SalesYtd
{
    public int Year { get; set; }
    public decimal TotalSales { get; set; }
}

public class SalesByEmployee
{
    public int EmployeeId { get; set; }
    public string? EmployeeFullName { get; set; }
    public string? MonthYear { get; set; }
    public string? MonthYearSort { get; set; }
    public decimal TotalSales { get; set; }
}

public class SalesByProduct
{
    public int ProductId { get; set; }
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public string? Period { get; set; }
    public string? PeriodSort { get; set; }
    public decimal TotalSales { get; set; }
}

public class InvoiceReport
{
    public int OrderId { get; set; }
    public DateTime? OrderDate { get; set; }
    public InvoiceCustomer? Customer { get; set; }
    public InvoiceEmployee? Employee { get; set; }
    public string? Status { get; set; }
    public List<InvoiceLineItem> LineItems { get; set; } = [];
    public decimal Subtotal { get; set; }
    public decimal TaxRate { get; set; }
    public decimal TaxAmount { get; set; }
    public decimal Total { get; set; }
}

public class InvoiceCustomer
{
    public int Id { get; set; }
    public string? CustomerName { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? Zip { get; set; }
}

public class InvoiceEmployee
{
    public int Id { get; set; }
    public string? FullName { get; set; }
}

public class InvoiceLineItem
{
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public int Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal ExtendedPrice { get; set; }
}

public class EmployeeEmailEntry
{
    public int EmployeeId { get; set; }
    public string? FullNameLNFN { get; set; }
    public string? EmailAddress { get; set; }
}

public class EmployeePhoneEntry
{
    public int EmployeeId { get; set; }
    public string? FullNameLNFN { get; set; }
    public string? PrimaryPhone { get; set; }
    public string? SecondaryPhone { get; set; }
}

// ── Admin ─────────────────────────────────────────────────────────────────────

public class AdminSetting
{
    public int Id { get; set; }
    public string? SettingName { get; set; }
    public string? SettingValue { get; set; }
    public string? Notes { get; set; }
}

public class AdminGenerateResult
{
    public int OrdersCreated { get; set; }
}

public class AdminDeleteResult
{
    public string? Message { get; set; }
    public int CustomersDeleted { get; set; }
    public int EmployeesDeleted { get; set; }
    public int OrdersDeleted { get; set; }
    public int OrderDetailsDeleted { get; set; }
    public int ProductsDeleted { get; set; }
}
