// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.DTOs.Products;

public class ProductListItemDto
{
    public int Id { get; set; }
    public string? ProductCode { get; set; }
    public string? ProductName { get; set; }
    public decimal? UnitPrice { get; set; }
    public int? TotalQuantitySold { get; set; }
    public int? OrderCount { get; set; }
    public int? SoldThisWeek { get; set; }
}
