// Generated by booster-apidev | 2026-04-06 19:37:30

namespace ApiApp.DTOs.Products;

public class ProductOrderSummaryDto
{
    public int OrderId { get; set; }
    public DateTime? OrderDate { get; set; }
    public string? CustomerName { get; set; }
    public int Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal ExtendedPrice { get; set; }
}
