// Generated by booster-apidev | 2026-04-06 19:37:30

using System.ComponentModel.DataAnnotations;

namespace ApiApp.DTOs.Products;

public class ProductCreateUpdateDto
{
    [Required]
    [MaxLength(20)]
    public string ProductCode { get; set; } = string.Empty;

    [MaxLength(50)]
    public string? ProductName { get; set; }

    public string? ProductDescription { get; set; }

    [Range(0, double.MaxValue)]
    public decimal? UnitPrice { get; set; }
}
