// > Generated by booster-apidev | 2026-04-07 11:36:00
using System.Net;
using System.Net.Http.Json;
using ApiApp.DTOs;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class AdminControllerTests
{
    private TestWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;

    [OneTimeSetUp]
    public void OneTimeSetUp()
    {
        _factory = new TestWebApplicationFactory();
        _client = _factory.CreateClient();
    }

    [OneTimeTearDown]
    public void OneTimeTearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    [Test, Order(1)]
    public async Task GetSettings_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/admin/settings");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var settings = await response.Content.ReadFromJsonAsync<List<SystemSettingDto>>();
        Assert.That(settings, Is.Not.Null);
        Assert.That(settings!.Count, Is.GreaterThanOrEqualTo(1));
    }

    [Test, Order(2)]
    public async Task GetSettings_ContainsTaxRate()
    {
        var response = await _client.GetAsync("/api/admin/settings");
        var settings = await response.Content.ReadFromJsonAsync<List<SystemSettingDto>>();
        var taxRate = settings!.FirstOrDefault(s => s.SettingName == "TaxRate");
        Assert.That(taxRate, Is.Not.Null);
        Assert.That(taxRate!.SettingValue, Is.EqualTo("85"));
    }

    [Test, Order(3)]
    public async Task UpdateSetting_ExistingId_Returns200()
    {
        var settings = await (await _client.GetAsync("/api/admin/settings"))
            .Content.ReadFromJsonAsync<List<SystemSettingDto>>();
        var taxRate = settings!.First(s => s.SettingName == "TaxRate");

        var response = await _client.PutAsJsonAsync(
            $"/api/admin/settings/{taxRate.SettingId}",
            new SystemSettingUpdateRequest { SettingValue = "90" });

        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var updated = await response.Content.ReadFromJsonAsync<SystemSettingDto>();
        Assert.That(updated!.SettingValue, Is.EqualTo("90"));

        // Restore original value
        await _client.PutAsJsonAsync(
            $"/api/admin/settings/{taxRate.SettingId}",
            new SystemSettingUpdateRequest { SettingValue = "85" });
    }

    [Test, Order(4)]
    public async Task UpdateSetting_NonExistentId_Returns404()
    {
        var response = await _client.PutAsJsonAsync(
            "/api/admin/settings/99999",
            new SystemSettingUpdateRequest { SettingValue = "50" });
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(5)]
    public async Task GenerateOrders_WithValidCount_ReturnsOk()
    {
        var response = await _client.PostAsJsonAsync("/api/admin/generate-orders",
            new GenerateOrdersRequest { Count = 3 });
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var result = await response.Content.ReadFromJsonAsync<GenerateOrdersResponse>();
        Assert.That(result, Is.Not.Null);
        Assert.That(result!.OrdersCreated, Is.EqualTo(3));
    }

    [Test, Order(6)]
    public async Task GenerateOrders_WithInvalidCount_Returns400()
    {
        var response = await _client.PostAsJsonAsync("/api/admin/generate-orders",
            new GenerateOrdersRequest { Count = -1 });
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.BadRequest));
    }

    // This test runs last as it deletes all data
    [Test, Order(99)]
    public async Task DeleteTestData_Returns204()
    {
        var response = await _client.DeleteAsync("/api/admin/test-data");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NoContent));

        // Verify data is gone
        var customersResp = await _client.GetAsync("/api/customers");
        var customers = await customersResp.Content.ReadFromJsonAsync<List<CustomerDto>>();
        Assert.That(customers, Is.Empty);

        var ordersResp = await _client.GetAsync("/api/orders");
        var orders = await ordersResp.Content.ReadFromJsonAsync<List<OrderSummaryDto>>();
        Assert.That(orders, Is.Empty);
    }
}
