// > Generated by booster-apidev | 2026-04-07 11:36:00
using System.Net;
using System.Net.Http.Json;
using ApiApp.DTOs;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class CustomersControllerTests
{
    private TestWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;

    [OneTimeSetUp]
    public void OneTimeSetUp()
    {
        _factory = new TestWebApplicationFactory();
        _client = _factory.CreateClient();
    }

    [OneTimeTearDown]
    public void OneTimeTearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    [Test, Order(1)]
    public async Task GetCustomers_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/customers");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var customers = await response.Content.ReadFromJsonAsync<List<CustomerDto>>();
        Assert.That(customers, Is.Not.Null);
    }

    [Test, Order(2)]
    public async Task GetCustomers_WithSearch_FiltersResults()
    {
        // Seeder adds customers in local env
        var response = await _client.GetAsync("/api/customers?search=Contoso");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var customers = await response.Content.ReadFromJsonAsync<List<CustomerDto>>();
        Assert.That(customers, Is.Not.Null);
        Assert.That(customers!.All(c => c.CustomerName!.Contains("Contoso") ||
            (c.City != null && c.City.Contains("Contoso")) ||
            (c.State != null && c.State.Contains("Contoso"))), Is.True);
    }

    [Test, Order(3)]
    public async Task GetCustomers_WithNoMatch_ReturnsEmpty()
    {
        var response = await _client.GetAsync("/api/customers?search=zzz_no_match_zzz");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var customers = await response.Content.ReadFromJsonAsync<List<CustomerDto>>();
        Assert.That(customers, Is.Empty);
    }

    [Test, Order(4)]
    public async Task GetCustomerLookup_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/customers/lookup");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var items = await response.Content.ReadFromJsonAsync<List<CustomerLookupDto>>();
        Assert.That(items, Is.Not.Null);
    }

    [Test, Order(5)]
    public async Task CreateCustomer_WithValidData_Returns201()
    {
        var request = new CustomerRequest
        {
            CustomerName = "Test Corp",
            PrimaryContactFirstName = "Alice",
            PrimaryContactLastName = "Smith",
            City = "Renton",
            State = "WA"
        };
        var response = await _client.PostAsJsonAsync("/api/customers", request);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.Created));
        var customer = await response.Content.ReadFromJsonAsync<CustomerDto>();
        Assert.That(customer, Is.Not.Null);
        Assert.That(customer!.CustomerId, Is.GreaterThan(0));
        Assert.That(customer.CustomerName, Is.EqualTo("Test Corp"));
        Assert.That(customer.AddedOn, Is.Not.Null);
    }

    [Test, Order(6)]
    public async Task GetCustomerById_ExistingId_Returns200()
    {
        // Create one first
        var created = await CreateTestCustomer("GetById Corp");
        var response = await _client.GetAsync($"/api/customers/{created.CustomerId}");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var customer = await response.Content.ReadFromJsonAsync<CustomerDto>();
        Assert.That(customer!.CustomerId, Is.EqualTo(created.CustomerId));
    }

    [Test, Order(7)]
    public async Task GetCustomerById_NonExistentId_Returns404()
    {
        var response = await _client.GetAsync("/api/customers/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(8)]
    public async Task UpdateCustomer_ExistingId_Returns200()
    {
        var created = await CreateTestCustomer("Update Test Corp");
        var updateRequest = new CustomerRequest { CustomerName = "Updated Corp", City = "Bothell", State = "WA" };
        var response = await _client.PutAsJsonAsync($"/api/customers/{created.CustomerId}", updateRequest);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var updated = await response.Content.ReadFromJsonAsync<CustomerDto>();
        Assert.That(updated!.CustomerName, Is.EqualTo("Updated Corp"));
        Assert.That(updated.ModifiedOn, Is.Not.Null);
    }

    [Test, Order(9)]
    public async Task UpdateCustomer_NonExistentId_Returns404()
    {
        var updateRequest = new CustomerRequest { CustomerName = "Ghost" };
        var response = await _client.PutAsJsonAsync("/api/customers/99999", updateRequest);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(10)]
    public async Task GetCustomerOrders_ExistingId_ReturnsOk()
    {
        var created = await CreateTestCustomer("Orders Customer");
        var response = await _client.GetAsync($"/api/customers/{created.CustomerId}/orders");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
    }

    [Test, Order(11)]
    public async Task GetCustomerOrders_NonExistentId_Returns404()
    {
        var response = await _client.GetAsync("/api/customers/99999/orders");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(12)]
    public async Task GetCustomerProducts_ExistingId_ReturnsOk()
    {
        var created = await CreateTestCustomer("Products Customer");
        var response = await _client.GetAsync($"/api/customers/{created.CustomerId}/products");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
    }

    [Test, Order(13)]
    public async Task DeleteCustomer_ExistingId_Returns204()
    {
        var created = await CreateTestCustomer("Delete Test Corp");
        var response = await _client.DeleteAsync($"/api/customers/{created.CustomerId}");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NoContent));
    }

    [Test, Order(14)]
    public async Task DeleteCustomer_NonExistentId_Returns404()
    {
        var response = await _client.DeleteAsync("/api/customers/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    private async Task<CustomerDto> CreateTestCustomer(string name)
    {
        var request = new CustomerRequest { CustomerName = name, City = "Seattle", State = "WA" };
        var response = await _client.PostAsJsonAsync("/api/customers", request);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<CustomerDto>())!;
    }
}
