// > Generated by booster-apidev | 2026-04-07 11:36:00
using System.Net;
using System.Net.Http.Json;
using ApiApp.DTOs;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class EmployeesControllerTests
{
    private TestWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;

    [OneTimeSetUp]
    public void OneTimeSetUp()
    {
        _factory = new TestWebApplicationFactory();
        _client = _factory.CreateClient();
    }

    [OneTimeTearDown]
    public void OneTimeTearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    [Test, Order(1)]
    public async Task GetEmployees_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/employees");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var employees = await response.Content.ReadFromJsonAsync<List<EmployeeDto>>();
        Assert.That(employees, Is.Not.Null);
        // Seeder creates 9 normal + 1 system (id=10) = 10 employees
        Assert.That(employees!.Count, Is.GreaterThanOrEqualTo(1));
    }

    [Test, Order(2)]
    public async Task GetEmployeeLookup_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/employees/lookup");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var items = await response.Content.ReadFromJsonAsync<List<EmployeeLookupDto>>();
        Assert.That(items, Is.Not.Null);
    }

    [Test, Order(3)]
    public async Task CreateEmployee_WithValidData_Returns201()
    {
        var request = new EmployeeRequest
        {
            FirstName = "Test",
            LastName = "Employee",
            EmailAddress = "test.emp@northwind.com",
            JobTitle = "Tester",
            WindowsUserName = $"temployee_{Guid.NewGuid():N}"
        };
        var response = await _client.PostAsJsonAsync("/api/employees", request);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.Created));
        var employee = await response.Content.ReadFromJsonAsync<EmployeeDto>();
        Assert.That(employee, Is.Not.Null);
        Assert.That(employee!.EmployeeId, Is.GreaterThan(0));
        Assert.That(employee.FullNameFNLN, Is.EqualTo("Test Employee"));
        Assert.That(employee.AddedOn, Is.Not.Null);
    }

    [Test, Order(4)]
    public async Task GetEmployeeById_ExistingId_Returns200()
    {
        var created = await CreateTestEmployee();
        var response = await _client.GetAsync($"/api/employees/{created.EmployeeId}");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var employee = await response.Content.ReadFromJsonAsync<EmployeeDto>();
        Assert.That(employee!.EmployeeId, Is.EqualTo(created.EmployeeId));
    }

    [Test, Order(5)]
    public async Task GetEmployeeById_NonExistentId_Returns404()
    {
        var response = await _client.GetAsync("/api/employees/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(6)]
    public async Task UpdateEmployee_ExistingId_Returns200()
    {
        var created = await CreateTestEmployee();
        var updateRequest = new EmployeeRequest
        {
            FirstName = "Updated",
            LastName = "Employee",
            JobTitle = "Senior Tester",
            WindowsUserName = created.WindowsUserName
        };
        var response = await _client.PutAsJsonAsync($"/api/employees/{created.EmployeeId}", updateRequest);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var updated = await response.Content.ReadFromJsonAsync<EmployeeDto>();
        Assert.That(updated!.FirstName, Is.EqualTo("Updated"));
        Assert.That(updated.ModifiedOn, Is.Not.Null);
    }

    [Test, Order(7)]
    public async Task UpdateEmployee_NonExistentId_Returns404()
    {
        var response = await _client.PutAsJsonAsync("/api/employees/99999",
            new EmployeeRequest { FirstName = "Ghost" });
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(8)]
    public async Task GetEmployeeOrders_ExistingId_ReturnsOk()
    {
        var created = await CreateTestEmployee();
        var response = await _client.GetAsync($"/api/employees/{created.EmployeeId}/orders");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
    }

    [Test, Order(9)]
    public async Task GetEmployeeOrders_NonExistentId_Returns404()
    {
        var response = await _client.GetAsync("/api/employees/99999/orders");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(10)]
    public async Task DeleteEmployee_ExistingId_Returns204()
    {
        var created = await CreateTestEmployee();
        var response = await _client.DeleteAsync($"/api/employees/{created.EmployeeId}");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NoContent));
    }

    [Test, Order(11)]
    public async Task DeleteEmployee_NonExistentId_Returns404()
    {
        var response = await _client.DeleteAsync("/api/employees/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    private async Task<EmployeeDto> CreateTestEmployee()
    {
        var request = new EmployeeRequest
        {
            FirstName = "Test",
            LastName = "User",
            EmailAddress = $"test.{Guid.NewGuid():N}@northwind.com",
            WindowsUserName = $"tuser_{Guid.NewGuid():N}"
        };
        var response = await _client.PostAsJsonAsync("/api/employees", request);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<EmployeeDto>())!;
    }
}
