// > Generated by booster-apidev | 2026-04-07 11:36:00
using System.Net;
using System.Net.Http.Json;
using ApiApp.DTOs;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class OrderDetailsControllerTests
{
    private TestWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;
    private int _orderId;
    private int _productId;

    [OneTimeSetUp]
    public async Task OneTimeSetUp()
    {
        _factory = new TestWebApplicationFactory();
        _client = _factory.CreateClient();

        // Create a product for line item tests
        var prodResp = await _client.PostAsJsonAsync("/api/products",
            new ProductRequest { ProductCode = $"TST{Guid.NewGuid().ToString("N")[..4]}", ProductName = "Test Product", UnitPrice = 15.00m });
        var product = await prodResp.Content.ReadFromJsonAsync<ProductDto>();
        _productId = product!.ProductId;

        // Create a customer and order
        var custResp = await _client.PostAsJsonAsync("/api/customers",
            new CustomerRequest { CustomerName = "LineItem Customer", City = "Seattle", State = "WA" });
        var cust = await custResp.Content.ReadFromJsonAsync<CustomerDto>();

        var orderResp = await _client.PostAsJsonAsync("/api/orders",
            new OrderRequest { CustomerId = cust!.CustomerId, StatusId = 3, OrderDate = DateTime.UtcNow });
        var order = await orderResp.Content.ReadFromJsonAsync<OrderSummaryDto>();
        _orderId = order!.OrderId;
    }

    [OneTimeTearDown]
    public void OneTimeTearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    [Test, Order(1)]
    public async Task GetDetails_ExistingOrder_ReturnsOk()
    {
        var response = await _client.GetAsync($"/api/orders/{_orderId}/details");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var details = await response.Content.ReadFromJsonAsync<List<OrderLineDto>>();
        Assert.That(details, Is.Not.Null);
    }

    [Test, Order(2)]
    public async Task GetDetails_NonExistentOrder_Returns404()
    {
        var response = await _client.GetAsync("/api/orders/99999/details");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(3)]
    public async Task CreateDetail_WithValidData_Returns201()
    {
        var request = new OrderLineRequest { ProductId = _productId, Quantity = 3, UnitPrice = 15.00m };
        var response = await _client.PostAsJsonAsync($"/api/orders/{_orderId}/details", request);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.Created));
        var detail = await response.Content.ReadFromJsonAsync<OrderLineDto>();
        Assert.That(detail, Is.Not.Null);
        Assert.That(detail!.OrderDetailId, Is.GreaterThan(0));
        Assert.That(detail.Quantity, Is.EqualTo(3));
        Assert.That(detail.ExtendedPrice, Is.EqualTo(45.00m));
    }

    [Test, Order(4)]
    public async Task CreateDetail_DefaultsUnitPriceFromProduct()
    {
        var request = new OrderLineRequest { ProductId = _productId, Quantity = 2 };
        var response = await _client.PostAsJsonAsync($"/api/orders/{_orderId}/details", request);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.Created));
        var detail = await response.Content.ReadFromJsonAsync<OrderLineDto>();
        Assert.That(detail!.UnitPrice, Is.EqualTo(15.00m)); // from product
    }

    [Test, Order(5)]
    public async Task CreateDetail_NonExistentOrder_Returns404()
    {
        var request = new OrderLineRequest { ProductId = _productId, Quantity = 1, UnitPrice = 10m };
        var response = await _client.PostAsJsonAsync("/api/orders/99999/details", request);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(6)]
    public async Task UpdateDetail_ExistingIds_Returns200()
    {
        var created = await CreateTestDetail();
        var updateRequest = new OrderLineRequest { ProductId = _productId, Quantity = 5, UnitPrice = 12.50m };
        var response = await _client.PutAsJsonAsync(
            $"/api/orders/{_orderId}/details/{created.OrderDetailId}", updateRequest);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var updated = await response.Content.ReadFromJsonAsync<OrderLineDto>();
        Assert.That(updated!.Quantity, Is.EqualTo(5));
        Assert.That(updated.UnitPrice, Is.EqualTo(12.50m));
        Assert.That(updated.ExtendedPrice, Is.EqualTo(62.50m));
    }

    [Test, Order(7)]
    public async Task UpdateDetail_NonExistentDetail_Returns404()
    {
        var response = await _client.PutAsJsonAsync(
            $"/api/orders/{_orderId}/details/99999",
            new OrderLineRequest { Quantity = 1, UnitPrice = 10m });
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(8)]
    public async Task DeleteDetail_ExistingIds_Returns204()
    {
        var created = await CreateTestDetail();
        var response = await _client.DeleteAsync($"/api/orders/{_orderId}/details/{created.OrderDetailId}");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NoContent));
    }

    [Test, Order(9)]
    public async Task DeleteDetail_NonExistentDetail_Returns404()
    {
        var response = await _client.DeleteAsync($"/api/orders/{_orderId}/details/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    private async Task<OrderLineDto> CreateTestDetail()
    {
        var request = new OrderLineRequest { ProductId = _productId, Quantity = 1, UnitPrice = 15.00m };
        var response = await _client.PostAsJsonAsync($"/api/orders/{_orderId}/details", request);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<OrderLineDto>())!;
    }
}
