// > Generated by booster-apidev | 2026-04-07 11:36:00
using System.Net;
using System.Net.Http.Json;
using ApiApp.DTOs;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class OrdersControllerTests
{
    private TestWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;
    private int _customerId;
    private int _employeeId;

    [OneTimeSetUp]
    public async Task OneTimeSetUp()
    {
        _factory = new TestWebApplicationFactory();
        _client = _factory.CreateClient();

        // Create a customer and employee for order tests
        var custResp = await _client.PostAsJsonAsync("/api/customers",
            new CustomerRequest { CustomerName = "Order Test Corp", City = "Seattle", State = "WA" });
        var cust = await custResp.Content.ReadFromJsonAsync<CustomerDto>();
        _customerId = cust!.CustomerId;

        var empResp = await _client.PostAsJsonAsync("/api/employees",
            new EmployeeRequest { FirstName = "Order", LastName = "Tester", WindowsUserName = $"ot_{Guid.NewGuid():N}" });
        var emp = await empResp.Content.ReadFromJsonAsync<EmployeeDto>();
        _employeeId = emp!.EmployeeId;
    }

    [OneTimeTearDown]
    public void OneTimeTearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    [Test, Order(1)]
    public async Task GetOrders_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/orders");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var orders = await response.Content.ReadFromJsonAsync<List<OrderSummaryDto>>();
        Assert.That(orders, Is.Not.Null);
    }

    [Test, Order(2)]
    public async Task GetOrders_WithFilters_ReturnsFiltered()
    {
        var response = await _client.GetAsync($"/api/orders?customerId={_customerId}");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var orders = await response.Content.ReadFromJsonAsync<List<OrderSummaryDto>>();
        Assert.That(orders, Is.Not.Null);
        Assert.That(orders!.All(o => o.CustomerId == _customerId), Is.True);
    }

    [Test, Order(3)]
    public async Task GetOrders_WithTopLimit_RespectsLimit()
    {
        // Create 5 orders
        for (int i = 0; i < 5; i++)
            await CreateTestOrder();

        var response = await _client.GetAsync("/api/orders?top=2");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var orders = await response.Content.ReadFromJsonAsync<List<OrderSummaryDto>>();
        Assert.That(orders!.Count, Is.LessThanOrEqualTo(2));
    }

    [Test, Order(4)]
    public async Task CreateOrder_WithValidData_Returns201()
    {
        var request = new OrderRequest
        {
            CustomerId = _customerId,
            EmployeeId = _employeeId,
            StatusId = 3,
            OrderDate = DateTime.UtcNow
        };
        var response = await _client.PostAsJsonAsync("/api/orders", request);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.Created));
        var order = await response.Content.ReadFromJsonAsync<OrderSummaryDto>();
        Assert.That(order, Is.Not.Null);
        Assert.That(order!.OrderId, Is.GreaterThan(0));
        Assert.That(order.StatusId, Is.EqualTo(3));
        Assert.That(order.AddedOn, Is.Not.Null);
    }

    [Test, Order(5)]
    public async Task CreateOrder_DefaultsStatusToNew()
    {
        var request = new OrderRequest { CustomerId = _customerId, OrderDate = DateTime.UtcNow };
        var response = await _client.PostAsJsonAsync("/api/orders", request);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.Created));
        var order = await response.Content.ReadFromJsonAsync<OrderSummaryDto>();
        Assert.That(order!.StatusId, Is.EqualTo(3)); // NEW
    }

    [Test, Order(6)]
    public async Task GetOrderById_ExistingId_Returns200WithDetails()
    {
        var created = await CreateTestOrder();
        var response = await _client.GetAsync($"/api/orders/{created.OrderId}");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var order = await response.Content.ReadFromJsonAsync<OrderFullDto>();
        Assert.That(order, Is.Not.Null);
        Assert.That(order!.OrderDetails, Is.Not.Null);
    }

    [Test, Order(7)]
    public async Task GetOrderById_NonExistentId_Returns404()
    {
        var response = await _client.GetAsync("/api/orders/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(8)]
    public async Task UpdateOrder_ExistingId_Returns200()
    {
        var created = await CreateTestOrder();
        var updateRequest = new OrderRequest
        {
            CustomerId = _customerId,
            EmployeeId = _employeeId,
            StatusId = 2, // Invoiced
            OrderDate = DateTime.UtcNow
        };
        var response = await _client.PutAsJsonAsync($"/api/orders/{created.OrderId}", updateRequest);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var updated = await response.Content.ReadFromJsonAsync<OrderSummaryDto>();
        Assert.That(updated!.StatusId, Is.EqualTo(2));
        Assert.That(updated.ModifiedOn, Is.Not.Null);
    }

    [Test, Order(9)]
    public async Task UpdateOrder_NonExistentId_Returns404()
    {
        var response = await _client.PutAsJsonAsync("/api/orders/99999",
            new OrderRequest { OrderDate = DateTime.UtcNow });
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(10)]
    public async Task DeleteOrder_ExistingId_Returns204()
    {
        var created = await CreateTestOrder();
        var response = await _client.DeleteAsync($"/api/orders/{created.OrderId}");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NoContent));
        // Verify deleted
        var getResp = await _client.GetAsync($"/api/orders/{created.OrderId}");
        Assert.That(getResp.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(11)]
    public async Task DeleteOrder_NonExistentId_Returns404()
    {
        var response = await _client.DeleteAsync("/api/orders/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    private async Task<OrderSummaryDto> CreateTestOrder()
    {
        var request = new OrderRequest
        {
            CustomerId = _customerId,
            EmployeeId = _employeeId,
            StatusId = 3,
            OrderDate = DateTime.UtcNow
        };
        var response = await _client.PostAsJsonAsync("/api/orders", request);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<OrderSummaryDto>())!;
    }
}
