// > Generated by booster-apidev | 2026-04-07 11:36:00
using System.Net;
using System.Net.Http.Json;
using ApiApp.DTOs;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class OrderStatusesControllerTests
{
    private TestWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;

    [OneTimeSetUp]
    public void OneTimeSetUp()
    {
        _factory = new TestWebApplicationFactory();
        _client = _factory.CreateClient();
    }

    [OneTimeTearDown]
    public void OneTimeTearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    [Test]
    public async Task GetOrderStatuses_ReturnsAllStatuses()
    {
        var response = await _client.GetAsync("/api/orderstatuses");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var statuses = await response.Content.ReadFromJsonAsync<List<OrderStatusDto>>();
        Assert.That(statuses, Is.Not.Null);
        Assert.That(statuses!.Count, Is.EqualTo(5));
    }

    [Test]
    public async Task GetOrderStatuses_ContainsExpectedStatuses()
    {
        var response = await _client.GetAsync("/api/orderstatuses");
        var statuses = await response.Content.ReadFromJsonAsync<List<OrderStatusDto>>();

        Assert.That(statuses!.Any(s => s.StatusCode == "NEW" && s.StatusId == 3), Is.True);
        Assert.That(statuses.Any(s => s.StatusCode == "INV" && s.StatusId == 2), Is.True);
        Assert.That(statuses.Any(s => s.StatusCode == "SHI" && s.StatusId == 4), Is.True);
        Assert.That(statuses.Any(s => s.StatusCode == "PAY" && s.StatusId == 5), Is.True);
        Assert.That(statuses.Any(s => s.StatusCode == "CLO" && s.StatusId == 1), Is.True);
    }

    [Test]
    public async Task GetOrderStatuses_ReturnsSortedBySortOrder()
    {
        var response = await _client.GetAsync("/api/orderstatuses");
        var statuses = await response.Content.ReadFromJsonAsync<List<OrderStatusDto>>();

        var sortOrders = statuses!.Select(s => (int)(s.SortOrder ?? 0)).ToList();
        Assert.That(sortOrders, Is.Ordered.Ascending);
    }
}
