// > Generated by booster-apidev | 2026-04-07 11:36:00
using System.Net;
using System.Net.Http.Json;
using ApiApp.DTOs;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class ProductsControllerTests
{
    private TestWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;

    [OneTimeSetUp]
    public void OneTimeSetUp()
    {
        _factory = new TestWebApplicationFactory();
        _client = _factory.CreateClient();
    }

    [OneTimeTearDown]
    public void OneTimeTearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    [Test, Order(1)]
    public async Task GetProducts_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/products");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var products = await response.Content.ReadFromJsonAsync<List<ProductDto>>();
        Assert.That(products, Is.Not.Null);
        // Seeder creates 10 products
        Assert.That(products!.Count, Is.GreaterThanOrEqualTo(10));
    }

    [Test, Order(2)]
    public async Task GetProducts_WithSearch_FiltersResults()
    {
        var response = await _client.GetAsync("/api/products?search=Chai");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var products = await response.Content.ReadFromJsonAsync<List<ProductDto>>();
        Assert.That(products, Is.Not.Null);
        Assert.That(products!.Any(p => p.ProductName!.Contains("Chai")), Is.True);
    }

    [Test, Order(3)]
    public async Task GetProducts_WithNoMatch_ReturnsEmpty()
    {
        var response = await _client.GetAsync("/api/products?search=zzz_no_match_zzz");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var products = await response.Content.ReadFromJsonAsync<List<ProductDto>>();
        Assert.That(products, Is.Empty);
    }

    [Test, Order(4)]
    public async Task GetProducts_IncludesMetrics()
    {
        var response = await _client.GetAsync("/api/products");
        var products = await response.Content.ReadFromJsonAsync<List<ProductDto>>();
        // Seeder creates orders with products, so some should have orderCount > 0
        Assert.That(products!.Any(p => p.TotalOrderCount >= 0), Is.True);
    }

    [Test, Order(5)]
    public async Task GetProductLookup_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/products/lookup");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var items = await response.Content.ReadFromJsonAsync<List<ProductLookupDto>>();
        Assert.That(items, Is.Not.Null);
        Assert.That(items!.All(p => p.UnitPrice.HasValue), Is.True);
    }

    [Test, Order(6)]
    public async Task CreateProduct_WithValidData_Returns201()
    {
        var request = new ProductRequest
        {
            ProductCode = $"P{Guid.NewGuid().ToString("N")[..6]}",
            ProductName = "Test Product",
            ProductDescription = "A product for testing",
            UnitPrice = 12.99m
        };
        var response = await _client.PostAsJsonAsync("/api/products", request);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.Created));
        var product = await response.Content.ReadFromJsonAsync<ProductDto>();
        Assert.That(product, Is.Not.Null);
        Assert.That(product!.ProductId, Is.GreaterThan(0));
        Assert.That(product.UnitPrice, Is.EqualTo(12.99m));
        Assert.That(product.AddedOn, Is.Not.Null);
    }

    [Test, Order(7)]
    public async Task GetProductById_ExistingId_Returns200()
    {
        var created = await CreateTestProduct();
        var response = await _client.GetAsync($"/api/products/{created.ProductId}");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var product = await response.Content.ReadFromJsonAsync<ProductDto>();
        Assert.That(product!.ProductId, Is.EqualTo(created.ProductId));
    }

    [Test, Order(8)]
    public async Task GetProductById_NonExistentId_Returns404()
    {
        var response = await _client.GetAsync("/api/products/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(9)]
    public async Task UpdateProduct_ExistingId_Returns200()
    {
        var created = await CreateTestProduct();
        var updateRequest = new ProductRequest
        {
            ProductCode = created.ProductCode,
            ProductName = "Updated Product",
            UnitPrice = 20.00m
        };
        var response = await _client.PutAsJsonAsync($"/api/products/{created.ProductId}", updateRequest);
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var updated = await response.Content.ReadFromJsonAsync<ProductDto>();
        Assert.That(updated!.ProductName, Is.EqualTo("Updated Product"));
        Assert.That(updated.UnitPrice, Is.EqualTo(20.00m));
        Assert.That(updated.ModifiedOn, Is.Not.Null);
    }

    [Test, Order(10)]
    public async Task UpdateProduct_NonExistentId_Returns404()
    {
        var response = await _client.PutAsJsonAsync("/api/products/99999",
            new ProductRequest { ProductName = "Ghost", ProductCode = "GHO01" });
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(11)]
    public async Task GetProductOrders_ExistingId_ReturnsOk()
    {
        var created = await CreateTestProduct();
        var response = await _client.GetAsync($"/api/products/{created.ProductId}/orders");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
    }

    [Test, Order(12)]
    public async Task GetProductOrders_NonExistentId_Returns404()
    {
        var response = await _client.GetAsync("/api/products/99999/orders");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test, Order(13)]
    public async Task DeleteProduct_ExistingId_Returns204()
    {
        var created = await CreateTestProduct();
        var response = await _client.DeleteAsync($"/api/products/{created.ProductId}");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NoContent));
    }

    [Test, Order(14)]
    public async Task DeleteProduct_NonExistentId_Returns404()
    {
        var response = await _client.DeleteAsync("/api/products/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    private async Task<ProductDto> CreateTestProduct()
    {
        var request = new ProductRequest
        {
            ProductCode = $"P{Guid.NewGuid().ToString("N")[..6]}",
            ProductName = $"Test Product {Guid.NewGuid().ToString("N")[..4]}",
            UnitPrice = 9.99m
        };
        var response = await _client.PostAsJsonAsync("/api/products", request);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<ProductDto>())!;
    }
}
