// > Generated by booster-apidev | 2026-04-07 11:36:00
using System.Net;
using System.Net.Http.Json;
using ApiApp.DTOs;
using NUnit.Framework;

namespace ApiApp.Tests;

[TestFixture]
public class ReportsControllerTests
{
    private TestWebApplicationFactory _factory = null!;
    private HttpClient _client = null!;

    [OneTimeSetUp]
    public void OneTimeSetUp()
    {
        _factory = new TestWebApplicationFactory();
        _client = _factory.CreateClient();
    }

    [OneTimeTearDown]
    public void OneTimeTearDown()
    {
        _client.Dispose();
        _factory.Dispose();
    }

    [Test]
    public async Task GetSalesYtd_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reports/sales-ytd");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var result = await response.Content.ReadFromJsonAsync<SalesYtdDto>();
        Assert.That(result, Is.Not.Null);
        Assert.That(result!.Year, Is.EqualTo(DateTime.UtcNow.Year));
        Assert.That(result.TotalRevenue, Is.GreaterThanOrEqualTo(0));
    }

    [Test]
    public async Task GetSalesByEmployee_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reports/sales-by-employee");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var result = await response.Content.ReadFromJsonAsync<List<SalesByEmployeeDto>>();
        Assert.That(result, Is.Not.Null);
    }

    [Test]
    public async Task GetSalesByProduct_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reports/sales-by-product");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var result = await response.Content.ReadFromJsonAsync<List<SalesByProductDto>>();
        Assert.That(result, Is.Not.Null);
    }

    [Test]
    public async Task GetSalesByProduct_WithDateFilter_ReturnsFiltered()
    {
        var from = DateTime.UtcNow.AddDays(-30).ToString("yyyy-MM-dd");
        var to = DateTime.UtcNow.ToString("yyyy-MM-dd");
        var response = await _client.GetAsync($"/api/reports/sales-by-product?from={from}&to={to}");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
    }

    [Test]
    public async Task GetSalesByProductQuarterly_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reports/sales-by-product-quarterly");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var result = await response.Content.ReadFromJsonAsync<List<SalesByProductQuarterlyDto>>();
        Assert.That(result, Is.Not.Null);
    }

    [Test]
    public async Task GetSalesByEmployeeMonthly_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reports/sales-by-employee-monthly");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var result = await response.Content.ReadFromJsonAsync<List<SalesByEmployeeMonthlyDto>>();
        Assert.That(result, Is.Not.Null);
    }

    [Test]
    public async Task GetInvoice_NonExistentOrder_Returns404()
    {
        var response = await _client.GetAsync("/api/reports/invoice/99999");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
    }

    [Test]
    public async Task GetInvoice_ExistingOrder_ReturnsInvoice()
    {
        // Create an order with a line item
        var custResp = await _client.PostAsJsonAsync("/api/customers",
            new CustomerRequest { CustomerName = "Invoice Cust", City = "Seattle", State = "WA" });
        var cust = await custResp.Content.ReadFromJsonAsync<CustomerDto>();

        var prodResp = await _client.PostAsJsonAsync("/api/products",
            new ProductRequest { ProductCode = $"INV{Guid.NewGuid().ToString("N")[..4]}", ProductName = "Invoice Prod", UnitPrice = 25.00m });
        var prod = await prodResp.Content.ReadFromJsonAsync<ProductDto>();

        var orderResp = await _client.PostAsJsonAsync("/api/orders",
            new OrderRequest { CustomerId = cust!.CustomerId, StatusId = 3, OrderDate = DateTime.UtcNow });
        var order = await orderResp.Content.ReadFromJsonAsync<OrderSummaryDto>();

        await _client.PostAsJsonAsync($"/api/orders/{order!.OrderId}/details",
            new OrderLineRequest { ProductId = prod!.ProductId, Quantity = 2, UnitPrice = 25.00m });

        var response = await _client.GetAsync($"/api/reports/invoice/{order.OrderId}");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var invoice = await response.Content.ReadFromJsonAsync<InvoiceDto>();
        Assert.That(invoice, Is.Not.Null);
        Assert.That(invoice!.LineItems.Count, Is.EqualTo(1));
        Assert.That(invoice.OrderTotal, Is.EqualTo(50.00m));
    }

    [Test]
    public async Task GetEmployeeEmailList_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reports/employee-email-list");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var result = await response.Content.ReadFromJsonAsync<List<EmployeeEmailDto>>();
        Assert.That(result, Is.Not.Null);
    }

    [Test]
    public async Task GetEmployeePhoneList_ReturnsOk()
    {
        var response = await _client.GetAsync("/api/reports/employee-phone-list");
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        var result = await response.Content.ReadFromJsonAsync<List<EmployeePhoneDto>>();
        Assert.That(result, Is.Not.Null);
    }
}
